'''opposite_day_strategy.py
Implements the "Opposite Day" sandbox strategy.

The idea is simple: for every active pick generated by the main signal
engine we open a *mirror* position with the opposite direction.  This is
intended as a research sandbox to evaluate whether the opposite side of the
signal has any statistical edge.\n
The script performs three steps:

1. Load the current active picks from ``crypto_signal_engine/data/active_picks.json``.
2. For each pick, flip the direction (LONG ↔ SHORT) and recompute the
   entry, TP and SL using the same risk parameters.  The opposite pick is
   stored in ``sandbox/opposite_day_picks.json``.
3. Update a lightweight performance tracker (win‑rate, profit factor) that
   lives in ``sandbox/opposite_day_stats.json``.  The tracker is updated
   each time the script runs – it closes any opposite picks that have hit
   TP/SL based on the latest market price and records the result.

The module can be invoked from the command line:

    python opposite_day_strategy.py --run

or imported and used programmatically.
'''

import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any

import requests

# ---------------------------------------------------------------------------
# Configuration – paths are relative to the repository root.
# ---------------------------------------------------------------------------
ROOT = Path(__file__).parent
DATA_DIR = ROOT / "crypto_signal_engine" / "data"
SANDBOX_DIR = ROOT / "sandbox"
SANDBOX_DIR.mkdir(parents=True, exist_ok=True)

ACTIVE_PICKS_PATH = DATA_DIR / "active_picks.json"
OPPOSITE_PICKS_PATH = SANDBOX_DIR / "opposite_day_picks.json"
OPPOSITE_STATS_PATH = SANDBOX_DIR / "opposite_day_stats.json"

# ---------------------------------------------------------------------------
# Helper functions for price fetching – we reuse the same endpoint that the
# main engine uses (CoinGecko public API).  This keeps the sandbox lightweight
# and does not require an API key.
# ---------------------------------------------------------------------------

def fetch_current_prices(symbols: List[str]) -> Dict[str, float]:
    """Fetch the latest market price for each *symbol*.

    The function queries CoinGecko's simple price endpoint which accepts a
    comma‑separated list of ids.  The mapping from exchange symbols to
    CoinGecko ids is hard‑coded for the most common assets – unknown symbols
    are ignored.
    """
    # Minimal mapping – extend as needed.
    symbol_to_id = {
        "BTC": "bitcoin",
        "ETH": "ethereum",
        "BNB": "binancecoin",
        "SOL": "solana",
        "AVAX": "avalanche-2",
        "DOT": "polkadot",
        "DOGE": "dogecoin",
        "SHIB": "shiba-inu",
    }
    ids = [symbol_to_id.get(s.upper()) for s in symbols if symbol_to_id.get(s.upper())]
    if not ids:
        return {}
    url = "https://api.coingecko.com/api/v3/simple/price"
    params = {
        "ids": ','.join(ids),
        "vs_currencies": "usd",
    }
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        # Reverse‑lookup to original symbol
        result = {}
        for sym in symbols:
            cid = symbol_to_id.get(sym.upper())
            if cid and cid in data:
                result[sym.upper()] = float(data[cid]["usd"])
        return result
    except Exception as exc:
        logging.error("Price fetch failed: %s", exc)
        return {}

# ---------------------------------------------------------------------------
# Core logic – flip direction and recompute risk levels using the same
# parameters that the main engine uses (ATR‑based TP/SL, 1% equity risk).
# ---------------------------------------------------------------------------

def _flip_direction(direction: str) -> str:
    return "SHORT" if direction.upper() == "LONG" else "LONG"


def _recompute_levels(pick: Dict[str, Any]) -> Dict[str, Any]:
    """Return a new dict with the opposite direction and adjusted TP/SL.

    The original pick contains ``entry``, ``tp``, ``sl`` and ``atr``.  For the
    opposite position we keep the same entry price (the market price at the
    time of the original signal) but swap the TP/SL logic:

    * LONG  →  TP = entry + ATR * TP_MULT, SL = entry - ATR * SL_MULT
    * SHORT →  TP = entry - ATR * TP_MULT, SL = entry + ATR * SL_MULT

    The function also copies over the original metadata (symbol, size, etc.)
    and adds a ``source`` field so we can differentiate sandbox picks later.
    """
    new = pick.copy()
    new["direction"] = _flip_direction(pick["direction"])
    atr = pick.get("atr", 0)
    # The original engine uses config.TP_ATR_MULT / config.SL_ATR_MULT – we
    # re‑import those values to stay consistent.
    from crypto_signal_engine import config
    tp_mult = getattr(config, "TP_ATR_MULT", 1.5)
    sl_mult = getattr(config, "SL_ATR_MULT", 1.0)
    entry = pick["entry"]
    if new["direction"] == "LONG":
        new["tp"] = round(entry + atr * tp_mult, 6)
        new["sl"] = round(entry - atr * sl_mult, 6)
    else:
        new["tp"] = round(entry - atr * tp_mult, 6)
        new["sl"] = round(entry + atr * sl_mult, 6)
    new["opened_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    new["status"] = "ACTIVE"
    new["source"] = "opposite_day"
    # Preserve the original confidence for analysis – it is not used for
    # decision making in the sandbox.
    return new


def load_json(path: Path) -> List[Dict[str, Any]]:
    if not path.is_file():
        return []
    try:
        return json.loads(path.read_text())
    except Exception as exc:
        logging.error("Failed to read %s: %s", path, exc)
        return []


def save_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str))

# ---------------------------------------------------------------------------
# Public API – run the sandbox for a single day.
# ---------------------------------------------------------------------------

def run_opposite_day():
    """Generate opposite picks, update P&L and write stats.

    The function is idempotent – running it repeatedly will only add new
    opposite picks for any *new* active signals and will close any existing
    opposite picks that have reached TP/SL.
    """
    # 1️⃣ Load current active picks from the main engine.
    active = load_json(ACTIVE_PICKS_PATH)
    if not active:
        logging.info("No active picks – nothing to invert.")
        return

    # 2️⃣ Load (or initialise) the sandbox state.
    opposite = load_json(OPPOSITE_PICKS_PATH)
    # Index by ``symbol_direction`` for quick duplicate checks.
    existing_keys = {f"{p['symbol']}_{p['direction']}" for p in opposite}

    # 3️⃣ Create opposite entries for any new signal.
    new_opposites = []
    for pick in active:
        key = f"{pick['symbol']}_{_flip_direction(pick['direction'])}"
        if key in existing_keys:
            continue
        opp = _recompute_levels(pick)
        new_opposites.append(opp)
        existing_keys.add(key)

    if new_opposites:
        opposite.extend(new_opposites)
        logging.info("Added %d opposite picks.", len(new_opposites))

    # 4️⃣ Update P&L for all opposite picks.
    symbols = list({p['symbol'] for p in opposite})
    prices = fetch_current_prices(symbols)
    closed = []
    still_active = []

    for pick in opposite:
        sym = pick['symbol']
        cur_price = prices.get(sym.upper())
        if cur_price is None:
            still_active.append(pick)
            continue
        entry = pick['entry']
        tp = pick['tp']
        sl = pick['sl']
        is_short = pick['direction'].upper() == 'SHORT'
        if is_short:
            pnl_pct = round((entry - cur_price) / entry * 100, 2)
            tp_hit = cur_price <= tp
            sl_hit = cur_price >= sl
        else:
            pnl_pct = round((cur_price - entry) / entry * 100, 2)
            tp_hit = cur_price >= tp
            sl_hit = cur_price <= sl
        pick['current_price'] = cur_price
        pick['pnl_pct'] = pnl_pct
        pick['last_checked'] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        if tp_hit:
            pick['status'] = 'TP_HIT'
            pick['closed_at'] = pick['last_checked']
            pick['result'] = 'WIN'
            closed.append(pick)
        elif sl_hit:
            pick['status'] = 'SL_HIT'
            pick['closed_at'] = pick['last_checked']
            pick['result'] = 'LOSS'
            closed.append(pick)
        else:
            still_active.append(pick)

    # 5️⃣ Persist sandbox state.
    save_json(OPPOSITE_PICKS_PATH, still_active)
    # Keep a rolling window of the most recent 500 closed picks.
    historic = load_json(OPPOSITE_PICKS_PATH.with_name("opposite_day_closed.json"))
    historic.extend(closed)
    historic = sorted(historic, key=lambda x: x.get('closed_at', ''), reverse=True)[:500]
    save_json(OPPOSITE_PICKS_PATH.with_name("opposite_day_closed.json"), historic)

    # 6️⃣ Compute simple performance metrics.
    wins = sum(1 for p in historic if p.get('result') == 'WIN')
    losses = sum(1 for p in historic if p.get('result') == 'LOSS')
    total = wins + losses
    win_rate = (wins / total * 100) if total else 0.0
    # Profit factor = sum(win pnl) / sum(abs(loss pnl))
    win_pnl = sum(p.get('pnl_pct', 0) for p in historic if p.get('result') == 'WIN')
    loss_pnl = sum(abs(p.get('pnl_pct', 0)) for p in historic if p.get('result') == 'LOSS')
    profit_factor = (win_pnl / loss_pnl) if loss_pnl else float('inf')
    stats = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "active_opposite_picks": len(still_active),
        "closed_opposite_picks": len(historic),
        "win_rate_pct": round(win_rate, 2),
        "profit_factor": round(profit_factor, 3) if profit_factor != float('inf') else "inf",
        "wins": wins,
        "losses": losses,
    }
    save_json(OPPOSITE_STATS_PATH, stats)
    logging.info("Opposite Day stats updated – win rate %.2f%%, PF %.3f", win_rate, profit_factor)

# ---------------------------------------------------------------------------
# CLI entry point.
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run Opposite Day sandbox")
    parser.add_argument("--run", action="store_true", help="Execute the full pipeline")
    args = parser.parse_args()
    if args.run:
        logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
        run_opposite_day()
