import { defineConfig } from '@playwright/test';

const isRemoteVerify =
  process.env.VERIFY_REMOTE === '1' || process.env.VERIFY_REMOTE === 'true';

export default defineConfig({
  testDir: '.',
  testMatch: [
    /(?:^|\/)events-loading\.spec\.ts$/,
    /(?:^|\/)tests\/local_root_main_site\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-guest-9000\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-admin-login\.spec\.ts$/,
    /(?:^|\/)tests\/verify_remote_site\.spec\.ts$/,
    /(?:^|\/)tests\/debug_nav_menu\.spec\.ts$/,
    /(?:^|\/)tests\/no_js_errors\.spec\.ts$/,
    /(?:^|\/)tests\/nav_2xko_after_favcreators\.spec\.ts$/,
    /(?:^|\/)tests\/inspect_quick_nav_order\.spec\.ts$/,
    /(?:^|\/)tests\/promo_banner_alignment\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-db-notes-remote\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-guest-notes-local\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-remote-notes\.spec\.ts$/,
    /(?:^|\/)tests\/signin_button_visible\.spec\.ts$/,
    /(?:^|\/)tests\/signin_flow_debug\.spec\.ts$/,
    /(?:^|\/)tests\/signin_login_box_location\.spec\.ts$/,
    /(?:^|\/)tests\/my_events_save_persisted\.spec\.ts$/,
    /(?:^|\/)tests\/tooltip_overlap\.spec\.ts$/,
    /(?:^|\/)tests\/tooltip_overlap_puppeteer\.spec\.ts$/,
    /(?:^|\/)tests\/movieshows_overlap\.spec\.ts$/,
    /(?:^|\/)tests\/live-status-ninja-test\.spec\.ts$/,
    /(?:^|\/)tests\/creator_updates\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-updates-comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-updates-user-param\.spec\.ts$/,
    /(?:^|\/)tests\/thumbnail-proxy\.spec\.ts$/,
    /(?:^|\/)tests\/live-streams-realtime\.spec\.ts$/,
    /(?:^|\/)tests\/live-offline-removal\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-last-seen-api\.spec\.ts$/,
    /(?:^|\/)tests\/mental-health-resources\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins_phase2\.spec\.ts$/,
    /(?:^|\/)tests\/vr_creators_auth\.spec\.ts$/,
    /(?:^|\/)tests\/vr_area_guide\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins_set7\.spec\.ts$/,
    /(?:^|\/)tests\/vr_scene_enhancements\.spec\.ts$/,
    /(?:^|\/)tests\/vr_completeness\.spec\.ts$/,
    /(?:^|\/)tests\/vr_interaction\.spec\.ts$/,
    /(?:^|\/)tests\/vr_personalization\.spec\.ts$/,
    /(?:^|\/)tests\/vr_advanced_ux\.spec\.ts$/,
    /(?:^|\/)tests\/vr_comfort_intel\.spec\.ts$/,
    /(?:^|\/)tests\/vr_content_depth\.spec\.ts$/,
    /(?:^|\/)tests\/vr_polish\.spec\.ts$/,
    /(?:^|\/)tests\/vr_social_rich\.spec\.ts$/,
    /(?:^|\/)tests\/vr_intel_engage\.spec\.ts$/,
    /(?:^|\/)tests\/vr_full_comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/vr_full_site_test\.spec\.ts$/,
    /(?:^|\/)tests\/vr_cross_platform_comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/vr_mode_toggle_cross_platform\.spec\.ts$/,
    /(?:^|\/)tests\/vr_mode_toggle_focused\.spec\.ts$/,
    /(?:^|\/)tests\/full_page_test\.spec\.ts$/,
    /(?:^|\/)tests\/weather_page\.spec\.ts$/,
    /(?:^|\/)tests\/otherstuff_popup\.spec\.ts$/,
    /(?:^|\/)tests\/ant_rush_smoke\.spec\.ts$/,
    /(?:^|\/)tests\/fightgame_test\.spec\.ts$/,
    /(?:^|\/)tests\/fightgame_remote\.spec\.ts$/,
    /(?:^|\/)tests\/vr_cross_platform_full\.spec\.ts$/,
    /(?:^|\/)tests\/lofe_creator_updates\.spec\.ts$/,
    /(?:^|\/)tests\/verify_fc_updates_remote\.spec\.ts$/,
    /(?:^|\/)tests\/debug_layout\.spec\.ts$/,
    /(?:^|\/)tests\/fps-v5-zero-errors\.spec\.ts$/,
    /(?:^|\/)tests\/fps-v5\.spec\.ts$/,
    /(?:^|\/)tests\/fps-v5-complete\.spec\.ts$/,
    /(?:^|\/)tests\/fps-v5-debug\.spec\.ts$/,
    /(?:^|\/)tests\/full_site_js_errors\.spec\.ts$/,
  ],
  timeout: isRemoteVerify ? 90000 : 30000,
  retries: isRemoteVerify ? 1 : 0,
  webServer: isRemoteVerify
    ? undefined
    : {
        command: 'python tools/serve_local.py',
        url: 'http://localhost:5173/',
        reuseExistingServer: !process.env.CI,
        timeout: 30000,
      },
  use: {
    baseURL: isRemoteVerify
      ? process.env.VERIFY_REMOTE_URL || 'https://findtorontoevents.ca'
      : 'http://localhost:5173',
    headless: true,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    video: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        viewport: { width: 1920, height: 1080 },
      },
    },
    {
      name: 'Desktop Edge',
      use: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
        viewport: { width: 1920, height: 1080 },
      },
    },
    {
      name: 'Samsung Galaxy S21',
      use: {
        userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.0.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
        viewport: { width: 384, height: 854 },
        hasTouch: true,
      },
    },
    {
      name: 'Meta Quest 3',
      use: {
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64; Quest 3) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/31.0.0.0.0 SamsungBrowser/4.0 Chrome/120.0.0.0 VR Safari/537.36',
        viewport: { width: 1832, height: 1920 },
      },
    },
  ],
});
