import { defineConfig } from '@playwright/test';

const isRemoteVerify =
  process.env.VERIFY_REMOTE === '1' || process.env.VERIFY_REMOTE === 'true';

export default defineConfig({
  testDir: '.',
  testIgnore: [
    '**/.kilo/**',
    '**/.pr41-review/**',
    '**/.worktrees/**',
    '.worktrees/**',
    '**/.claude/**',
    '.claude/**',
    '**/node_modules/**',
    '**/.git/**',
    '**/.pytest_cache/**',
  ],
  testMatch: [
    /(?:^|\/)events-loading\.spec\.ts$/,
    /(?:^|\/)tests\/local_root_main_site\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-guest-9000\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-admin-login\.spec\.ts$/,
    /(?:^|\/)tests\/verify_remote_site\.spec\.ts$/,
    /(?:^|\/)tests\/debug_nav_menu\.spec\.ts$/,
    /(?:^|\/)tests\/no_js_errors\.spec\.ts$/,
    /(?:^|\/)tests\/sports_api_dashboard\.spec\.ts$/,
    /(?:^|\/)tests\/sports_betting_js_errors\.spec\.js$/,
    /(?:^|\/)tests\/nav_2xko_after_favcreators\.spec\.ts$/,
    /(?:^|\/)tests\/inspect_quick_nav_order\.spec\.ts$/,
    /(?:^|\/)tests\/promo_banner_alignment\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-db-notes-remote\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-guest-notes-local\.spec\.ts$/,
    /(?:^|\/)tests\/favcreators-remote-notes\.spec\.ts$/,
    /(?:^|\/)tests\/signin_button_visible\.spec\.ts$/,
    /(?:^|\/)tests\/signin_flow_debug\.spec\.ts$/,
    /(?:^|\/)tests\/signin_login_box_location\.spec\.ts$/,
    /(?:^|\/)tests\/my_events_save_persisted\.spec\.ts$/,
    /(?:^|\/)tests\/tooltip_overlap\.spec\.ts$/,
    /(?:^|\/)tests\/tooltip_overlap_puppeteer\.spec\.ts$/,
    /(?:^|\/)tests\/movieshows_overlap\.spec\.ts$/,
    /(?:^|\/)tests\/live-status-ninja-test\.spec\.ts$/,
    /(?:^|\/)tests\/creator_updates\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-updates-comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-updates-user-param\.spec\.ts$/,
    /(?:^|\/)tests\/thumbnail-proxy\.spec\.ts$/,
    /(?:^|\/)tests\/live-streams-realtime\.spec\.ts$/,
    /(?:^|\/)tests\/live-offline-removal\.spec\.ts$/,
    /(?:^|\/)tests\/streamer-last-seen-api\.spec\.ts$/,
    /(?:^|\/)tests\/mental-health-resources\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins_phase2\.spec\.ts$/,
    /(?:^|\/)tests\/vr_creators_auth\.spec\.ts$/,
    /(?:^|\/)tests\/vr_area_guide\.spec\.ts$/,
    /(?:^|\/)tests\/vr_quick_wins_set7\.spec\.ts$/,
    /(?:^|\/)tests\/vr_scene_enhancements\.spec\.ts$/,
    /(?:^|\/)tests\/vr_completeness\.spec\.ts$/,
    /(?:^|\/)tests\/vr_interaction\.spec\.ts$/,
    /(?:^|\/)tests\/vr_personalization\.spec\.ts$/,
    /(?:^|\/)tests\/vr_advanced_ux\.spec\.ts$/,
    /(?:^|\/)tests\/vr_comfort_intel\.spec\.ts$/,
    /(?:^|\/)tests\/vr_content_depth\.spec\.ts$/,
    /(?:^|\/)tests\/vr_polish\.spec\.ts$/,
    /(?:^|\/)tests\/vr_social_rich\.spec\.ts$/,
    /(?:^|\/)tests\/vr_intel_engage\.spec\.ts$/,
    /(?:^|\/)tests\/vr_full_comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/vr_full_site_test\.spec\.ts$/,
    /(?:^|\/)tests\/vr_cross_platform_comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/vr_mode_toggle_cross_platform\.spec\.ts$/,
    /(?:^|\/)tests\/vr_mode_toggle_focused\.spec\.ts$/,
    /(?:^|\/)tests\/full_page_test\.spec\.ts$/,
    /(?:^|\/)tests\/weather_page\.spec\.ts$/,
    /(?:^|\/)tests\/otherstuff_popup\.spec\.ts$/,
    /(?:^|\/)tests\/vr_cross_platform_full\.spec\.ts$/,
    /(?:^|\/)tests\/ant_rush_smoke\.spec\.ts$/,
    /(?:^|\/)tests\/dashboard_data_loading\.spec\.ts$/,
    /(?:^|\/)tests\/unified_dashboard_console_network\.spec\.ts$/,
    /(?:^|\/)tests\/unified_dashboard_verify\.spec\.ts$/,
    /(?:^|\/)tests\/ms3_browse_play\.spec\.ts$/,
    /(?:^|\/)tests\/audit_wording_audit\.spec\.ts$/,
    /(?:^|\/)tests\/audit_dashboard_quality\.spec\.ts$/,
    /(?:^|\/)tests\/audit_dashboard_mobile\.spec\.ts$/,
    /(?:^|\/)tests\/alpha_audit_validation\.spec\.ts$/,
    /(?:^|\/)tests\/test_dashboards\.spec\.ts$/,
    /(?:^|\/)tests\/test_agreement_matrix\.spec\.ts$/,
    /(?:^|\/)tests\/test_inactive_systems_fix\.spec\.ts$/,
    /(?:^|\/)tests\/audit_dashboard_deep_review\.spec\.ts$/,
    /(?:^|\/)tests\/verify_4ai_battle\.spec\.ts$/,
    /(?:^|\/)tests\/verify_5ai_battle_round2\.spec\.ts$/,
    /(?:^|\/)tests\/audit_export_comprehensive\.spec\.ts$/,
    /(?:^|\/)tests\/audit_visual_validation\.spec\.js$/,
    /(?:^|\/)tests\/audit_copytrader_inspection\.spec\.ts$/,
    /(?:^|\/)tests\/supplemental_api_portfolio\.spec\.ts$/,
    /(?:^|\/)tests\/multi_asset_copytrader\.spec\.ts$/,
    /(?:^|\/)tests\/audit_live_full_inspection\.spec\.ts$/,
    /(?:^|\/)tests\/audit_post_deploy_validation\.spec\.ts$/,
    /(?:^|\/)tests\/audit_smart_picks_inspection\.spec\.ts$/,
    /(?:^|\/)tests\/audit_metric_matrix_validation\.spec\.ts$/,
    /(?:^|\/)tests\/audit_live_quant_data\.spec\.ts$/,
    /(?:^|\/)tests\/hyrotrader_tracker\.spec\.ts$/,
    /(?:^|\/)tests\/hyrotrader_live_freshness\.spec\.ts$/,
    /(?:^|\/)tests\/audit_hc_conviction_e2e\.spec\.ts$/,
    /(?:^|\/)tests\/audit_verified_edge_active_picks\.spec\.ts$/,
    /(?:^|\/)tests\/audit_remote_tabs_no_errors\.spec\.ts$/,
    /(?:^|\/)tests\/audit_agv_col_tip_viewport\.spec\.ts$/,
    /(?:^|\/)tests\/audit_prediction_markets_crossover\.spec\.ts$/,
    /(?:^|\/)tests\/audit_remote_warn_and_desc\.spec\.ts$/,
    /(?:^|\/)tests\/events_tbd_filter\.spec\.ts$/,
    /(?:^|\/)tests\/events_filter_bugs\.spec\.ts$/,
    /(?:^|\/)tests\/events_month_filters\.spec\.ts$/,
    /(?:^|\/)tests\/non_crypto_picks_postfix\.spec\.ts$/,
    /(?:^|\/)tests\/audit_page\.spec\.ts$/,
    /(?:^|\/)tests\/live_events_smoke\.spec\.ts$/,
    /(?:^|\/)tests\/playwright\/test_event_date_filters\.spec\.ts$/,
  ],
  timeout: isRemoteVerify ? 90000 : 30000,
  retries: isRemoteVerify ? 1 : 0,
  webServer: isRemoteVerify
    ? undefined
    : {
        command: 'python tools/serve_local.py',
        url: 'http://localhost:5173/',
        reuseExistingServer: !process.env.CI,
        timeout: 30000,
      },
  use: {
    baseURL: isRemoteVerify
      ? process.env.VERIFY_REMOTE_URL || 'https://findtorontoevents.ca'
      : 'http://localhost:5173',
    headless: true,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    video: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        viewport: { width: 1920, height: 1080 },
      },
    },
    {
      name: 'Desktop Edge',
      use: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
        viewport: { width: 1920, height: 1080 },
      },
    },
    {
      name: 'Samsung Galaxy S21',
      use: {
        userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.0.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
        viewport: { width: 384, height: 854 },
        hasTouch: true,
      },
    },
    {
      // Samsung Galaxy S25 Ultra — released Jan 2025. CSS viewport ~412×915
      // (3120×1440 physical @ DPR ~3.5). UA reflects Android 15 + SM-S938U.
      // Used to verify event-filter chips remain tappable and the chip row
      // doesn't overflow on a current flagship Samsung phone.
      name: 'Samsung Galaxy S25 Ultra',
      use: {
        userAgent: 'Mozilla/5.0 (Linux; Android 15; SM-S938U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36',
        viewport: { width: 412, height: 915 },
        deviceScaleFactor: 3.5,
        hasTouch: true,
        isMobile: true,
      },
    },
    {
      name: 'Meta Quest 3',
      use: {
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64; Quest 3) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/31.0.0.0.0 SamsungBrowser/4.0 Chrome/120.0.0.0 VR Safari/537.36',
        viewport: { width: 1832, height: 1920 },
      },
    },
  ],
});
