import json
import glob

files = glob.glob('**/*closed*.json', recursive=True)
files.append('audit_trail/data/closed_picks.json') # Add general files just in case
files = list(set(files))

print(f"Checking {len(files)} files...")

for f in files:
    try:
        with open(f, 'r') as fp:
            data = json.load(fp)
            
        was_list = isinstance(data, list)
        items = data if was_list else data.get('picks', data.get('signals', []))
        if not isinstance(items, list): continue
        
        valid = []
        removed = 0
        for p in items:
            sym = str(p.get('symbol', '')).upper()
            strat = str(p.get('strategy', '')).upper()
            src = str(p.get('source_system', p.get('source', ''))).lower()
            asset = str(p.get('asset_class', '')).upper()
            
            remove = False
            # Rule 1: EURUSDT treated as forex in rapid_fire
            if sym == "EURUSDT" and 'rapid' in src: remove = True
            
            # Rule 2: signal_validation testing forex
            if src in ['signal_validation', 'kimi_signal_tracking', 'forex-scanner-live']:
                if asset in ['FOREX', 'FX', 'EQUITY', 'STOCKS', 'COMMODITY', 'ETF']: remove = True
                
            # Rule 3: forex tools generated by ML tests
            if 'kimi' in src and asset == 'FX': remove = True
            if 'momentumema' in strat.lower() and sym == 'GBP-USD': remove = True
            
            if remove:
                removed += 1
            else:
                valid.append(p)
            
        if removed > 0:
            print(f"Removed {removed} testing/sandbox picks from {f}")
            if was_list:
                with open(f, 'w') as out:
                    json.dump(valid, out, indent=2)
            else:
                if 'picks' in data: data['picks'] = valid
                if 'signals' in data: data['signals'] = valid
                with open(f, 'w') as out:
                    json.dump(data, out, indent=2)
    except Exception as e:
        pass
