"""Contract test — winner_hunt_replay_payload.json isolation discipline.

Background
----------
``audit_dashboard/data/winner_hunt_replay_payload.json`` is an ALERT payload
generated monthly by ``tools/build_winner_hunt_replay.py`` (driven by the
``.github/workflows/winner-hunt-replay.yml`` cron at 08:00 UTC on the 1st of
each month). It currently carries::

    "_schema_note": "Generated by tools/build_winner_hunt_replay.py; read-only
                     replay of the STA-09 hunt. NEVER a sizing input."
    "winner_hunt_replay_only": True

The payload encodes alert data (PROMOTE THE LEAD / NEW_CELL_FOUND / ::notice::
— never a sizing signal). The schema contract reads "NEVER a sizing input"
with the ``winner_hunt_replay_only: True`` gate as the machine-readable proxy
(specifically added to be the contract gate-flag for this test — the older
generic ``read_only`` name was too ambiguous and risked false negatives).

That contract is currently a docstring — Python has no way to enforce it. This
test enforces it pre-merge so a future ``tools/consume_picks.py`` (or any
*.py under ``tools/``, ``audit_trail/``, ``alpha_engine/``) that silently
re-ingests this alert payload as a sizing source FAILS the test instead of
shipping to production.

The contract — two acceptable signals in a consumer candidate:

1. The file references the gate flag ``winner_hunt_replay_only`` (the
   "this is alert data, not sizing" proxy), OR
2. The file carries an explicit ``# allowed: winner-hunt-replay consumer``
   comment on its own line (a human-acknowledged override — used for the
   writer, the verdict-doc renderer, manual debug scripts, etc.)

A file that reads ``winner_hunt_replay_payload.json`` and carries neither
signal is flagged as an **unguarded consumer** and the test fails.

This test mirrors ``tests/test_no_sizing_consumer.py`` (which guards
``operator_review_today.json``) with a different gate-flag name + allow-marker
because: the operator-review sidecar is sizing-adjacent visibility (decides
what the operator sees for human review); the winner-hunt-replay payload is
alert data (announces cell promotions or new cell hits). Different domain —
different names; the discipline (the test mechanics: scan + flag + marker
pattern + cron-mode fail-closed) is identical.

Cron-mode fail-closed (mirror of the operator-review test)
---------------------------------------------------------
When ``WINNER_HUNT_CRON_MODE=1`` is set in the env, a missing payload
AFTER the build step ran becomes a ``pytest.fail()`` (not a
``pytest.skip()``). Local pytest runs (env unset) keep the developer-
friendly skip path. The cron-mode env var is set ONLY at the contract-test
step's env block when/if a future integration wires this test into the
winner-hunt-replay cron (it doesn't today — the operator-review cron has
it, the winner-hunt-replay cron doesn't yet).

See:
- ``audit_dashboard/data/winner_hunt_replay_payload.json`` for the payload +
  its ``_schema_note`` / ``winner_hunt_replay_only`` fields
- ``tools/build_winner_hunt_replay.py`` for the writer
- ``updates/2026-06-22-winner-hunt-replay-cron.md`` §"References" for the spec
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import pytest

# --------------------------------------------------------------------------- #
# Configuration — keep this list narrow; only writers and self may be exempt. #
# --------------------------------------------------------------------------- #

REPO = Path(__file__).resolve().parent.parent

# Scan roots: any *.py here that reads the payload is a consumer candidate.
SCAN_ROOTS = [
    REPO / "tools",
    REPO / "audit_trail",
    REPO / "alpha_engine",
]

# Files exempt from the scan. Two legitimate categories today:
#   1. The writer (build script — it WRITES the payload, never reads it back
#      as a sizing source, but the filename literal appears in source as
#      PRIOR_PAYLOAD_PATH/OUT_PAYLOAD_PATH).
#   2. The test file itself (it necessarily mentions both the filename and
#      the gate-flag in source).
EXEMPT_BASENAMES = {
    "build_winner_hunt_replay.py",             # writer — produces the payload
    "test_no_winner_hunt_replay_consumer.py",  # self — this file
}

# Cache & generated artifacts we never want to scan.
EXEMPT_SUFFIX_PARTS = ("__pycache__", ".pyc")

# Contract signals.
SIDECAR_FILENAME = "winner_hunt_replay_payload.json"
GUARD_FLAG = "winner_hunt_replay_only"
# Accept the marker as a line-leading OR inline trailing comment. Anchored
# on the literal `#` and word-boundary `consumer\b` so typos fail loudly.
ALLOW_COMMENT_RE = re.compile(
    r"#\s*allowed:\s*winner-hunt-replay\s+consumer\b"
)
SIDECAR_CONTRACT_KEYS_REQUIRED = ("_schema_note", "winner_hunt_replay_only")

# Cron-mode gate: when/if the workflow's "Run contract tests" step sets
# WINNER_HUNT_CRON_MODE=1 in its env block, a missing payload AFTER the
# build step ran is a HARD regression. The inline cron branch in
# test_sidecar_payload_carries_required_contract_keys converts the
# developer-friendly pytest.skip() into a hard pytest.fail() so the
# workflow contract step stops before the commit step can run.
# Local pytest runs (env unset) keep the skip-friendly default so a
# developer without the build can still run this contract test.
#
# COVERAGE LIMITATION: this constant + the inline pytest.fail() ONLY
# catches the one known skip (missing payload). If a future maintainer
# adds a SECOND pytest.skip() (e.g. @pytest.mark.skip(reason="WIP")) to
# this file, it will silently pass through. This file is a contract test,
# not a feature test bed — any future skip here MUST be coordinated with
# the contract owner OR replaced with explicit pytest.fail() in cron mode.
CRON_MODE = os.environ.get("WINNER_HUNT_CRON_MODE", "") == "1"


# --------------------------------------------------------------------------- #
# Detection helpers — substring/line-based; deliberately NOT AST, because the  #
# contract is about human-readable intent (the gate-flag literal is the signal).#
# --------------------------------------------------------------------------- #

def _consumes_sidecar(content: str) -> bool:
    """True if the file opens AND reads winner_hunt_replay_payload.json.

    Both the filename substring AND a loader-intent pattern must appear in
    the same file. Pure docstring-mentions (e.g., explaining the payload's
    role in prose) do NOT qualify — this rejects false positives where the
    substring appears only in a docstring/comment with no actual read.
    """
    if SIDECAR_FILENAME not in content:
        return False
    intent_patterns = (
        "open(", "read_text", "read_bytes",  # pathlib / Pathlib-style read
        "json.load", "json.loads",             # most-common payload consumer
        "yaml.safe_load", "yaml.load",         # alternate config loader
        "tomllib.load",                         # stdlib py3.11+
        ".load(", ".loads(",                    # generic pickle/csv/etc.
    )
    return any(pat in content for pat in intent_patterns)


def _carries_guard(content: str) -> bool:
    """True if the file references the winner_hunt_replay_only gate flag
    anywhere in source — as a name, attribute access, or string literal."""
    return GUARD_FLAG in content


def _carries_allow_marker(content: str) -> bool:
    """True if the file carries an explicit `# allowed: winner-hunt-replay
    consumer` marker — line-leading OR trailing inline-comment.

    The pattern is anchored on the literal `#`, on a word boundary after
    `consumer`, and tolerates inline trailing comments (e.g., after code).
    Strict-enough to reject typos; loose-enough to accept real usage.
    """
    return bool(ALLOW_COMMENT_RE.search(content))


def _is_exempt(path: Path) -> bool:
    """Exempt test self + writer + cache artifacts."""
    if path.name in EXEMPT_BASENAMES:
        return True
    if any(part in EXEMPT_SUFFIX_PARTS for part in path.parts):
        return True
    return False


def _scan_files():
    """Yield every scanned-eligible *.py under SCAN_ROOTS."""
    for root in SCAN_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*.py"):
            if not path.is_file():
                continue
            if _is_exempt(path):
                continue
            yield path


# --------------------------------------------------------------------------- #
# Pytest test functions.                                                      #
# --------------------------------------------------------------------------- #

def test_no_unguarded_consumer_in_scan_roots():
    """ANY *.py under tools/ + audit_trail/ + alpha_engine/ that opens
    winner_hunt_replay_payload.json MUST also reference the
    winner_hunt_replay_only gate flag OR carry the explicit
    ``# allowed: winner-hunt-replay consumer`` marker on its own line.
    Otherwise it is an UNGUARDED consumer and the test fails — surfacing
    the violation in the merge queue."""
    violations: list[str] = []

    for path in _scan_files():
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            # Non-text files, symlinks, unreadable — skip.
            continue

        if not _consumes_sidecar(content):
            continue

        if _carries_allow_marker(content):
            continue

        if _carries_guard(content):
            continue

        violations.append(path.relative_to(REPO).as_posix())

    assert not violations, (
        "Unguarded consumers of winner_hunt_replay_payload.json detected. "
        "Every *.py that opens the sidecar under {tools/, audit_trail/, "
        "alpha_engine/} must EITHER reference the `winner_hunt_replay_only` "
        "gate-flag string (anywhere in the file) OR carry a line reading "
        "exactly `# allowed: winner-hunt-replay consumer` (human-acknowledged "
        "override). Either add the guard reference, or add the override "
        "comment, or — if the read is no longer needed — remove the read. "
        f"Violations: {violations}"
    )


def test_sidecar_payload_carries_required_contract_keys():
    """Mirror check on the payload itself: must carry `_schema_note` AND
    `winner_hunt_replay_only` fields — without these, the contract is
    not enforceable on consumers."""
    sidecar_path = REPO / "audit_dashboard" / "data" / SIDECAR_FILENAME

    if not sidecar_path.exists():
        # Cron-mode (env WINNER_HUNT_CRON_MODE=1, set by the workflow's
        # "Run contract tests" step when wired): the build step just ran,
        # so the payload MUST exist on disk. A missing payload in cron mode
        # is a HARD regression — fail-loud so the workflow stops BEFORE
        # any commit step can push the broken baseline.
        if CRON_MODE:
            pytest.fail(
                f"HARD REGRESSION: {sidecar_path.relative_to(REPO).as_posix()} "
                "is missing AFTER the winner-hunt-replay build step ran "
                "(WINNER_HUNT_CRON_MODE=1). Possible causes: "
                "build script (tools/build_winner_hunt_replay.py) "
                "failed silently to write the payload, or the "
                "contract + commit step sequence is wrong, "
                "or the contract test is running out of order. "
                "Investigate the build before re-running the cron. "
                "(Locally: unset WINNER_HUNT_CRON_MODE to run in "
                "developer-friendly skip mode.)"
            )
        # Local non-cron mode: developer-friendly skip — the build hasn't
        # run yet; the cron lands the payload on the 1st of each month at
        # 08:00 UTC.
        pytest.skip(
            f"{sidecar_path.relative_to(REPO).as_posix()} not yet produced; "
            "the winner-hunt-replay cron at 08:00 UTC on the 1st of each "
            "month will land it. (unset WINNER_HUNT_CRON_MODE to suppress "
            "the cron-mode fail-closed path.)"
        )

    payload = json.loads(sidecar_path.read_text(encoding="utf-8"))

    missing = [k for k in SIDECAR_CONTRACT_KEYS_REQUIRED if k not in payload]
    assert not missing, (
        f"{sidecar_path.relative_to(REPO).as_posix()} is missing required "
        f"contract keys: {missing}. Both `_schema_note` (human-readable "
        "contract) and `winner_hunt_replay_only` (machine-readable gate "
        "flag) are required — the test_no_unguarded_consumer_in_scan_roots "
        "test above would have nothing to verify against."
    )

    # The machine-readable gate flag must be a strict boolean True. If a
    # refactor accidentally stringifies it, consumers checking truthiness
    # alone are OK but operators reading the file by eye are misled.
    assert payload["winner_hunt_replay_only"] is True, (
        "winner_hunt_replay_only must be a strict boolean True; got "
        f"{payload['winner_hunt_replay_only']!r} instead. The fail-closed "
        "contract depends on a strict type match (not just truthiness)."
    )


def test_exempt_set_includes_writer_and_self():
    """Sanity guard: the EXEMPT_BASENAMES table must include the writer
    (build_winner_hunt_replay.py) and the test file itself — otherwise
    the writer's PRIOR_PAYLOAD_PATH literal would false-positive the main
    test, or this test would flag itself."""
    today = REPO / "tests" / "test_no_winner_hunt_replay_consumer.py"
    writer = REPO / "tools" / "build_winner_hunt_replay.py"

    # THIS test file's own name must be in the exempt set — otherwise self-flag.
    assert today.name in EXEMPT_BASENAMES, (
        "EXEMPT_BASENAMES must contain the test file's own name to avoid a "
        "self-flagged violation on every run."
    )

    # The writer is in the scan root and contains a path literal to the
    # payload (PRIOR_PAYLOAD_PATH/OUT_PAYLOAD_PATH); it must be exempt
    # explicitly. If the writer is renamed in the future, update this
    # assertion + EXEMPT_BASENAMES together.
    assert writer.name in EXEMPT_BASENAMES, (
        "EXEMPT_BASENAMES must contain "
        f"{writer.name!r} (the winner-hunt-replay payload's build script). "
        "The writer opens PRIOR_PAYLOAD_PATH literal to set OUT_PAYLOAD_PATH; "
        "scanning it without exemption would false-positive on every run. "
        "Either add the writer to EXEMPT_BASENAMES, or — if the writer is "
        "being retired — delete this assertion."
    )
