<?php
/**
 * DayTraders Miracle_CURSOR — Dashboard Stats API (Claude-generated)
 * Strategy leaderboard, portfolio performance, and system stats.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Actions:
 *   stats       -- overall system statistics
 *   leaderboard -- strategy performance ranking
 *   portfolio   -- portfolio-level P&L tracking
 *   history     -- daily pick history with outcomes
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$action = isset($_GET['action']) ? trim($_GET['action']) : 'stats';
$response = array('ok' => true, 'action' => $action);

if ($action === 'stats') {
    $stats = array();

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_watchlist3 WHERE active=1");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['watchlist_tickers'] = (int)$row['c'];

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_strategies3 WHERE enabled=1");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['active_strategies'] = (int)$row['c'];

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_picks3");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['total_picks'] = (int)$row['c'];

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_picks3 WHERE outcome='won'");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['total_wins'] = (int)$row['c'];

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_picks3 WHERE outcome='lost'");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['total_losses'] = (int)$row['c'];

    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_picks3 WHERE outcome='pending'");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['pending_picks'] = (int)$row['c'];

    $resolved = $stats['total_wins'] + $stats['total_losses'];
    $stats['overall_win_rate'] = ($resolved > 0) ? round($stats['total_wins'] / $resolved * 100, 2) : 0;

    // Average score of picks
    $res = $conn->query("SELECT AVG(score) as avg_score FROM miracle_picks3");
    $row = ($res) ? $res->fetch_assoc() : array('avg_score' => 0);
    $stats['avg_pick_score'] = round((float)$row['avg_score'], 1);

    // CDR vs non-CDR breakdown
    $res = $conn->query("SELECT is_cdr, COUNT(*) as cnt FROM miracle_picks3 GROUP BY is_cdr");
    $cdr_breakdown = array('cdr' => 0, 'non_cdr' => 0);
    if ($res) {
        while ($row = $res->fetch_assoc()) {
            if ($row['is_cdr'] == 1) $cdr_breakdown['cdr'] = (int)$row['cnt'];
            else $cdr_breakdown['non_cdr'] = (int)$row['cnt'];
        }
    }
    $stats['cdr_breakdown'] = $cdr_breakdown;

    // Date range
    $res = $conn->query("SELECT MIN(scan_date) as mn, MAX(scan_date) as mx FROM miracle_picks3");
    if ($res) {
        $row = $res->fetch_assoc();
        $stats['date_range'] = array('earliest' => $row['mn'], 'latest' => $row['mx']);
    }

    // Today's picks count
    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_picks3 WHERE scan_date=CURDATE()");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['today_picks'] = (int)$row['c'];

    // Learning adjustments count
    $res = $conn->query("SELECT COUNT(*) as c FROM miracle_learning3");
    $row = ($res) ? $res->fetch_assoc() : array('c' => 0);
    $stats['learning_adjustments'] = (int)$row['c'];

    $response['stats'] = $stats;

} elseif ($action === 'leaderboard') {
    $strategies = array();
    $res = $conn->query("SELECT
        strategy_name,
        COUNT(*) as total_picks,
        SUM(CASE WHEN outcome='won' THEN 1 ELSE 0 END) as wins,
        SUM(CASE WHEN outcome='lost' THEN 1 ELSE 0 END) as losses,
        SUM(CASE WHEN outcome='pending' THEN 1 ELSE 0 END) as pending_count,
        AVG(score) as avg_score,
        AVG(CASE WHEN outcome IN ('won','lost') THEN outcome_pct ELSE NULL END) as avg_outcome_pct,
        AVG(CASE WHEN outcome='won' THEN outcome_pct ELSE NULL END) as avg_win_pct,
        AVG(CASE WHEN outcome='lost' THEN outcome_pct ELSE NULL END) as avg_loss_pct,
        SUM(CASE WHEN outcome IN ('won','lost') THEN net_profit_if_tp ELSE 0 END) as total_pnl,
        AVG(risk_reward_ratio) as avg_rr,
        SUM(CASE WHEN is_cdr=1 THEN 1 ELSE 0 END) as cdr_picks
        FROM miracle_picks3
        GROUP BY strategy_name
        ORDER BY wins DESC");

    if ($res) {
        $rank = 0;
        while ($row = $res->fetch_assoc()) {
            $rank++;
            $resolved = (int)$row['wins'] + (int)$row['losses'];
            $row['win_rate'] = ($resolved > 0) ? round((int)$row['wins'] / $resolved * 100, 2) : 0;
            $row['avg_score'] = round((float)$row['avg_score'], 1);
            $row['avg_outcome_pct'] = round((float)$row['avg_outcome_pct'], 4);
            $row['avg_win_pct'] = round((float)$row['avg_win_pct'], 4);
            $row['avg_loss_pct'] = round((float)$row['avg_loss_pct'], 4);
            $row['total_pnl'] = round((float)$row['total_pnl'], 2);
            $row['avg_rr'] = round((float)$row['avg_rr'], 2);

            // Composite score: win_rate * 0.4 + avg_score * 0.3 + avg_rr * 10 * 0.3
            $composite = $row['win_rate'] * 0.4 + $row['avg_score'] * 0.3 + $row['avg_rr'] * 10 * 0.3;
            $row['composite_score'] = round($composite, 2);
            $row['rank'] = $rank;
            $strategies[] = $row;
        }
    }

    // Re-sort by composite score
    $comp_arr = array();
    for ($i = 0; $i < count($strategies); $i++) $comp_arr[$i] = $strategies[$i]['composite_score'];
    arsort($comp_arr);
    $sorted = array(); $rank = 0;
    foreach ($comp_arr as $idx => $val) { $rank++; $strategies[$idx]['rank'] = $rank; $sorted[] = $strategies[$idx]; }

    $response['leaderboard'] = $sorted;
    $response['ranking_method'] = 'composite = WinRate*0.4 + AvgScore*0.3 + RiskReward*3';

} elseif ($action === 'portfolio') {
    $portfolios = array();
    $res = $conn->query("SELECT * FROM miracle_portfolios3 ORDER BY id");
    if ($res) {
        while ($p = $res->fetch_assoc()) {
            // Get picks matching this portfolio's strategy filter
            $filter = trim($p['strategy_filter']);
            $strat_where = '';
            if ($filter !== '') {
                $parts = explode(',', $filter);
                $conds = array();
                foreach ($parts as $pt) {
                    $safe = $conn->real_escape_string(trim($pt));
                    $conds[] = "strategy_name LIKE '%$safe%'";
                }
                $strat_where = ' AND (' . implode(' OR ', $conds) . ')';
            }
            if ($p['prefer_cdr'] == 1) $strat_where .= ' AND is_cdr=1';

            $pick_res = $conn->query("SELECT COUNT(*) as total,
                SUM(CASE WHEN outcome='won' THEN 1 ELSE 0 END) as wins,
                SUM(CASE WHEN outcome='lost' THEN 1 ELSE 0 END) as losses,
                AVG(outcome_pct) as avg_pct
                FROM miracle_picks3 WHERE 1=1 $strat_where");
            $pick_stats = ($pick_res) ? $pick_res->fetch_assoc() : array('total' => 0, 'wins' => 0, 'losses' => 0, 'avg_pct' => 0);

            $p['pick_stats'] = $pick_stats;
            $portfolios[] = $p;
        }
    }
    $response['portfolios'] = $portfolios;

} elseif ($action === 'history') {
    $days = isset($_GET['days']) ? (int)$_GET['days'] : 30;
    if ($days < 1) $days = 30;
    if ($days > 365) $days = 365;

    $history = array();
    $res = $conn->query("SELECT scan_date,
        COUNT(*) as total_picks,
        SUM(CASE WHEN outcome='won' THEN 1 ELSE 0 END) as wins,
        SUM(CASE WHEN outcome='lost' THEN 1 ELSE 0 END) as losses,
        SUM(CASE WHEN outcome='pending' THEN 1 ELSE 0 END) as pending_count,
        AVG(score) as avg_score,
        AVG(CASE WHEN outcome IN ('won','lost') THEN outcome_pct ELSE NULL END) as avg_pct
        FROM miracle_picks3
        WHERE scan_date >= DATE_SUB(CURDATE(), INTERVAL $days DAY)
        GROUP BY scan_date
        ORDER BY scan_date DESC");
    if ($res) {
        while ($row = $res->fetch_assoc()) {
            $row['avg_score'] = round((float)$row['avg_score'], 1);
            $row['avg_pct'] = round((float)$row['avg_pct'], 4);
            $resolved = (int)$row['wins'] + (int)$row['losses'];
            $row['win_rate'] = ($resolved > 0) ? round((int)$row['wins'] / $resolved * 100, 2) : 0;
            $history[] = $row;
        }
    }
    $response['history'] = $history;
    $response['days'] = $days;

} else {
    $response['ok'] = false;
    $response['error'] = 'Unknown action. Use: stats, leaderboard, portfolio, history';
}

echo json_encode($response);
$conn->close();
?>
