<?php
/**
 * Database configuration for DayTraders Miracle_CURSOR (Claude-generated)
 * Uses same database as findstocks, with miracle3_ prefixed tables.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 */
error_reporting(0);
ini_set('display_errors', '0');

$servername = 'mysql.50webs.com';
$username   = 'ejaguiar1_stocks';
$password   = 'stocks';
$dbname     = 'ejaguiar1_stocks';
?>
