<?php
/**
 * DayTraders Miracle_CURSOR — Self-Adjusting Learning Algorithm (Claude-generated)
 * Analyzes historical pick outcomes per strategy, identifies what works/fails,
 * and automatically adjusts strategy parameters (TP%, SL%, min_score) to improve.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Actions:
 *   analyze       -- Full analysis of all strategies (read-only report)
 *   adjust        -- Analyze + apply recommended parameter adjustments
 *   permutation   -- Exhaustive TP/SL grid search per strategy
 *   performance   -- Calculate & store strategy performance records
 *
 * The learning loop:
 *   1. Collect all resolved picks (won/lost) per strategy
 *   2. Calculate actual win rate, avg win %, avg loss %, profit factor
 *   3. Run TP/SL grid search to find params that would have performed best
 *   4. Compare current defaults vs optimal params
 *   5. Gradually shift defaults toward optimal (max 20% per adjustment cycle)
 *   6. Log every adjustment for audit trail
 *   7. Store performance snapshot for trend tracking
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$action = isset($_GET['action']) ? trim($_GET['action']) : 'analyze';
$response = array('ok' => true, 'action' => $action);

// ═══════════════════════════════════════════════
// MINI-BACKTEST: Simulate TP/SL against historical outcomes
// ═══════════════════════════════════════════════
function miracle_mini_backtest($conn, $strategy_name, $tp_pct, $sl_pct) {
    $safe = $conn->real_escape_string($strategy_name);
    $res = $conn->query("SELECT entry_price, outcome_price, outcome_pct, outcome FROM miracle_picks3
        WHERE strategy_name='$safe' AND outcome IN ('won','lost') AND entry_price > 0");

    if (!$res || $res->num_rows === 0) {
        return array('trades' => 0, 'wins' => 0, 'losses' => 0, 'win_rate' => 0, 'avg_return' => 0, 'total_return' => 0, 'profit_factor' => 0);
    }

    $trades = 0; $wins = 0; $total_gain = 0; $total_loss = 0; $total_return = 0;

    while ($pick = $res->fetch_assoc()) {
        $entry = (float)$pick['entry_price'];
        $actual_pct = (float)$pick['outcome_pct'];
        if ($entry <= 0) continue;

        $trades++;

        // Simulate: would this pick have hit the new TP or SL first?
        // Since we don't have intraday data, use the actual outcome_pct as proxy
        // If actual_pct >= tp_pct: counted as win at tp_pct
        // If actual_pct <= -sl_pct: counted as loss at -sl_pct
        // Otherwise: use actual outcome
        $sim_pct = $actual_pct;
        if ($actual_pct >= $tp_pct) {
            $sim_pct = $tp_pct;
            $wins++;
            $total_gain += $tp_pct;
        } elseif ($actual_pct <= -$sl_pct) {
            $sim_pct = -$sl_pct;
            $total_loss += $sl_pct;
        } else {
            if ($actual_pct > 0) { $wins++; $total_gain += $actual_pct; }
            else { $total_loss += abs($actual_pct); }
        }
        $total_return += $sim_pct;
    }

    $losses = $trades - $wins;
    $wr = ($trades > 0) ? round($wins / $trades * 100, 2) : 0;
    $avg_ret = ($trades > 0) ? round($total_return / $trades, 4) : 0;
    $pf = ($total_loss > 0) ? round($total_gain / $total_loss, 4) : ($total_gain > 0 ? 99.99 : 0);

    return array(
        'trades' => $trades, 'wins' => $wins, 'losses' => $losses,
        'win_rate' => $wr, 'avg_return' => $avg_ret, 'total_return' => round($total_return, 4),
        'profit_factor' => $pf
    );
}

// ═══════════════════════════════════════════════
// ACTION: analyze — Read-only analysis of all strategies
// ═══════════════════════════════════════════════
if ($action === 'analyze' || $action === 'adjust') {
    // Load current strategy defaults
    $strats = array();
    $sr = $conn->query("SELECT * FROM miracle_strategies3 WHERE enabled=1");
    if ($sr) { while ($row = $sr->fetch_assoc()) $strats[] = $row; }

    $recommendations = array();
    $adjustments_made = 0;

    foreach ($strats as $s) {
        $name = $s['name'];
        $scan_type = $s['scan_type'];
        $current_tp = (float)$s['default_tp_pct'];
        $current_sl = (float)$s['default_sl_pct'];

        // Current performance with default params
        $current_perf = miracle_mini_backtest($conn, $name, $current_tp, $current_sl);

        // Grid search: TP from 2-15%, SL from 1-8%
        $tp_grid = array(2, 3, 4, 5, 6, 7, 8, 10, 12, 15);
        $sl_grid = array(1, 1.5, 2, 2.5, 3, 4, 5, 6, 8);

        $best_return = -9999;
        $best_params = array('tp' => $current_tp, 'sl' => $current_sl);
        $best_perf = $current_perf;
        $profitable_combos = 0;
        $total_tested = 0;

        foreach ($tp_grid as $tp) {
            foreach ($sl_grid as $sl) {
                $r = miracle_mini_backtest($conn, $name, $tp, $sl);
                if ($r['trades'] > 0) {
                    $total_tested++;
                    // Score: weighted combo of win_rate + avg_return + profit_factor
                    $combo_score = $r['win_rate'] * 0.3 + $r['avg_return'] * 5 + $r['profit_factor'] * 10;
                    if ($r['avg_return'] > 0) $profitable_combos++;
                    if ($combo_score > $best_return) {
                        $best_return = $combo_score;
                        $best_params = array('tp' => $tp, 'sl' => $sl);
                        $best_perf = $r;
                    }
                }
            }
        }

        // Determine verdict
        $verdict = 'NO_DATA';
        if ($current_perf['trades'] === 0) {
            $verdict = 'NO_TRADES_YET';
        } elseif ($best_perf['avg_return'] > 0 && $best_perf['avg_return'] > $current_perf['avg_return']) {
            $verdict = 'BETTER_PARAMS_FOUND';
        } elseif ($best_perf['avg_return'] > 0) {
            $verdict = 'CURRENT_IS_NEAR_OPTIMAL';
        } else {
            $verdict = 'ALL_PARAMS_LOSING';
        }

        $rec = array(
            'strategy' => $name,
            'scan_type' => $scan_type,
            'current_params' => array('tp_pct' => $current_tp, 'sl_pct' => $current_sl),
            'current_performance' => $current_perf,
            'best_params' => $best_params,
            'best_performance' => $best_perf,
            'profitable_combos' => $profitable_combos,
            'total_combos_tested' => $total_tested,
            'verdict' => $verdict
        );

        // If adjusting, gradually shift parameters toward optimal
        if ($action === 'adjust' && $verdict === 'BETTER_PARAMS_FOUND' && $current_perf['trades'] >= 3) {
            // Max 20% shift per cycle to avoid whiplash
            $new_tp = round($current_tp + ($best_params['tp'] - $current_tp) * 0.20, 2);
            $new_sl = round($current_sl + ($best_params['sl'] - $current_sl) * 0.20, 2);

            // Bounds: TP 1-20%, SL 0.5-10%
            if ($new_tp < 1) $new_tp = 1;
            if ($new_tp > 20) $new_tp = 20;
            if ($new_sl < 0.5) $new_sl = 0.5;
            if ($new_sl > 10) $new_sl = 10;

            $tp_changed = abs($new_tp - $current_tp) > 0.01;
            $sl_changed = abs($new_sl - $current_sl) > 0.01;

            if ($tp_changed || $sl_changed) {
                $safe_name = $conn->real_escape_string($name);
                $conn->query("UPDATE miracle_strategies3 SET default_tp_pct=$new_tp, default_sl_pct=$new_sl WHERE name='$safe_name'");

                $now = date('Y-m-d H:i:s');

                if ($tp_changed) {
                    $reason = 'Grid search found optimal TP=' . $best_params['tp'] . '%. Shifted 20% toward it. Best WR=' . $best_perf['win_rate'] . '%, PF=' . $best_perf['profit_factor'];
                    $conn->query("INSERT INTO miracle_learning3 (strategy_name, param_name, old_value, new_value, reason, backtest_win_rate, backtest_return_pct, applied_at)
                        VALUES ('$safe_name', 'default_tp_pct', $current_tp, $new_tp, '" . $conn->real_escape_string($reason) . "', {$best_perf['win_rate']}, {$best_perf['avg_return']}, '$now')");
                }

                if ($sl_changed) {
                    $reason = 'Grid search found optimal SL=' . $best_params['sl'] . '%. Shifted 20% toward it. Best WR=' . $best_perf['win_rate'] . '%, PF=' . $best_perf['profit_factor'];
                    $conn->query("INSERT INTO miracle_learning3 (strategy_name, param_name, old_value, new_value, reason, backtest_win_rate, backtest_return_pct, applied_at)
                        VALUES ('$safe_name', 'default_sl_pct', $current_sl, $new_sl, '" . $conn->real_escape_string($reason) . "', {$best_perf['win_rate']}, {$best_perf['avg_return']}, '$now')");
                }

                $adjustments_made++;
                $rec['adjustment_applied'] = array('new_tp' => $new_tp, 'new_sl' => $new_sl, 'tp_shifted' => $tp_changed, 'sl_shifted' => $sl_changed);
            }
        }

        $recommendations[] = $rec;
    }

    $response['recommendations'] = $recommendations;
    $response['total_strategies'] = count($strats);
    if ($action === 'adjust') $response['adjustments_made'] = $adjustments_made;
}

// ═══════════════════════════════════════════════
// ACTION: permutation — Exhaustive grid search for one strategy
// ═══════════════════════════════════════════════
if ($action === 'permutation') {
    $strat_filter = isset($_GET['strategy']) ? trim($_GET['strategy']) : '';
    $top_n = isset($_GET['top']) ? (int)$_GET['top'] : 20;
    if ($top_n < 5) $top_n = 5;
    if ($top_n > 100) $top_n = 100;

    $tp_grid = array(1.5, 2, 2.5, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20);
    $sl_grid = array(0.5, 1, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10);

    $all_perms = array();
    foreach ($tp_grid as $tp) {
        foreach ($sl_grid as $sl) {
            $r = miracle_mini_backtest($conn, $strat_filter, $tp, $sl);
            if ($r['trades'] > 0) {
                $r['tp_pct'] = $tp;
                $r['sl_pct'] = $sl;
                $r['rr_ratio'] = ($sl > 0) ? round($tp / $sl, 2) : 99;
                $all_perms[] = $r;
            }
        }
    }

    // Sort by avg_return desc
    $ret_arr = array();
    for ($i = 0; $i < count($all_perms); $i++) $ret_arr[$i] = $all_perms[$i]['avg_return'];
    arsort($ret_arr);
    $sorted = array(); $rank = 0;
    foreach ($ret_arr as $idx => $val) { $sorted[] = $all_perms[$idx]; $rank++; if ($rank >= $top_n) break; }

    // Worst
    asort($ret_arr);
    $worst = array(); $rank = 0;
    foreach ($ret_arr as $idx => $val) { $worst[] = $all_perms[$idx]; $rank++; if ($rank >= 5) break; }

    $profitable = 0;
    foreach ($all_perms as $p) { if ($p['avg_return'] > 0) $profitable++; }

    $response['strategy'] = $strat_filter ? $strat_filter : 'ALL';
    $response['total_combos'] = count($tp_grid) * count($sl_grid);
    $response['tested'] = count($all_perms);
    $response['profitable_combos'] = $profitable;
    $response['profitability_rate'] = (count($all_perms) > 0) ? round($profitable / count($all_perms) * 100, 2) : 0;
    $response['top_permutations'] = $sorted;
    $response['worst_permutations'] = $worst;
}

// ═══════════════════════════════════════════════
// ACTION: performance — Store strategy performance snapshot
// ═══════════════════════════════════════════════
if ($action === 'performance') {
    $now = date('Y-m-d H:i:s');
    $today = date('Y-m-d');

    $sr = $conn->query("SELECT DISTINCT strategy_name FROM miracle_picks3");
    $strat_names = array();
    if ($sr) { while ($row = $sr->fetch_assoc()) $strat_names[] = $row['strategy_name']; }

    $stored = 0;
    foreach ($strat_names as $sname) {
        $safe = $conn->real_escape_string($sname);
        $res = $conn->query("SELECT
            COUNT(*) as total,
            SUM(CASE WHEN outcome='won' THEN 1 ELSE 0 END) as wins,
            SUM(CASE WHEN outcome='lost' THEN 1 ELSE 0 END) as losses,
            SUM(CASE WHEN outcome='pending' THEN 1 ELSE 0 END) as pending_count,
            AVG(CASE WHEN outcome='won' THEN outcome_pct ELSE NULL END) as avg_gain,
            AVG(CASE WHEN outcome='lost' THEN outcome_pct ELSE NULL END) as avg_loss,
            SUM(CASE WHEN outcome IN ('won','lost') THEN net_profit_if_tp ELSE 0 END) as total_pnl,
            MAX(CASE WHEN outcome='won' THEN outcome_pct ELSE NULL END) as best_pct,
            MIN(CASE WHEN outcome='lost' THEN outcome_pct ELSE NULL END) as worst_pct
            FROM miracle_picks3 WHERE strategy_name='$safe'");

        if (!$res) continue;
        $r = $res->fetch_assoc();

        $wins = (int)$r['wins'];
        $losses = (int)$r['losses'];
        $resolved = $wins + $losses;
        $wr = ($resolved > 0) ? round($wins / $resolved * 100, 2) : 0;
        $avg_gain = round((float)$r['avg_gain'], 4);
        $avg_loss = round((float)$r['avg_loss'], 4);
        $pf = (abs($avg_loss) > 0 && $losses > 0) ? round(($avg_gain * $wins) / (abs($avg_loss) * $losses), 4) : 0;
        $expect = ($resolved > 0) ? round(($wr / 100 * $avg_gain) + ((1 - $wr / 100) * $avg_loss), 4) : 0;

        // Get best/worst tickers
        $best_t = ''; $worst_t = '';
        $bt = $conn->query("SELECT ticker FROM miracle_picks3 WHERE strategy_name='$safe' AND outcome='won' ORDER BY outcome_pct DESC LIMIT 1");
        if ($bt && $bt->num_rows > 0) { $btr = $bt->fetch_assoc(); $best_t = $btr['ticker']; }
        $wt = $conn->query("SELECT ticker FROM miracle_picks3 WHERE strategy_name='$safe' AND outcome='lost' ORDER BY outcome_pct ASC LIMIT 1");
        if ($wt && $wt->num_rows > 0) { $wtr = $wt->fetch_assoc(); $worst_t = $wtr['ticker']; }

        $conn->query("INSERT INTO miracle_results3 (strategy_name, period, calc_date, total_picks, winners, losers, pending_count,
            win_rate, avg_gain_pct, avg_loss_pct, total_pnl, best_pick_ticker, best_pick_pct, worst_pick_ticker, worst_pick_pct,
            profit_factor, expectancy, created_at)
            VALUES ('$safe', 'cumulative', '$today', {$r['total']}, $wins, $losses, {$r['pending_count']},
            $wr, $avg_gain, $avg_loss, " . round((float)$r['total_pnl'], 2) . ", '" . $conn->real_escape_string($best_t) . "', " . round((float)$r['best_pct'], 4) . ",
            '" . $conn->real_escape_string($worst_t) . "', " . round((float)$r['worst_pct'], 4) . ",
            $pf, $expect, '$now')");
        $stored++;
    }

    $response['strategies_processed'] = count($strat_names);
    $response['records_stored'] = $stored;
}

// Audit log
$now = date('Y-m-d H:i:s');
$ip = isset($_SERVER['REMOTE_ADDR']) ? $conn->real_escape_string($_SERVER['REMOTE_ADDR']) : 'unknown';
$conn->query("INSERT INTO miracle_audit3 (action_type, details, ip_address, created_at) VALUES ('learning_$action', '" . $conn->real_escape_string($action) . "', '$ip', '$now')");

echo json_encode($response);
$conn->close();
?>
