<?php
/**
 * DayTraders Miracle_CURSOR — Picks API (Claude-generated)
 * List, filter, and retrieve miracle picks.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Usage:
 *   GET .../picks3.php                           -- today's picks
 *   GET .../picks3.php?date=2026-02-09           -- specific date
 *   GET .../picks3.php?strategy=gap_up           -- filter by strategy
 *   GET .../picks3.php?outcome=pending           -- filter by outcome
 *   GET .../picks3.php?cdr_only=1                -- CDR tickers only
 *   GET .../picks3.php?min_score=70              -- minimum score filter
 *   GET .../picks3.php?limit=50                  -- limit results
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$response = array('ok' => true);

$date_filter = isset($_GET['date']) ? trim($_GET['date']) : '';
$strategy_filter = isset($_GET['strategy']) ? trim($_GET['strategy']) : '';
$outcome_filter = isset($_GET['outcome']) ? trim($_GET['outcome']) : '';
$cdr_only = isset($_GET['cdr_only']) ? (int)$_GET['cdr_only'] : 0;
$min_score = isset($_GET['min_score']) ? (int)$_GET['min_score'] : 0;
$limit = isset($_GET['limit']) ? (int)$_GET['limit'] : 100;
if ($limit < 1) $limit = 100;
if ($limit > 500) $limit = 500;

$conditions = array();

if ($date_filter !== '') {
    $safe = $conn->real_escape_string($date_filter);
    $conditions[] = "scan_date = '$safe'";
} else {
    // Default: today and yesterday (in case today's scan hasn't run yet)
    $conditions[] = "scan_date >= DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
}

if ($strategy_filter !== '') {
    $safe = $conn->real_escape_string($strategy_filter);
    $conditions[] = "strategy_name LIKE '%$safe%'";
}

if ($outcome_filter !== '') {
    $safe = $conn->real_escape_string($outcome_filter);
    $conditions[] = "outcome = '$safe'";
}

if ($cdr_only) {
    $conditions[] = "is_cdr = 1";
}

if ($min_score > 0) {
    $conditions[] = "score >= $min_score";
}

$where = '';
if (count($conditions) > 0) {
    $where = 'WHERE ' . implode(' AND ', $conditions);
}

$sql = "SELECT * FROM miracle_picks3 $where ORDER BY score DESC, scan_date DESC LIMIT $limit";
$res = $conn->query($sql);
$picks = array();
if ($res) {
    while ($row = $res->fetch_assoc()) {
        // Parse signals JSON
        if (isset($row['signals_json']) && $row['signals_json'] !== '') {
            $row['signals'] = json_decode($row['signals_json'], true);
        }
        unset($row['signals_json']);
        $picks[] = $row;
    }
}

$response['picks'] = $picks;
$response['count'] = count($picks);
$response['filters'] = array(
    'date' => $date_filter ? $date_filter : 'latest',
    'strategy' => $strategy_filter ? $strategy_filter : 'all',
    'outcome' => $outcome_filter ? $outcome_filter : 'all',
    'cdr_only' => $cdr_only,
    'min_score' => $min_score
);

echo json_encode($response);
$conn->close();
?>
