<?php
/**
 * DayTraders Miracle_CURSOR — Outcome Resolver (Claude-generated)
 * Checks pending picks against latest prices to determine win/loss.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Usage: GET .../resolve3.php              -- resolve all pending picks
 *        GET .../resolve3.php?days=7       -- only resolve picks from last N days
 *        GET .../resolve3.php?expire=3     -- auto-close picks older than N days
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$response = array('ok' => true, 'resolved' => 0, 'expired' => 0, 'still_pending' => 0, 'errors' => array());
$max_days = isset($_GET['days']) ? (int)$_GET['days'] : 30;
$expire_days = isset($_GET['expire']) ? (int)$_GET['expire'] : 5; // auto-close after N days

$now = date('Y-m-d');
$now_dt = date('Y-m-d H:i:s');

// Load pending picks
$res = $conn->query("SELECT id, ticker, entry_price, stop_loss_price, take_profit_price, stop_loss_pct, take_profit_pct, scan_date
    FROM miracle_picks3
    WHERE outcome='pending' AND scan_date >= DATE_SUB(CURDATE(), INTERVAL $max_days DAY)
    ORDER BY scan_date DESC");

$pending = array();
if ($res) {
    while ($row = $res->fetch_assoc()) $pending[] = $row;
}

// Group by ticker to minimize API calls
$ticker_picks = array();
foreach ($pending as $p) {
    $t = $p['ticker'];
    if (!isset($ticker_picks[$t])) $ticker_picks[$t] = array();
    $ticker_picks[$t][] = $p;
}

foreach ($ticker_picks as $ticker => $picks) {
    // Fetch recent price data
    $url = 'https://query1.finance.yahoo.com/v8/finance/chart/' . urlencode($ticker) . '?range=10d&interval=1d';
    $ctx = stream_context_create(array('http' => array('timeout' => 10, 'header' => 'User-Agent: Mozilla/5.0')));
    $raw = @file_get_contents($url, false, $ctx);
    if ($raw === false) {
        $response['errors'][] = $ticker . ': Failed to fetch price';
        continue;
    }

    $data = json_decode($raw, true);
    if (!$data || !isset($data['chart']['result'][0])) {
        $response['errors'][] = $ticker . ': Invalid response';
        continue;
    }

    $result = $data['chart']['result'][0];
    $timestamps = isset($result['timestamp']) ? $result['timestamp'] : array();
    $quotes = isset($result['indicators']['quote'][0]) ? $result['indicators']['quote'][0] : array();

    // Build price history: date => {high, low, close}
    $price_days = array();
    for ($i = 0; $i < count($timestamps); $i++) {
        $d = date('Y-m-d', $timestamps[$i]);
        $price_days[$d] = array(
            'high' => isset($quotes['high'][$i]) ? (float)$quotes['high'][$i] : 0,
            'low' => isset($quotes['low'][$i]) ? (float)$quotes['low'][$i] : 0,
            'close' => isset($quotes['close'][$i]) ? (float)$quotes['close'][$i] : 0
        );
    }

    foreach ($picks as $pick) {
        $entry = (float)$pick['entry_price'];
        $tp = (float)$pick['take_profit_price'];
        $sl = (float)$pick['stop_loss_price'];
        $scan_date = $pick['scan_date'];
        $pick_id = (int)$pick['id'];

        // Check each day after scan_date
        $outcome = 'pending';
        $outcome_price = 0;
        $outcome_reason = '';

        foreach ($price_days as $d => $prices) {
            if ($d <= $scan_date) continue; // only check days after the pick

            // Check stop loss hit (low went below SL)
            if ($sl > 0 && $prices['low'] <= $sl) {
                $outcome = 'lost';
                $outcome_price = $sl;
                $outcome_reason = 'stop_loss';
                break;
            }

            // Check take profit hit (high went above TP)
            if ($tp > 0 && $prices['high'] >= $tp) {
                $outcome = 'won';
                $outcome_price = $tp;
                $outcome_reason = 'take_profit';
                break;
            }
        }

        // Check expiry (auto-close after expire_days)
        if ($outcome === 'pending') {
            $days_open = (strtotime($now) - strtotime($scan_date)) / 86400;
            if ($days_open >= $expire_days) {
                // Close at latest available price
                $latest_prices = end($price_days);
                if ($latest_prices) {
                    $outcome_price = $latest_prices['close'];
                    $pct = ($entry > 0) ? ($outcome_price - $entry) / $entry * 100 : 0;
                    $outcome = ($pct > 0) ? 'won' : 'lost';
                    $outcome_reason = 'expired';
                }
            }
        }

        if ($outcome !== 'pending') {
            $pct = ($entry > 0) ? round(($outcome_price - $entry) / $entry * 100, 4) : 0;
            $conn->query("UPDATE miracle_picks3 SET outcome='$outcome', outcome_price=$outcome_price,
                outcome_pct=$pct, outcome_date='$now', outcome_reason='$outcome_reason'
                WHERE id=$pick_id");
            $response['resolved']++;
            if ($outcome_reason === 'expired') $response['expired']++;
        } else {
            $response['still_pending']++;
        }
    }
}

// Audit
$ip = isset($_SERVER['REMOTE_ADDR']) ? $conn->real_escape_string($_SERVER['REMOTE_ADDR']) : 'unknown';
$det = 'Resolved ' . $response['resolved'] . ' picks (' . $response['expired'] . ' expired), ' . $response['still_pending'] . ' still pending';
$conn->query("INSERT INTO miracle_audit3 (action_type, details, ip_address, created_at) VALUES ('resolve', '" . $conn->real_escape_string($det) . "', '$ip', '$now_dt')");

echo json_encode($response);
$conn->close();
?>
