<?php
/**
 * DayTraders Miracle_CURSOR — Core Scanner Engine (Claude-generated)
 * Fetches real-time Yahoo Finance data, runs 8 screening strategies,
 * scores & ranks picks, calculates Questrade commission-aware profit targets.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Usage: GET .../scanner3.php                  -- run full scan
 *        GET .../scanner3.php?strategy=gap_up  -- run one strategy
 *        GET .../scanner3.php?ticker=AAPL      -- scan one ticker
 *        GET .../scanner3.php?batch=10&offset=0 -- batch scan (10 tickers starting at offset 0)
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$response = array('ok' => true, 'scan_date' => date('Y-m-d'), 'scan_time' => date('Y-m-d H:i:s'));
$strategy_filter = isset($_GET['strategy']) ? trim($_GET['strategy']) : '';
$ticker_filter = isset($_GET['ticker']) ? strtoupper(trim($_GET['ticker'])) : '';
$min_score = isset($_GET['min_score']) ? (int)$_GET['min_score'] : 40;
$batch_size = isset($_GET['batch']) ? (int)$_GET['batch'] : 0;
$offset = isset($_GET['offset']) ? (int)$_GET['offset'] : 0;

// ═══════════════════════════════════════════════
// CDR LIST (from Questrade)
// ═══════════════════════════════════════════════
$CDR_TICKERS = array(
    'AAPL','AMD','AMZN','CSCO','CRM','GOOG','GOOGL','IBM','INTC','META','MSFT','NFLX','NVDA',
    'COST','DIS','HD','MCD','NKE','SBUX','TSLA','WMT',
    'ABBV','CVS','JNJ','PFE','UNH',
    'BAC','BRK.B','CITI','GS','JPM','MA','PYPL','V',
    'BA','CVX','XOM','HON','UPS','KO','VZ','UBER'
);
$TSX_SUFFIXES = array('.TO', '.V', '.CN');

function is_cdr_ticker($ticker) {
    global $CDR_TICKERS;
    $upper = strtoupper(trim($ticker));
    $base = preg_replace('/\.(TO|V|CN)$/', '', $upper);
    return in_array($upper, $CDR_TICKERS) || in_array($base, $CDR_TICKERS);
}

function is_canadian_ticker($ticker) {
    global $TSX_SUFFIXES;
    $upper = strtoupper(trim($ticker));
    foreach ($TSX_SUFFIXES as $s) {
        if (substr($upper, -strlen($s)) === strtoupper($s)) return true;
    }
    return false;
}

function calc_questrade_roundtrip($ticker, $entry, $exit, $shares) {
    $is_cdr = is_cdr_ticker($ticker);
    $is_can = is_canadian_ticker($ticker);
    if ($is_cdr || $is_can) return 0;
    // US stock: forex 1.75% on buy + sell
    $buy_val = $entry * $shares;
    $sell_val = $exit * $shares;
    $forex = ($buy_val + $sell_val) * 0.0175;
    $ecn = $shares * 0.0035 * 2;
    $sec = $sell_val * 0.0000278;
    return round($forex + $ecn + $sec, 2);
}

// ═══════════════════════════════════════════════
// YAHOO FINANCE DATA FETCHER
// ═══════════════════════════════════════════════
function fetch_yahoo_quote($ticker) {
    $url = 'https://query1.finance.yahoo.com/v8/finance/chart/' . urlencode($ticker) . '?range=35d&interval=1d&includeAdjustedClose=true';
    $ctx = stream_context_create(array('http' => array('timeout' => 10, 'header' => 'User-Agent: Mozilla/5.0')));
    $raw = @file_get_contents($url, false, $ctx);
    if ($raw === false) return null;

    $data = json_decode($raw, true);
    if (!$data || !isset($data['chart']['result'][0])) return null;

    $result = $data['chart']['result'][0];
    $meta = isset($result['meta']) ? $result['meta'] : array();
    $timestamps = isset($result['timestamp']) ? $result['timestamp'] : array();
    $quotes = isset($result['indicators']['quote'][0]) ? $result['indicators']['quote'][0] : array();

    if (count($timestamps) < 5) return null;

    $candles = array();
    for ($i = 0; $i < count($timestamps); $i++) {
        $o = isset($quotes['open'][$i]) ? (float)$quotes['open'][$i] : 0;
        $h = isset($quotes['high'][$i]) ? (float)$quotes['high'][$i] : 0;
        $l = isset($quotes['low'][$i]) ? (float)$quotes['low'][$i] : 0;
        $c = isset($quotes['close'][$i]) ? (float)$quotes['close'][$i] : 0;
        $v = isset($quotes['volume'][$i]) ? (int)$quotes['volume'][$i] : 0;
        if ($c <= 0) continue;
        $candles[] = array('date' => date('Y-m-d', $timestamps[$i]), 'o' => $o, 'h' => $h, 'l' => $l, 'c' => $c, 'v' => $v);
    }

    if (count($candles) < 5) return null;

    return array(
        'ticker' => $ticker,
        'name' => isset($meta['longName']) ? $meta['longName'] : (isset($meta['shortName']) ? $meta['shortName'] : $ticker),
        'currency' => isset($meta['currency']) ? $meta['currency'] : 'USD',
        'exchange' => isset($meta['exchangeName']) ? $meta['exchangeName'] : '',
        'candles' => $candles
    );
}

// ═══════════════════════════════════════════════
// TECHNICAL INDICATORS
// ═══════════════════════════════════════════════
function calc_sma($closes, $period) {
    $n = count($closes);
    if ($n < $period) return 0;
    $sum = 0;
    for ($i = $n - $period; $i < $n; $i++) $sum += $closes[$i];
    return $sum / $period;
}

function calc_rsi($closes, $period) {
    $n = count($closes);
    if ($n < $period + 1) return 50;
    $gains = 0; $losses = 0;
    for ($i = $n - $period; $i < $n; $i++) {
        $diff = $closes[$i] - $closes[$i - 1];
        if ($diff > 0) $gains += $diff;
        else $losses += abs($diff);
    }
    $avg_gain = $gains / $period;
    $avg_loss = $losses / $period;
    if ($avg_loss == 0) return 100;
    $rs = $avg_gain / $avg_loss;
    return round(100 - (100 / (1 + $rs)), 2);
}

function calc_bollinger($closes, $period, $mult) {
    $n = count($closes);
    if ($n < $period) return array('mid' => 0, 'upper' => 0, 'lower' => 0);
    $sma = calc_sma($closes, $period);
    $sum_sq = 0;
    for ($i = $n - $period; $i < $n; $i++) {
        $diff = $closes[$i] - $sma;
        $sum_sq += $diff * $diff;
    }
    $std = sqrt($sum_sq / $period);
    return array('mid' => round($sma, 4), 'upper' => round($sma + $mult * $std, 4), 'lower' => round($sma - $mult * $std, 4));
}

function calc_atr($candles, $period) {
    $n = count($candles);
    if ($n < $period + 1) return 0;
    $tr_sum = 0;
    for ($i = $n - $period; $i < $n; $i++) {
        $tr1 = $candles[$i]['h'] - $candles[$i]['l'];
        $tr2 = abs($candles[$i]['h'] - $candles[$i - 1]['c']);
        $tr3 = abs($candles[$i]['l'] - $candles[$i - 1]['c']);
        $tr_sum += max($tr1, $tr2, $tr3);
    }
    return round($tr_sum / $period, 4);
}

function calc_zscore($closes, $period) {
    $n = count($closes);
    if ($n < $period) return 0;
    $sma = calc_sma($closes, $period);
    $sum_sq = 0;
    for ($i = $n - $period; $i < $n; $i++) {
        $diff = $closes[$i] - $sma;
        $sum_sq += $diff * $diff;
    }
    $std = sqrt($sum_sq / $period);
    if ($std == 0) return 0;
    return round(($closes[$n - 1] - $sma) / $std, 4);
}

function calc_avg_volume($candles, $period) {
    $n = count($candles);
    if ($n < $period) $period = $n;
    $sum = 0;
    for ($i = $n - $period; $i < $n; $i++) $sum += $candles[$i]['v'];
    return ($period > 0) ? $sum / $period : 0;
}

function consecutive_red_days($candles) {
    $n = count($candles);
    $count = 0;
    for ($i = $n - 1; $i >= 0; $i--) {
        if ($candles[$i]['c'] < $candles[$i]['o']) $count++;
        else break;
    }
    return $count;
}

// ═══════════════════════════════════════════════
// 8 DAY-TRADING STRATEGIES
// ═══════════════════════════════════════════════

// Strategy 1: Gap Up Momentum
function scan_gap_up($candles, $ticker) {
    $n = count($candles);
    if ($n < 5) return null;
    $today = $candles[$n - 1];
    $yesterday = $candles[$n - 2];
    $gap_pct = ($today['o'] - $yesterday['c']) / $yesterday['c'] * 100;
    if ($gap_pct < 3.0) return null;

    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 0;
    if ($vol_ratio < 1.5) return null;

    $signal = min(30, round($gap_pct * 4));
    $vol_score = ($vol_ratio >= 3) ? 20 : (($vol_ratio >= 2) ? 15 : 10);

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];
    $sma20 = calc_sma($closes, 20);
    $trend = ($today['c'] > $sma20) ? 15 : 5;

    $tp_pct = round($gap_pct * 1.5, 2);
    if ($tp_pct < 3) $tp_pct = 3;
    if ($tp_pct > 15) $tp_pct = 15;
    $sl_pct = round($gap_pct * 0.5, 2);
    if ($sl_pct < 1.5) $sl_pct = 1.5;

    return array(
        'strategy' => 'Gap Up Momentum',
        'scan_type' => 'gap_up',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => $tp_pct,
        'sl_pct' => $sl_pct,
        'signals' => array('gap_pct' => round($gap_pct, 2), 'volume_ratio' => round($vol_ratio, 2))
    );
}

// Strategy 2: Volume Surge Breakout
function scan_volume_surge($candles, $ticker) {
    $n = count($candles);
    if ($n < 21) return null;
    $today = $candles[$n - 1];

    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 0;
    if ($vol_ratio < 2.5) return null;

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

    // Check 20-day high breakout
    $high_20 = 0;
    for ($i = $n - 21; $i < $n - 1; $i++) {
        if ($candles[$i]['h'] > $high_20) $high_20 = $candles[$i]['h'];
    }
    if ($today['h'] <= $high_20) return null;

    $rsi = calc_rsi($closes, 14);
    if ($rsi > 80) return null; // overextended

    $signal = min(30, round($vol_ratio * 5));
    $vol_score = ($vol_ratio >= 4) ? 20 : (($vol_ratio >= 3) ? 18 : 12);
    $sma20 = calc_sma($closes, 20);
    $sma50 = calc_sma($closes, min(count($closes), 50));
    $trend = ($today['c'] > $sma20 && $sma20 > $sma50) ? 20 : (($today['c'] > $sma20) ? 12 : 5);

    $atr = calc_atr($candles, 14);
    $tp_pct = ($today['c'] > 0) ? round(($atr * 2) / $today['c'] * 100, 2) : 6;
    $sl_pct = ($today['c'] > 0) ? round($atr / $today['c'] * 100, 2) : 3;
    if ($tp_pct < 3) $tp_pct = 3;
    if ($tp_pct > 12) $tp_pct = 12;
    if ($sl_pct < 1.5) $sl_pct = 1.5;

    return array(
        'strategy' => 'Volume Surge Breakout',
        'scan_type' => 'volume_surge',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => $tp_pct,
        'sl_pct' => $sl_pct,
        'signals' => array('volume_ratio' => round($vol_ratio, 2), 'rsi' => $rsi, 'breakout_above' => round($high_20, 2))
    );
}

// Strategy 3: Oversold Bounce
function scan_oversold_bounce($candles, $ticker) {
    $n = count($candles);
    if ($n < 21) return null;
    $today = $candles[$n - 1];

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

    $rsi = calc_rsi($closes, 14);
    if ($rsi > 35) return null;

    $bb = calc_bollinger($closes, 20, 2);
    if ($today['c'] > $bb['lower'] * 1.02) return null; // must be near lower band

    // Reversal candle: today close > today open after red days
    $red_days = consecutive_red_days(array_slice($candles, 0, $n - 1));
    if ($red_days < 2) return null;
    if ($today['c'] <= $today['o']) return null; // must be green candle

    $signal = min(30, round((35 - $rsi) * 2));
    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 1;
    $vol_score = ($vol_ratio >= 2) ? 18 : (($vol_ratio >= 1.3) ? 12 : 8);

    $sma200 = calc_sma($closes, min(count($closes), 30)); // approx
    $trend = ($today['c'] > $sma200 * 0.9) ? 15 : 5;

    // Target: middle Bollinger band
    $tp_pct = ($today['c'] > 0) ? round(($bb['mid'] - $today['c']) / $today['c'] * 100, 2) : 4;
    if ($tp_pct < 2) $tp_pct = 2;
    if ($tp_pct > 10) $tp_pct = 10;
    $sl_pct = 3.0;

    return array(
        'strategy' => 'Oversold Bounce',
        'scan_type' => 'oversold_bounce',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => $tp_pct,
        'sl_pct' => $sl_pct,
        'signals' => array('rsi' => $rsi, 'bb_lower' => $bb['lower'], 'red_days' => $red_days, 'reversal' => true)
    );
}

// Strategy 4: Momentum Continuation
function scan_momentum_cont($candles, $ticker) {
    $n = count($candles);
    if ($n < 21) return null;
    $today = $candles[$n - 1];

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

    $sma20 = calc_sma($closes, 20);
    $sma50 = calc_sma($closes, min(count($closes), 50));

    // Must be in uptrend: price > SMA20 > SMA50 (or approx)
    if ($sma20 <= $sma50 * 0.99) return null;

    // Pullback to SMA20: today's low near SMA20
    $dist_to_sma20 = abs($today['l'] - $sma20) / $sma20 * 100;
    if ($dist_to_sma20 > 2.0) return null; // too far from SMA20

    // Bounce: close above open (green candle)
    if ($today['c'] <= $today['o']) return null;

    $signal = min(30, round((2.0 - $dist_to_sma20) * 15));
    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 1;
    $vol_score = ($vol_ratio >= 2) ? 18 : (($vol_ratio >= 1.2) ? 12 : 6);
    $trend = 20; // already verified uptrend

    // Target: previous swing high
    $prev_high = 0;
    for ($i = max(0, $n - 10); $i < $n - 1; $i++) {
        if ($candles[$i]['h'] > $prev_high) $prev_high = $candles[$i]['h'];
    }
    $tp_pct = ($today['c'] > 0 && $prev_high > $today['c']) ? round(($prev_high - $today['c']) / $today['c'] * 100, 2) : 5;
    if ($tp_pct < 2) $tp_pct = 2;
    if ($tp_pct > 12) $tp_pct = 12;
    $sl_pct = ($today['c'] > 0 && $sma50 > 0) ? round(($today['c'] - $sma50) / $today['c'] * 100, 2) : 3.5;
    if ($sl_pct < 2) $sl_pct = 2;
    if ($sl_pct > 6) $sl_pct = 6;

    return array(
        'strategy' => 'Momentum Continuation',
        'scan_type' => 'momentum_cont',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => $tp_pct,
        'sl_pct' => $sl_pct,
        'signals' => array('sma20' => round($sma20, 2), 'sma50' => round($sma50, 2), 'pullback_dist' => round($dist_to_sma20, 2))
    );
}

// Strategy 5: Earnings Catalyst Runner (simplified - checks for recent big moves)
function scan_earnings_runner($candles, $ticker) {
    $n = count($candles);
    if ($n < 10) return null;

    // Look for a big gap + volume in last 5 days (proxy for earnings)
    for ($d = 1; $d <= 5; $d++) {
        $idx = $n - $d;
        if ($idx < 1) continue;
        $day = $candles[$idx];
        $prev = $candles[$idx - 1];
        $gap_pct = ($prev['c'] > 0) ? ($day['o'] - $prev['c']) / $prev['c'] * 100 : 0;
        $avg_vol = calc_avg_volume(array_slice($candles, 0, $idx), 20);
        $vol_ratio = ($avg_vol > 0) ? $day['v'] / $avg_vol : 0;

        if (abs($gap_pct) >= 5 && $vol_ratio >= 2.5) {
            // Found earnings-like catalyst
            $today = $candles[$n - 1];
            $closes = array();
            for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

            // Only if still moving in gap direction (PEAD)
            if ($gap_pct > 0 && $today['c'] < $day['o']) return null; // reversal
            if ($gap_pct < 0) return null; // only bullish catalysts

            $direction = 'LONG';
            $signal = min(30, round(abs($gap_pct) * 2));
            $vol_score = ($vol_ratio >= 4) ? 20 : 15;
            $trend = ($today['c'] > $day['o']) ? 18 : 10;

            return array(
                'strategy' => 'Earnings Catalyst Runner',
                'scan_type' => 'earnings_runner',
                'signal_strength' => $signal,
                'volume_score' => $vol_score,
                'trend_score' => $trend,
                'tp_pct' => 10.0,
                'sl_pct' => 4.0,
                'signals' => array('catalyst_gap' => round($gap_pct, 2), 'catalyst_vol_ratio' => round($vol_ratio, 2), 'days_ago' => $d)
            );
        }
    }
    return null;
}

// Strategy 6: CDR Zero-Fee Priority
function scan_cdr_priority($candles, $ticker) {
    if (!is_cdr_ticker($ticker)) return null;

    $n = count($candles);
    if ($n < 15) return null;
    $today = $candles[$n - 1];

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

    $rsi = calc_rsi($closes, 14);
    $sma20 = calc_sma($closes, 20);
    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 1;

    // CDR bonus: any reasonable setup qualifies (lower thresholds)
    $signal = 0;
    $signals_data = array('rsi' => $rsi, 'sma20' => round($sma20, 2), 'vol_ratio' => round($vol_ratio, 2));

    // Momentum: above SMA20 + green candle
    if ($today['c'] > $sma20 && $today['c'] > $today['o']) $signal += 15;
    // Volume confirmation
    if ($vol_ratio > 1.3) $signal += 10;
    // RSI not overextended
    if ($rsi < 70 && $rsi > 30) $signal += 8;
    // Recent strength
    $change_5d = ($n >= 6 && $candles[$n - 6]['c'] > 0) ? ($today['c'] - $candles[$n - 6]['c']) / $candles[$n - 6]['c'] * 100 : 0;
    if ($change_5d > 1) $signal += 7;

    if ($signal < 20) return null;

    $vol_score = ($vol_ratio >= 2) ? 15 : (($vol_ratio >= 1.3) ? 10 : 5);
    $trend = ($today['c'] > $sma20) ? 15 : 5;

    return array(
        'strategy' => 'CDR Zero-Fee Priority',
        'scan_type' => 'cdr_priority',
        'signal_strength' => min(30, $signal),
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => 5.0,
        'sl_pct' => 2.5,
        'signals' => $signals_data
    );
}

// Strategy 7: Sector Momentum Leader
function scan_sector_leader($candles, $ticker) {
    $n = count($candles);
    if ($n < 10) return null;
    $today = $candles[$n - 1];
    $yesterday = $candles[$n - 2];

    $day_change = ($yesterday['c'] > 0) ? ($today['c'] - $yesterday['c']) / $yesterday['c'] * 100 : 0;
    if ($day_change < 2.0) return null; // must be outperforming significantly

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];
    $sma20 = calc_sma($closes, 20);

    // Must be above SMA20
    if ($today['c'] <= $sma20) return null;

    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 1;
    if ($vol_ratio < 1.2) return null;

    $signal = min(30, round($day_change * 5));
    $vol_score = ($vol_ratio >= 2) ? 18 : (($vol_ratio >= 1.5) ? 12 : 8);
    $trend = ($today['c'] > $sma20) ? 15 : 5;

    return array(
        'strategy' => 'Sector Momentum Leader',
        'scan_type' => 'sector_leader',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => 5.0,
        'sl_pct' => 2.0,
        'signals' => array('day_change_pct' => round($day_change, 2), 'vol_ratio' => round($vol_ratio, 2))
    );
}

// Strategy 8: Mean Reversion Sniper
function scan_mean_reversion($candles, $ticker) {
    $n = count($candles);
    if ($n < 21) return null;
    $today = $candles[$n - 1];

    $closes = array();
    for ($i = 0; $i < $n; $i++) $closes[] = $candles[$i]['c'];

    $zscore = calc_zscore($closes, 20);
    if ($zscore > -1.5) return null; // must be significantly below mean

    $sma20 = calc_sma($closes, 20);
    // Longer-term trend must not be broken (SMA of available data still roughly rising)
    $sma_early = calc_sma(array_slice($closes, 0, min(15, count($closes))), min(10, count($closes)));
    if ($sma20 < $sma_early * 0.95) return null; // structural downtrend, skip

    $signal = min(30, round(abs($zscore) * 12));
    $avg_vol = calc_avg_volume(array_slice($candles, 0, $n - 1), 20);
    $vol_ratio = ($avg_vol > 0) ? $today['v'] / $avg_vol : 1;
    $vol_score = ($vol_ratio >= 1.5) ? 15 : 8;
    $trend = 10; // neutral since we're betting on reversion

    // Target: return to mean (Z=0)
    $tp_pct = ($today['c'] > 0) ? round(($sma20 - $today['c']) / $today['c'] * 100, 2) : 4;
    if ($tp_pct < 2) $tp_pct = 2;
    if ($tp_pct > 10) $tp_pct = 10;
    $sl_pct = round($tp_pct * 0.6, 2);
    if ($sl_pct < 1.5) $sl_pct = 1.5;

    return array(
        'strategy' => 'Mean Reversion Sniper',
        'scan_type' => 'mean_reversion',
        'signal_strength' => $signal,
        'volume_score' => $vol_score,
        'trend_score' => $trend,
        'tp_pct' => $tp_pct,
        'sl_pct' => $sl_pct,
        'signals' => array('zscore' => $zscore, 'sma20' => round($sma20, 2), 'deviation' => round($sma20 - $today['c'], 2))
    );
}

// ═══════════════════════════════════════════════
// MAIN SCANNER LOOP
// ═══════════════════════════════════════════════

// Load strategy defaults
$strat_defaults = array();
$sr = $conn->query("SELECT name, scan_type, default_tp_pct, default_sl_pct, min_score FROM miracle_strategies3 WHERE enabled=1");
if ($sr) {
    while ($row = $sr->fetch_assoc()) {
        $strat_defaults[$row['scan_type']] = $row;
    }
}

// Load watchlist
$where_wl = "WHERE active=1";
if ($ticker_filter !== '') {
    $safe_t = $conn->real_escape_string($ticker_filter);
    $where_wl = "WHERE ticker='$safe_t'";
}
$wl_res = $conn->query("SELECT ticker, company_name, sector, is_cdr, is_canadian FROM miracle_watchlist3 $where_wl ORDER BY is_cdr DESC, ticker ASC");
$watchlist = array();
if ($wl_res) {
    while ($row = $wl_res->fetch_assoc()) $watchlist[] = $row;
}

$total_watchlist = count($watchlist);

// Batch mode: slice the watchlist
if ($batch_size > 0 && $ticker_filter === '') {
    $watchlist = array_slice($watchlist, $offset, $batch_size);
    $response['batch'] = array(
        'size' => $batch_size,
        'offset' => $offset,
        'total' => $total_watchlist,
        'has_more' => ($offset + $batch_size) < $total_watchlist
    );
}

$all_strategies = array('gap_up', 'volume_surge', 'oversold_bounce', 'momentum_cont', 'earnings_runner', 'cdr_priority', 'sector_leader', 'mean_reversion');
$scan_strategies = ($strategy_filter !== '') ? array($strategy_filter) : $all_strategies;

$all_picks = array();
$scanned = 0;
$errors = array();

foreach ($watchlist as $wl_item) {
    $ticker = $wl_item['ticker'];

    // Fetch data from Yahoo Finance
    $quote = fetch_yahoo_quote($ticker);
    if ($quote === null) {
        $errors[] = $ticker . ': Failed to fetch data';
        continue;
    }
    $scanned++;

    $candles = $quote['candles'];
    $latest = $candles[count($candles) - 1];
    $entry = $latest['c'];

    foreach ($scan_strategies as $strat) {
        $result = null;
        switch ($strat) {
            case 'gap_up': $result = scan_gap_up($candles, $ticker); break;
            case 'volume_surge': $result = scan_volume_surge($candles, $ticker); break;
            case 'oversold_bounce': $result = scan_oversold_bounce($candles, $ticker); break;
            case 'momentum_cont': $result = scan_momentum_cont($candles, $ticker); break;
            case 'earnings_runner': $result = scan_earnings_runner($candles, $ticker); break;
            case 'cdr_priority': $result = scan_cdr_priority($candles, $ticker); break;
            case 'sector_leader': $result = scan_sector_leader($candles, $ticker); break;
            case 'mean_reversion': $result = scan_mean_reversion($candles, $ticker); break;
        }

        if ($result === null) continue;

        // CDR bonus
        $cdr_bonus = is_cdr_ticker($ticker) ? 10 : 0;

        // Risk/reward score
        $rr = ($result['sl_pct'] > 0) ? $result['tp_pct'] / $result['sl_pct'] : 1;
        $rr_score = ($rr >= 3) ? 20 : (($rr >= 2) ? 15 : (($rr >= 1.5) ? 10 : 5));

        $total_score = $result['signal_strength'] + $result['volume_score'] + $result['trend_score'] + $cdr_bonus + $rr_score;
        if ($total_score < $min_score) continue;

        // Confidence label
        $confidence = 'Weak';
        if ($total_score >= 85) $confidence = 'Extremely Strong';
        elseif ($total_score >= 75) $confidence = 'Very Strong';
        elseif ($total_score >= 65) $confidence = 'Strong';
        elseif ($total_score >= 55) $confidence = 'Okay';
        elseif ($total_score >= 45) $confidence = 'Weak';
        else $confidence = 'Very Weak';

        $tp_price = round($entry * (1 + $result['tp_pct'] / 100), 4);
        $sl_price = round($entry * (1 - $result['sl_pct'] / 100), 4);

        // Questrade fee calculation (100 shares as reference)
        $shares = max(1, round(1000 / $entry));
        $roundtrip_fee = calc_questrade_roundtrip($ticker, $entry, $tp_price, $shares);
        $gross_profit = ($tp_price - $entry) * $shares;
        $net_profit = round($gross_profit - $roundtrip_fee, 2);

        $pick_hash = md5($ticker . '|' . $result['scan_type'] . '|' . date('Y-m-d'));

        $all_picks[] = array(
            'ticker' => $ticker,
            'company_name' => $wl_item['company_name'] ? $wl_item['company_name'] : $quote['name'],
            'strategy' => $result['strategy'],
            'scan_type' => $result['scan_type'],
            'entry_price' => $entry,
            'take_profit_price' => $tp_price,
            'stop_loss_price' => $sl_price,
            'tp_pct' => $result['tp_pct'],
            'sl_pct' => $result['sl_pct'],
            'score' => $total_score,
            'confidence' => $confidence,
            'direction' => 'LONG',
            'is_cdr' => is_cdr_ticker($ticker) ? 1 : 0,
            'is_canadian' => is_canadian_ticker($ticker) ? 1 : 0,
            'risk_reward' => round($rr, 2),
            'ref_shares' => $shares,
            'questrade_roundtrip_fee' => $roundtrip_fee,
            'gross_profit_if_tp' => round($gross_profit, 2),
            'net_profit_if_tp' => $net_profit,
            'signals' => $result['signals'],
            'pick_hash' => $pick_hash,
            'score_breakdown' => array(
                'signal' => $result['signal_strength'],
                'volume' => $result['volume_score'],
                'trend' => $result['trend_score'],
                'cdr_bonus' => $cdr_bonus,
                'risk_reward' => $rr_score
            )
        );
    }
}

// Sort by score descending
$scores = array();
for ($i = 0; $i < count($all_picks); $i++) $scores[$i] = $all_picks[$i]['score'];
arsort($scores);
$sorted = array();
$rank = 0;
foreach ($scores as $idx => $val) {
    $rank++;
    $all_picks[$idx]['rank'] = $rank;
    $sorted[] = $all_picks[$idx];
}

// Save top picks to database
$saved = 0;
$today_date = date('Y-m-d');
$today_time = date('Y-m-d H:i:s');
foreach ($sorted as $p) {
    $safe_hash = $conn->real_escape_string($p['pick_hash']);
    $dup = $conn->query("SELECT id FROM miracle_picks3 WHERE pick_hash='$safe_hash'");
    if ($dup && $dup->num_rows > 0) continue;

    $st = $conn->real_escape_string($p['ticker']);
    $sn = $conn->real_escape_string($p['company_name']);
    $ss = $conn->real_escape_string($p['strategy']);
    $sc = $conn->real_escape_string($p['confidence']);
    $sj = $conn->real_escape_string(json_encode($p['signals']));

    $conn->query("INSERT INTO miracle_picks3 (ticker, company_name, strategy_name, scan_date, scan_time,
        entry_price, stop_loss_price, take_profit_price, stop_loss_pct, take_profit_pct,
        score, confidence, direction, signals_json, is_cdr, is_canadian,
        questrade_buy_fee, questrade_sell_fee, net_profit_if_tp, risk_reward_ratio, pick_hash)
        VALUES ('$st', '$sn', '$ss', '$today_date', '$today_time',
        {$p['entry_price']}, {$p['stop_loss_price']}, {$p['take_profit_price']}, {$p['sl_pct']}, {$p['tp_pct']},
        {$p['score']}, '$sc', '{$p['direction']}', '$sj', {$p['is_cdr']}, {$p['is_canadian']},
        " . round($p['questrade_roundtrip_fee'] / 2, 2) . ", " . round($p['questrade_roundtrip_fee'] / 2, 2) . ",
        {$p['net_profit_if_tp']}, {$p['risk_reward']}, '$safe_hash')");

    if (!$conn->error) $saved++;
}

$response['tickers_scanned'] = $scanned;
$response['picks_found'] = count($sorted);
$response['picks_saved'] = $saved;
$response['errors'] = $errors;
$response['top_picks'] = array_slice($sorted, 0, 15);

// Audit log
$ip = isset($_SERVER['REMOTE_ADDR']) ? $conn->real_escape_string($_SERVER['REMOTE_ADDR']) : 'unknown';
$conn->query("INSERT INTO miracle_audit3 (action_type, details, ip_address, created_at)
    VALUES ('scan', 'Scanned $scanned tickers, found " . count($sorted) . " picks, saved $saved', '$ip', '$today_time')");

echo json_encode($response);
$conn->close();
?>
