<?php
/**
 * Schema setup for DayTraders Miracle_CURSOR system (Claude-generated)
 * Creates all miracle3_ prefixed tables and seeds strategies/portfolios.
 * PHP 5.2 compatible.
 *
 * GENERATED BY: Claude (Anthropic) — DayTraders Miracle_CURSOR v3
 *
 * Usage: GET .../setup_schema3.php          -- create tables + seed
 *        GET .../setup_schema3.php?key=stocksrefresh2026  -- admin only in prod
 */
require_once dirname(__FILE__) . '/db_connect3.php';

$response = array('ok' => true, 'actions' => array());

// ── miracle_strategies3: Day trading strategy definitions ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_strategies3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    family VARCHAR(50) NOT NULL DEFAULT 'day_trade',
    description TEXT,
    scan_type VARCHAR(50) NOT NULL DEFAULT 'momentum',
    ideal_hold VARCHAR(20) NOT NULL DEFAULT '1d',
    default_tp_pct DECIMAL(5,2) NOT NULL DEFAULT 5.00,
    default_sl_pct DECIMAL(5,2) NOT NULL DEFAULT 3.00,
    min_score INT NOT NULL DEFAULT 50,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME,
    UNIQUE KEY idx_name (name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_strategies3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_picks3: Individual stock pick records with entry/SL/TP ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_picks3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    company_name VARCHAR(200) NOT NULL DEFAULT '',
    strategy_name VARCHAR(100) NOT NULL,
    scan_date DATE NOT NULL,
    scan_time DATETIME NOT NULL,
    entry_price DECIMAL(12,4) NOT NULL DEFAULT 0,
    stop_loss_price DECIMAL(12,4) NOT NULL DEFAULT 0,
    take_profit_price DECIMAL(12,4) NOT NULL DEFAULT 0,
    stop_loss_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    take_profit_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    score INT NOT NULL DEFAULT 0,
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium',
    direction VARCHAR(10) NOT NULL DEFAULT 'LONG',
    signals_json TEXT,
    is_cdr TINYINT NOT NULL DEFAULT 0,
    is_canadian TINYINT NOT NULL DEFAULT 0,
    questrade_buy_fee DECIMAL(8,2) NOT NULL DEFAULT 0,
    questrade_sell_fee DECIMAL(8,2) NOT NULL DEFAULT 0,
    net_profit_if_tp DECIMAL(12,2) NOT NULL DEFAULT 0,
    risk_reward_ratio DECIMAL(5,2) NOT NULL DEFAULT 0,
    outcome VARCHAR(20) NOT NULL DEFAULT 'pending',
    outcome_price DECIMAL(12,4) NOT NULL DEFAULT 0,
    outcome_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    outcome_date DATE,
    outcome_reason VARCHAR(50) NOT NULL DEFAULT '',
    pick_hash VARCHAR(64) NOT NULL DEFAULT '',
    KEY idx_ticker (ticker),
    KEY idx_strategy (strategy_name),
    KEY idx_date (scan_date),
    KEY idx_outcome (outcome),
    KEY idx_score (score),
    KEY idx_hash (pick_hash)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_picks3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_portfolios3: Portfolio templates with different risk profiles ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_portfolios3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    strategy_filter VARCHAR(500) NOT NULL DEFAULT '',
    initial_capital DECIMAL(12,2) NOT NULL DEFAULT 10000.00,
    position_size_pct DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    max_positions INT NOT NULL DEFAULT 5,
    fee_model VARCHAR(20) NOT NULL DEFAULT 'questrade',
    prefer_cdr TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    UNIQUE KEY idx_name (name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_portfolios3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_results3: Strategy/portfolio performance tracking ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_results3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    portfolio_id INT NOT NULL DEFAULT 0,
    strategy_name VARCHAR(100) NOT NULL DEFAULT '',
    period VARCHAR(20) NOT NULL DEFAULT 'daily',
    calc_date DATE NOT NULL,
    total_picks INT NOT NULL DEFAULT 0,
    winners INT NOT NULL DEFAULT 0,
    losers INT NOT NULL DEFAULT 0,
    pending_count INT NOT NULL DEFAULT 0,
    win_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
    avg_gain_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    avg_loss_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    total_pnl DECIMAL(12,2) NOT NULL DEFAULT 0,
    best_pick_ticker VARCHAR(10) NOT NULL DEFAULT '',
    best_pick_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    worst_pick_ticker VARCHAR(10) NOT NULL DEFAULT '',
    worst_pick_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    sharpe_ratio DECIMAL(10,4) NOT NULL DEFAULT 0,
    profit_factor DECIMAL(10,4) NOT NULL DEFAULT 0,
    expectancy DECIMAL(10,4) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    KEY idx_strategy (strategy_name),
    KEY idx_date (calc_date)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_results3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_watchlist3: Tickers to scan daily ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_watchlist3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    company_name VARCHAR(200) NOT NULL DEFAULT '',
    sector VARCHAR(50) NOT NULL DEFAULT '',
    is_cdr TINYINT NOT NULL DEFAULT 0,
    is_canadian TINYINT NOT NULL DEFAULT 0,
    reason TEXT,
    added_date DATE NOT NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'seed',
    active TINYINT NOT NULL DEFAULT 1,
    UNIQUE KEY idx_ticker (ticker)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_watchlist3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_learning3: Self-adjusting parameter history ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_learning3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    strategy_name VARCHAR(100) NOT NULL,
    param_name VARCHAR(50) NOT NULL,
    old_value DECIMAL(10,4) NOT NULL DEFAULT 0,
    new_value DECIMAL(10,4) NOT NULL DEFAULT 0,
    reason TEXT,
    backtest_win_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
    backtest_return_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
    applied_at DATETIME NOT NULL,
    KEY idx_strategy (strategy_name),
    KEY idx_date (applied_at)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_learning3: ' . ($conn->error ? $conn->error : 'OK');

// ── miracle_audit3: Action logging ──
$sql = "CREATE TABLE IF NOT EXISTS miracle_audit3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    action_type VARCHAR(50) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    KEY idx_action (action_type),
    KEY idx_date (created_at)
) ENGINE=MyISAM DEFAULT CHARSET=utf8";
$conn->query($sql);
$response['actions'][] = 'miracle_audit3: ' . ($conn->error ? $conn->error : 'OK');

// ═══════════════════════════════════════════════
// SEED STRATEGIES
// ═══════════════════════════════════════════════
$now = date('Y-m-d H:i:s');
$strategies = array(
    array('Gap Up Momentum', 'momentum', 'gap_up', 'Stocks gapping up >3% with 2x+ volume at open. Best in first 30 min of trading.', '1d', 8.00, 3.00, 60),
    array('Volume Surge Breakout', 'breakout', 'volume_surge', 'Unusual volume >3x 20-day avg with price breaking 20-day high. RSI < 80 filter.', '1d', 6.00, 3.00, 55),
    array('Oversold Bounce', 'reversal', 'oversold_bounce', 'RSI(14) < 30 + Bollinger lower band + reversal candle after 3+ red days.', '1-2d', 5.00, 3.00, 50),
    array('Momentum Continuation', 'momentum', 'momentum_cont', 'Strong uptrend pullback to SMA20 with bounce. All SMAs bullishly aligned.', '1-3d', 7.00, 3.50, 55),
    array('Earnings Catalyst Runner', 'catalyst', 'earnings_runner', 'Post-earnings gap >5% with 3x volume. PEAD effect exploitation.', '1-5d', 10.00, 4.00, 65),
    array('CDR Zero-Fee Priority', 'fee_optimized', 'cdr_priority', 'Any signal on CDR-available stocks. Zero commission = better risk/reward.', '1d', 5.00, 2.50, 45),
    array('Sector Momentum Leader', 'sector', 'sector_leader', 'Strongest sector + leading stock outperforming by >2%. Intraday persistence.', '1d', 5.00, 2.00, 50),
    array('Mean Reversion Sniper', 'reversal', 'mean_reversion', 'Z-score < -2 with SMA200 still rising. Targets return to mean.', '1-3d', 4.00, 2.50, 55)
);

foreach ($strategies as $s) {
    $sn = $conn->real_escape_string($s[0]);
    $sf = $conn->real_escape_string($s[1]);
    $st = $conn->real_escape_string($s[2]);
    $sd = $conn->real_escape_string($s[3]);
    $ih = $conn->real_escape_string($s[4]);
    $conn->query("INSERT INTO miracle_strategies3 (name, family, scan_type, description, ideal_hold, default_tp_pct, default_sl_pct, min_score, created_at)
                  VALUES ('$sn', '$sf', '$st', '$sd', '$ih', {$s[5]}, {$s[6]}, {$s[7]}, '$now')
                  ON DUPLICATE KEY UPDATE description='$sd', default_tp_pct={$s[5]}, default_sl_pct={$s[6]}");
}
$response['actions'][] = 'Seeded ' . count($strategies) . ' strategies';

// ═══════════════════════════════════════════════
// SEED PORTFOLIOS
// ═══════════════════════════════════════════════
$portfolios = array(
    array('Miracle Aggressive', 'High-risk day trades. All strategies, max 8 positions.', '', 10000, 12.5, 8, 'questrade', 1),
    array('Miracle Conservative', 'Lower-risk picks only. Score >= 70, CDR preferred.', 'cdr_priority,oversold_bounce,mean_reversion', 10000, 8.0, 4, 'questrade', 1),
    array('CDR Only Portfolio', 'Zero-fee trades only. CDR-available stocks exclusively.', 'cdr_priority', 10000, 10.0, 5, 'questrade', 1),
    array('Momentum Day Trader', 'Pure momentum plays. Gap ups and breakouts.', 'gap_up,volume_surge,momentum_cont', 10000, 10.0, 6, 'questrade', 0),
    array('Reversal Specialist', 'Oversold bounces and mean reversion only.', 'oversold_bounce,mean_reversion', 10000, 10.0, 4, 'questrade', 0),
    array('Catalyst Catcher', 'Earnings and sector momentum plays.', 'earnings_runner,sector_leader', 10000, 15.0, 3, 'questrade', 0)
);

foreach ($portfolios as $p) {
    $pn = $conn->real_escape_string($p[0]);
    $pd = $conn->real_escape_string($p[1]);
    $pf = $conn->real_escape_string($p[2]);
    $conn->query("INSERT INTO miracle_portfolios3 (name, description, strategy_filter, initial_capital, position_size_pct, max_positions, fee_model, prefer_cdr, created_at)
                  VALUES ('$pn', '$pd', '$pf', {$p[3]}, {$p[4]}, {$p[5]}, '{$p[6]}', {$p[7]}, '$now')
                  ON DUPLICATE KEY UPDATE description='$pd'");
}
$response['actions'][] = 'Seeded ' . count($portfolios) . ' portfolios';

// ═══════════════════════════════════════════════
// SEED WATCHLIST (CDR tickers + Blue Chips + ETFs)
// ═══════════════════════════════════════════════
$watchlist = array(
    // CDR tickers (zero fees on Questrade)
    array('AAPL', 'Apple Inc', 'Technology', 1, 0),
    array('AMD', 'Advanced Micro Devices', 'Technology', 1, 0),
    array('AMZN', 'Amazon.com Inc', 'Consumer', 1, 0),
    array('GOOG', 'Alphabet Inc', 'Technology', 1, 0),
    array('META', 'Meta Platforms', 'Technology', 1, 0),
    array('MSFT', 'Microsoft Corp', 'Technology', 1, 0),
    array('NFLX', 'Netflix Inc', 'Technology', 1, 0),
    array('NVDA', 'NVIDIA Corp', 'Technology', 1, 0),
    array('TSLA', 'Tesla Inc', 'Consumer', 1, 0),
    array('COST', 'Costco Wholesale', 'Consumer', 1, 0),
    array('DIS', 'Walt Disney Co', 'Consumer', 1, 0),
    array('HD', 'Home Depot', 'Consumer', 1, 0),
    array('MCD', 'McDonalds Corp', 'Consumer', 1, 0),
    array('NKE', 'Nike Inc', 'Consumer', 1, 0),
    array('SBUX', 'Starbucks Corp', 'Consumer', 1, 0),
    array('WMT', 'Walmart Inc', 'Consumer', 1, 0),
    array('ABBV', 'AbbVie Inc', 'Healthcare', 1, 0),
    array('JNJ', 'Johnson & Johnson', 'Healthcare', 1, 0),
    array('PFE', 'Pfizer Inc', 'Healthcare', 1, 0),
    array('UNH', 'UnitedHealth Group', 'Healthcare', 1, 0),
    array('BAC', 'Bank of America', 'Financials', 1, 0),
    array('JPM', 'JPMorgan Chase', 'Financials', 1, 0),
    array('MA', 'Mastercard Inc', 'Financials', 1, 0),
    array('V', 'Visa Inc', 'Financials', 1, 0),
    array('GS', 'Goldman Sachs', 'Financials', 1, 0),
    array('BA', 'Boeing Co', 'Industrials', 1, 0),
    array('CVX', 'Chevron Corp', 'Energy', 1, 0),
    array('XOM', 'Exxon Mobil', 'Energy', 1, 0),
    array('KO', 'Coca-Cola Co', 'Consumer', 1, 0),
    array('UBER', 'Uber Technologies', 'Technology', 1, 0),
    array('PYPL', 'PayPal Holdings', 'Financials', 1, 0),
    array('CRM', 'Salesforce Inc', 'Technology', 1, 0),
    array('INTC', 'Intel Corp', 'Technology', 1, 0),
    array('IBM', 'IBM Corp', 'Technology', 1, 0),
    array('CSCO', 'Cisco Systems', 'Technology', 1, 0),
    // High-volatility US stocks (no CDR — forex fee applies)
    array('PLTR', 'Palantir Technologies', 'Technology', 0, 0),
    array('SOFI', 'SoFi Technologies', 'Financials', 0, 0),
    array('ROKU', 'Roku Inc', 'Technology', 0, 0),
    array('SQ', 'Block Inc', 'Financials', 0, 0),
    array('SNAP', 'Snap Inc', 'Technology', 0, 0),
    array('COIN', 'Coinbase Global', 'Financials', 0, 0),
    array('MARA', 'Marathon Digital', 'Technology', 0, 0),
    array('RIOT', 'Riot Platforms', 'Technology', 0, 0),
    array('DKNG', 'DraftKings Inc', 'Consumer', 0, 0),
    array('SHOP', 'Shopify Inc', 'Technology', 0, 0),
    // Sector ETFs
    array('SPY', 'SPDR S&P 500 ETF', 'ETF', 0, 0),
    array('QQQ', 'Invesco QQQ Trust', 'ETF', 0, 0),
    array('XLK', 'Technology Select SPDR', 'ETF', 0, 0),
    array('XLF', 'Financial Select SPDR', 'ETF', 0, 0),
    array('XLE', 'Energy Select SPDR', 'ETF', 0, 0),
    array('XLV', 'Health Care Select SPDR', 'ETF', 0, 0),
    // Canadian high-volume
    array('SHOP.TO', 'Shopify (TSX)', 'Technology', 0, 1),
    array('RY.TO', 'Royal Bank of Canada', 'Financials', 0, 1),
    array('TD.TO', 'Toronto-Dominion Bank', 'Financials', 0, 1),
    array('ENB.TO', 'Enbridge Inc', 'Energy', 0, 1),
    array('CNR.TO', 'Canadian National Railway', 'Industrials', 0, 1)
);

$wl_added = 0;
foreach ($watchlist as $w) {
    $wt = $conn->real_escape_string($w[0]);
    $wn = $conn->real_escape_string($w[1]);
    $ws = $conn->real_escape_string($w[2]);
    $conn->query("INSERT INTO miracle_watchlist3 (ticker, company_name, sector, is_cdr, is_canadian, reason, added_date, source)
                  VALUES ('$wt', '$wn', '$ws', {$w[3]}, {$w[4]}, 'Initial seed', CURDATE(), 'seed')
                  ON DUPLICATE KEY UPDATE company_name='$wn', sector='$ws', is_cdr={$w[3]}, is_canadian={$w[4]}");
    $wl_added++;
}
$response['actions'][] = 'Seeded ' . $wl_added . ' watchlist tickers (' . count(array_filter($watchlist, create_function('$w', 'return $w[3]==1;'))) . ' CDR)';

// Log
$ip = isset($_SERVER['REMOTE_ADDR']) ? $conn->real_escape_string($_SERVER['REMOTE_ADDR']) : 'unknown';
$conn->query("INSERT INTO miracle_audit3 (action_type, details, ip_address, created_at) VALUES ('setup_schema', 'Tables created + seeded', '$ip', '$now')");

echo json_encode($response);
$conn->close();
?>
