"""Persona: Transaction Cost Researcher -- Slippage and market-impact modeling.

Part of Theme F from the hedge-fund-grade uplift plan.
Wires into: alpha_engine/execution_researcher

This researcher investigates the real-world cost of executing the picks
generated by the system.  The core question is: "After accounting for
spread, slippage, and market impact, does the alpha survive?"

Methodology:
1. Collect execution data (intended vs actual fill prices) from recent
   trades across all asset classes.
2. Fit market-impact models (square-root law, Almgren-Chriss) to the
   execution slippage.
3. Estimate all-in transaction cost per asset class and position size.
4. Backtest strategies with transaction costs applied to verify alpha
   persistence.
5. Recommend position-size caps per asset class based on liquidity.

Expected outputs:
- findings.md with cost estimates per asset class
- Market-impact model parameters
- Alpha persistence analysis (before vs after costs)
- Recommended position-size caps and execution timing rules
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

__all__ = ["TransactionCostResearcher"]


class TransactionCostResearcher:
    """Researcher persona for transaction cost analysis.

    Fills the execution-cost gap between theoretical backtests and live
    trading.  Production backtests currently ignore transaction costs;
    this researcher develops the evidence for applying realistic cost
    models that ensure promoted strategies survive in live execution.

    Attributes
    ----------
    PERSONA_ID : str
        Unique snake_case identifier for this persona.
    THEME : str
        Theme letter from the uplift plan.
    TARGET_MODULE : str
        Production module this research wires into.
    """

    PERSONA_ID = "transaction_cost"
    THEME = "F"
    TARGET_MODULE = "alpha_engine/execution_researcher"

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        """Initialise the researcher with configuration.

        Parameters
        ----------
        config : dict or None
            Research parameters.  Expected keys:
            - ``spread_lookup`` (dict): typical spread by asset class
            - ``impact_model`` (str): market impact model to fit
            - ``min_sample_size`` (int): minimum trades for reliable estimate
        """
        self.config = config or {}
        self.spread_lookup = self.config.get(
            "spread_lookup",
            {
                "crypto": 0.001,
                "equity": 0.0005,
                "forex": 0.0003,
                "commodity": 0.001,
                "bond": 0.0002,
                "etf": 0.0004,
                "futures": 0.0005,
            },
        )
        self.impact_model = self.config.get("impact_model", "square_root")
        self.min_sample_size = self.config.get("min_sample_size", 100)
        logger.info(
            "TransactionCostResearcher initialised (impact_model=%s, min_n=%d)",
            self.impact_model,
            self.min_sample_size,
        )

    def run_experiment(self, data: dict[str, Any]) -> dict[str, Any]:
        """Run the persona's core experiment. Returns findings dict.

        Parameters
        ----------
        data : dict
            Experiment data with keys:
            - ``fills_df`` (pd.DataFrame): execution records with intended/actual
            - ``position_sizes`` (pd.Series): dollar position per trade
            - ``strategies`` (pd.DataFrame): strategy backtest results

        Returns
        -------
        dict
            Findings with keys:
            - ``cost_by_asset_class`` (dict): mean all-in cost per class
            - ``impact_model_params`` (dict): fitted model parameters
            - ``alpha_persistence`` (float): Sharpe retention after costs
            - ``recommended_caps`` (dict): max position size per class
        """
        raise NotImplementedError("Subclasses must implement run_experiment")

    def generate_findings(self, data: dict[str, Any]) -> str:
        """Generate findings.md content. Returns markdown string.

        Parameters
        ----------
        data : dict
            Output from ``run_experiment``.

        Returns
        -------
        str
            Markdown-formatted findings document ready for commit.
        """
        raise NotImplementedError("Subclasses must implement generate_findings")

    def validate_for_production(self, findings: dict[str, Any]) -> tuple[bool, str]:
        """Check if findings meet production bar. Returns (bool, reason).

        A finding meets the production bar when:
        1. Alpha persistence after costs is >= 70% (Sharpe retention).
        2. Cost estimates are based on >= min_sample_size executions.
        3. All asset classes have a recommended position-size cap.

        Parameters
        ----------
        findings : dict
            Output from ``run_experiment".

        Returns
        -------
        tuple
            (passes: bool, reason: str)
        """
        raise NotImplementedError("Subclasses must implement validate_for_production")
