"""Seed strategies for the 4-island model.

Each island is seeded with proven high-WR strategies from the audit trail
and ALL_STRATEGIES.md, rather than random genes.
"""
from typing import List, Dict
try:
    from genome.dna_engine import StrategyDNA, create_strategy_dna, CombinationLogic
except ImportError:
    from dna_engine import StrategyDNA, create_strategy_dna, CombinationLogic

ISLAND_CONFIGS: Dict[str, dict] = {
    "bear": {
        "description": "Defensive/mean-reversion strategies for bear markets",
        "mutation_bias": "defensive",
        "seeds": [
            {
                "name": "vwap_sd_mean_reversion",
                "timeframe": "1h",
                "primary_indicator": "VWAP",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"rsi_period": 14, "rsi_oversold": 30, "rsi_overbought": 70,
                          "take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.72, "source": "alpha_engine"},
            },
            {
                "name": "connors_rsi2_crypto",
                "timeframe": "4h",
                "primary_indicator": "RSI",
                "entry_logic": "rsi_oversold",
                "exit_logic": "rsi_overbought",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 2, "rsi_oversold": 5, "rsi_overbought": 95,
                          "take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.625, "source": "alpha_engine"},
            },
            {
                "name": "funding_rate_carry",
                "timeframe": "4h",
                "primary_indicator": "Volume",
                "entry_logic": "funding_flip",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.5,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.60, "source": "alpha_engine"},
            },
            {
                "name": "corr_vwap_reversion",
                "timeframe": "30m",
                "primary_indicator": "VWAP",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 1.67, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.65, "source": "correlation_strategies"},
            },
            {
                "name": "corr_zscore_extreme",
                "timeframe": "30m",
                "primary_indicator": "Bollinger",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.62, "source": "correlation_strategies"},
            },
            {
                "name": "leap_swing_trail",
                "timeframe": "30m",
                "primary_indicator": "SMA",
                "entry_logic": "breakout",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 3.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.55, "source": "leap_strategies"},
            },
            {
                "name": "verified_stoch_rsi",
                "timeframe": "4h",
                "primary_indicator": "RSI",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"rsi_period": 14, "take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.78, "source": "verified_research"},
            },
            {
                "name": "verified_williams_r",
                "timeframe": "4h",
                "primary_indicator": "Volume",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.78, "source": "verified_research"},
            },
            {
                "name": "kimi_vpin_reversion",
                "timeframe": "4h",
                "primary_indicator": "VWAP",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.65, "source": "kimi_claw"},
            },
        ],
    },
    "bull": {
        "description": "Momentum/trend-following strategies for bull markets",
        "mutation_bias": "momentum",
        "seeds": [
            {
                "name": "rsi_macd_confluence",
                "timeframe": "4h",
                "primary_indicator": "MACD",
                "entry_logic": "macd_crossover",
                "exit_logic": "death_cross",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 14, "ema_fast": 12, "ema_slow": 26,
                          "take_profit_mult": 3.0, "stop_loss_mult": 1.5,
                          "position_size": 8, "leverage": 2,
                          "expected_wr": 0.65, "source": "alpha_engine"},
            },
            {
                "name": "multi_timeframe_ema_stack",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "death_cross",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 9, "ema_slow": 21, "atr_period": 14,
                          "take_profit_mult": 3.0, "stop_loss_mult": 1.5,
                          "position_size": 8, "leverage": 2,
                          "expected_wr": 0.68, "source": "alpha_engine"},
            },
            {
                "name": "hash_ribbon_buy",
                "timeframe": "1d",
                "primary_indicator": "SMA",
                "entry_logic": "golden_cross",
                "exit_logic": "trailing_stop",
                "risk_profile": "conservative",
                "genes": {"ema_fast": 30, "ema_slow": 60,
                          "take_profit_mult": 5.0, "stop_loss_mult": 2.0,
                          "position_size": 10, "leverage": 1,
                          "expected_wr": 0.78, "source": "alpha_engine_onchain"},
            },
            {
                "name": "corr_hma_trend",
                "timeframe": "30m",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "death_cross",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.60, "source": "correlation_strategies"},
            },
            {
                "name": "corr_triple_crown",
                "timeframe": "30m",
                "primary_indicator": "EMA",
                "entry_logic": "momentum",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.70, "source": "correlation_strategies"},
            },
            {
                "name": "leap_htf_momentum",
                "timeframe": "4h",
                "primary_indicator": "SMA",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "leap_strategies"},
            },
            {
                "name": "simpleton_trend_reversal",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "death_cross",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 21, "ema_slow": 55, "rsi_period": 14,
                          "rsi_overbought": 55, "rsi_oversold": 45, "atr_period": 14,
                          "take_profit_mult": 2.5, "stop_loss_mult": 1.5,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "pine_script_conversion"},
            },
            {
                "name": "mercury_vol_crossover",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 9, "ema_slow": 21, "rsi_period": 14,
                          "rsi_oversold": 30, "rsi_overbought": 70, "atr_period": 14,
                          "take_profit_mult": 4.0, "stop_loss_mult": 2.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.40, "source": "mercury_inceptionlabs"},
            },
            {
                "name": "mercury_aggressive",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "aggressive",
                "genes": {"ema_fast": 9, "ema_slow": 21, "rsi_period": 14,
                          "rsi_oversold": 35, "rsi_overbought": 65, "atr_period": 14,
                          "take_profit_mult": 4.5, "stop_loss_mult": 1.5,
                          "position_size": 10, "leverage": 2,
                          "expected_wr": 0.35, "source": "mercury_inceptionlabs"},
            },
            {
                "name": "mercury_hma_filtered",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 9, "ema_slow": 21, "rsi_period": 14,
                          "rsi_oversold": 30, "rsi_overbought": 70, "atr_period": 14,
                          "take_profit_mult": 4.0, "stop_loss_mult": 2.0,
                          "position_size": 8, "leverage": 1,
                          "secondary_indicator": "Volume",
                          "expected_wr": 0.47, "source": "mercury_hma_hull2005"},
            },
            {
                "name": "fr_mtf_aligned",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 21, "ema_slow": 55, "rsi_period": 14, "atr_period": 14,
                          "take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.60, "source": "fundedrelay_leap"},
            },
            {
                "name": "verified_supertrend_ai",
                "timeframe": "4h",
                "primary_indicator": "Bollinger",
                "entry_logic": "breakout",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"atr_period": 10, "take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.46, "source": "verified_research"},
            },
            {
                "name": "verified_ema_stack",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "death_cross",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 9, "ema_slow": 50, "take_profit_mult": 2.4,
                          "stop_loss_mult": 1.0, "position_size": 8, "leverage": 1,
                          "expected_wr": 0.59, "source": "verified_research"},
            },
            {
                "name": "academic_tsmom_28_5",
                "timeframe": "1d",
                "primary_indicator": "SMA",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "academic_tsmom"},
            },
            {
                "name": "kimi_ema600_40",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 40, "ema_slow": 150, "atr_period": 14,
                          "take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.55, "source": "kimi_claw"},
            },
        ],
    },
    "range": {
        "description": "Mean-reversion strategies for ranging/sideways markets",
        "mutation_bias": "mean_reversion",
        "seeds": [
            {
                "name": "keltner_mean_reversion",
                "timeframe": "4h",
                "primary_indicator": "Bollinger",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"atr_period": 20, "take_profit_mult": 2.0,
                          "stop_loss_mult": 1.2, "position_size": 5, "leverage": 1,
                          "expected_wr": 0.676, "source": "baby_strategies"},
            },
            {
                "name": "consecutive_down_rsi",
                "timeframe": "4h",
                "primary_indicator": "RSI",
                "entry_logic": "rsi_oversold",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"rsi_period": 2, "rsi_oversold": 10,
                          "take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.743, "source": "baby_strategies"},
            },
            {
                "name": "bollinger_mean_reversion",
                "timeframe": "1h",
                "primary_indicator": "Bollinger",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"rsi_period": 14, "take_profit_mult": 2.0,
                          "stop_loss_mult": 1.0, "position_size": 5, "leverage": 1,
                          "expected_wr": 0.607, "source": "baby_strategies"},
            },
            {
                "name": "corr_kama_adaptive",
                "timeframe": "30m",
                "primary_indicator": "EMA",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.62, "source": "correlation_strategies"},
            },
            {
                "name": "corr_vwap_zscore_reversion",
                "timeframe": "30m",
                "primary_indicator": "VWAP",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.64, "source": "correlation_strategies"},
            },
            {
                "name": "leap_fee_aware_sniper",
                "timeframe": "30m",
                "primary_indicator": "RSI",
                "entry_logic": "rsi_oversold",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 3.6, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.60, "source": "leap_strategies"},
            },
            {
                "name": "verified_keltner_breakout",
                "timeframe": "4h",
                "primary_indicator": "Bollinger",
                "entry_logic": "breakout",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"atr_period": 10, "take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.77, "source": "verified_research"},
            },
            {
                "name": "verified_wavetrend",
                "timeframe": "4h",
                "primary_indicator": "MACD",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.58, "source": "verified_research"},
            },
            {
                "name": "fr_liquidity_filtered",
                "timeframe": "4h",
                "primary_indicator": "Volume",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.4, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.58, "source": "fundedrelay_leap"},
            },
            {
                "name": "triple_confirmation",
                "timeframe": "1d",
                "primary_indicator": "Bollinger",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"rsi_period": 14, "atr_period": 14,
                          "take_profit_mult": 2.0, "stop_loss_mult": 1.5,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.60, "source": "kimi_agent_challenge"},
            },
        ],
    },
    "recent": {
        "description": "Ensemble/hybrid strategies for current market regime",
        "mutation_bias": "exploratory",
        "seeds": [
            {
                "name": "hmlf_ensemble_v1",
                "timeframe": "1h",
                "primary_indicator": "MACD",
                "entry_logic": "momentum",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 14, "ema_fast": 12, "ema_slow": 26,
                          "atr_period": 14, "take_profit_mult": 2.5,
                          "stop_loss_mult": 1.5, "position_size": 5, "leverage": 1,
                          "vote_threshold": 0.6, "regime_filter_len": 30,
                          "secondary_indicator": "Funding_Rate",
                          "expected_wr": 0.65, "source": "hmlf_design"},
            },
            {
                "name": "kalman_trend_reversion",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.5,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.62, "source": "forward_validated"},
            },
            {
                "name": "rsi_whaleconfirmed",
                "timeframe": "4h",
                "primary_indicator": "RSI",
                "entry_logic": "rsi_oversold",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 14, "take_profit_mult": 2.0,
                          "stop_loss_mult": 1.5, "position_size": 5, "leverage": 1,
                          "expected_wr": 0.649, "source": "forward_validated"},
            },
            {
                "name": "corr_hma_elton_confluence",
                "timeframe": "30m",
                "primary_indicator": "EMA",
                "entry_logic": "momentum",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.4, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.65, "source": "correlation_strategies"},
            },
            {
                "name": "leap_concentrated_rr",
                "timeframe": "30m",
                "primary_indicator": "Volume",
                "entry_logic": "breakout",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 3.3, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.55, "source": "leap_strategies"},
            },
            {
                "name": "leap_elliott_impulse",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "leap_strategies"},
            },
            {
                "name": "mercury_conservative",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "trailing_stop",
                "risk_profile": "conservative",
                "genes": {"ema_fast": 9, "ema_slow": 21, "rsi_period": 14,
                          "rsi_oversold": 20, "rsi_overbought": 80, "atr_period": 14,
                          "take_profit_mult": 4.5, "stop_loss_mult": 3.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.45, "source": "mercury_inceptionlabs"},
            },
            {
                "name": "simpleton_mercury_hybrid",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 21, "ema_slow": 55, "rsi_period": 14,
                          "rsi_oversold": 30, "rsi_overbought": 70, "atr_period": 14,
                          "take_profit_mult": 5.0, "stop_loss_mult": 2.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.43, "source": "fundedrelay_x_mercury"},
            },
            {
                "name": "mercury_funding_enhanced",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "golden_cross",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 9, "ema_slow": 21, "rsi_period": 14,
                          "rsi_oversold": 30, "rsi_overbought": 70, "atr_period": 14,
                          "take_profit_mult": 4.0, "stop_loss_mult": 2.0,
                          "position_size": 8, "leverage": 1,
                          "secondary_indicator": "Funding_Rate",
                          "expected_wr": 0.45, "source": "mercury_funding_carry"},
            },
            {
                "name": "fr_full_confluence",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "momentum",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 21, "ema_slow": 55, "rsi_period": 14, "atr_period": 14,
                          "take_profit_mult": 3.3, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.65, "source": "fundedrelay_leap"},
            },
            {
                "name": "verified_donchian_turtle",
                "timeframe": "4h",
                "primary_indicator": "Bollinger",
                "entry_logic": "breakout",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.55, "source": "verified_research"},
            },
            {
                "name": "risk_managed_momentum",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.4, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "academic_risk_managed"},
            },
            {
                "name": "kimi_lgbm_features",
                "timeframe": "4h",
                "primary_indicator": "MACD",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.4, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.60, "source": "kimi_claw"},
            },
            {
                "name": "kimi_vol_momentum_blend",
                "timeframe": "4h",
                "primary_indicator": "Volume",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.4, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.58, "source": "kimi_claw"},
            },
            {
                "name": "kimi_vpin_lgbm_ensemble",
                "timeframe": "4h",
                "primary_indicator": "VPIN",
                "entry_logic": "mean_reversion",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 3.0, "stop_loss_mult": 2.0,
                          "position_size": 6, "leverage": 1,
                          "expected_wr": 0.57, "source": "kimi_claw_ensemble"},
            },
            # Gemini Deep Research Championship Strategies (Mar 2026)
            {
                "name": "irb_hoffman",
                "timeframe": "1h",
                "primary_indicator": "EMA",
                "entry_logic": "breakout",
                "exit_logic": "trailing_stop",
                "risk_profile": "moderate",
                "genes": {"ema_fast": 5, "ema_slow": 20, "atr_period": 14,
                          "take_profit_mult": 1.5, "stop_loss_mult": 1.0,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.47, "source": "gemini_championship_hoffman"},
            },
            {
                "name": "fib_rsi_divergence",
                "timeframe": "1h",
                "primary_indicator": "RSI",
                "entry_logic": "mean_reversion",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 14, "take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 6, "leverage": 1,
                          "expected_wr": 0.33, "source": "gemini_championship_bellet"},
            },
            {
                "name": "protective_momentum",
                "timeframe": "1h",
                "primary_indicator": "MACD",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"rsi_period": 14, "ema_fast": 12, "ema_slow": 26,
                          "atr_period": 14, "take_profit_mult": 2.0,
                          "stop_loss_mult": 1.5, "position_size": 8, "leverage": 1,
                          "expected_wr": 0.48, "source": "gemini_championship_triton"},
            },
            # Alpha Arena Competition Strategies (Mar 2026)
            {
                "name": "alpha_aggressive_patience",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "trend_following",
                "exit_logic": "atr_based",
                "risk_profile": "aggressive",
                "genes": {"take_profit_mult": 3.0, "stop_loss_mult": 2.0,
                          "position_size": 10, "leverage": 1,
                          "expected_wr": 0.30, "source": "alpha_arena_qwen"},
            },
            {
                "name": "alpha_four_layer",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "confluence",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.5,
                          "position_size": 6, "leverage": 1,
                          "expected_wr": 0.55, "source": "alpha_arena_unified"},
            },
            {
                "name": "alpha_regime_switcher",
                "timeframe": "4h",
                "primary_indicator": "ADX",
                "entry_logic": "regime_adaptive",
                "exit_logic": "take_profit",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.5, "stop_loss_mult": 1.0,
                          "position_size": 7, "leverage": 1,
                          "expected_wr": 0.50, "source": "alpha_arena_deepseek"},
            },
            {
                "name": "alpha_risk_parity",
                "timeframe": "4h",
                "primary_indicator": "Volatility",
                "entry_logic": "momentum",
                "exit_logic": "take_profit",
                "risk_profile": "conservative",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.0,
                          "position_size": 5, "leverage": 1,
                          "expected_wr": 0.52, "source": "alpha_arena_deepseek"},
            },
            {
                "name": "alpha_drawdown_responsive",
                "timeframe": "4h",
                "primary_indicator": "Momentum",
                "entry_logic": "momentum",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 2.0, "stop_loss_mult": 1.5,
                          "position_size": 6, "leverage": 1,
                          "expected_wr": 0.48, "source": "alpha_arena_dual"},
            },
            # Hoffman IRB + EMA Angle Strategies (Mar 2026) — 3 hold-time variants
            {
                "name": "hoffman_irb_1h",
                "timeframe": "15m",
                "primary_indicator": "EMA",
                "entry_logic": "irb_dip_buy",
                "exit_logic": "atr_based",
                "risk_profile": "aggressive",
                "genes": {"ema_period": 20, "atr_period": 14,
                          "take_profit_mult": 1.0, "stop_loss_mult": 0.75,
                          "position_size": 8, "leverage": 1,
                          "expected_wr": 0.50, "source": "hoffman_irb_ema_angle"},
            },
            {
                "name": "hoffman_irb_2h",
                "timeframe": "15m",
                "primary_indicator": "EMA",
                "entry_logic": "irb_dip_buy",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"ema_period": 20, "atr_period": 14,
                          "take_profit_mult": 1.25, "stop_loss_mult": 1.0,
                          "position_size": 7, "leverage": 1,
                          "expected_wr": 0.52, "source": "hoffman_irb_ema_angle"},
            },
            {
                "name": "hoffman_irb_4h",
                "timeframe": "15m",
                "primary_indicator": "EMA",
                "entry_logic": "irb_dip_buy",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"ema_period": 20, "atr_period": 14,
                          "take_profit_mult": 1.5, "stop_loss_mult": 1.0,
                          "position_size": 6, "leverage": 1,
                          "expected_wr": 0.53, "source": "hoffman_irb_ema_angle"},
            },
            {
                "name": "alpha_partial_scaleout",
                "timeframe": "4h",
                "primary_indicator": "EMA",
                "entry_logic": "trend_following",
                "exit_logic": "atr_based",
                "risk_profile": "moderate",
                "genes": {"take_profit_mult": 3.0, "stop_loss_mult": 1.0,
                          "position_size": 7, "leverage": 1,
                          "expected_wr": 0.50, "source": "alpha_arena_qwen"},
            },
        ],
    },
}


def get_island_seeds(island_name: str) -> List[StrategyDNA]:
    """Create StrategyDNA objects from seed definitions for a given island."""
    config = ISLAND_CONFIGS[island_name]
    strategies = []
    for seed in config["seeds"]:
        extra_genes = seed.get("genes", {})
        dna = create_strategy_dna(
            name=seed["name"],
            timeframe=seed["timeframe"],
            primary_indicator=seed["primary_indicator"],
            entry_logic=seed["entry_logic"],
            exit_logic=seed["exit_logic"],
            risk_profile=seed["risk_profile"],
            **extra_genes,
        )
        strategies.append(dna)
    return strategies


def get_all_island_seeds() -> Dict[str, List[StrategyDNA]]:
    """Return seed populations for all 4 islands."""
    return {name: get_island_seeds(name) for name in ISLAND_CONFIGS}
