"""Meta-Strategy Permutation Engine — SQLite persistence layer.

Tables:
  permutations     — Every combo definition (systems, logic, weights)
  permutation_signals — Signals generated by each permutation
  permutation_results — Backtest metrics per permutation×symbol
  live_performance   — Paper-traded P&L tracking ($1000 portfolio)
  elimination_log    — Why and when combos were eliminated/resurrected
"""
import sqlite3
import json
from pathlib import Path
from datetime import datetime, timezone

DB_PATH = Path(__file__).parent / "data" / "meta_strategy.db"


def get_db() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    _create_tables(conn)
    return conn


def _create_tables(conn: sqlite3.Connection) -> None:
    conn.executescript("""
        -- Every permutation we've ever tested
        CREATE TABLE IF NOT EXISTS permutations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT UNIQUE NOT NULL,          -- e.g. "mercury2+alpha_engine|majority"
            systems TEXT NOT NULL,                   -- JSON list of system_ids
            logic_type TEXT NOT NULL DEFAULT 'majority',  -- majority, unanimous, weighted, cascade, inverse
            weights TEXT,                             -- JSON dict of system weights (null = equal)
            min_agreement INTEGER DEFAULT 2,          -- minimum systems that must agree
            parameters TEXT,                          -- JSON extra params (thresholds, lookback, etc.)
            status TEXT DEFAULT 'ACTIVE',              -- ACTIVE, ELIMINATED, PROBATION, RETIRED, RESURRECTED
            created_at TEXT NOT NULL,
            eliminated_at TEXT,
            elimination_reason TEXT,
            resurrection_count INTEGER DEFAULT 0,
            consecutive_failures INTEGER DEFAULT 0,
            max_failures_before_elimination INTEGER DEFAULT 5
        );

        -- Signals generated by each permutation (for forward-test tracking)
        CREATE TABLE IF NOT EXISTS permutation_signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            symbol TEXT NOT NULL,
            direction TEXT NOT NULL,                   -- BUY or SELL
            confidence REAL DEFAULT 0.5,
            entry_price REAL,
            take_profit REAL,
            stop_loss REAL,
            timestamp TEXT NOT NULL,
            source_signals TEXT,                        -- JSON: which system signals contributed
            status TEXT DEFAULT 'OPEN',                 -- OPEN, TP_HIT, SL_HIT, EXPIRED, CLOSED
            exit_price REAL,
            exit_timestamp TEXT,
            pnl_pct REAL,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id)
        );

        -- Backtest results per permutation x symbol
        CREATE TABLE IF NOT EXISTS permutation_results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            symbol TEXT,                                -- NULL = all symbols aggregate
            total_trades INTEGER NOT NULL DEFAULT 0,
            wins INTEGER NOT NULL DEFAULT 0,
            losses INTEGER NOT NULL DEFAULT 0,
            win_rate REAL DEFAULT 0.0,
            avg_pnl_pct REAL DEFAULT 0.0,
            total_pnl_pct REAL DEFAULT 0.0,
            sharpe REAL DEFAULT 0.0,
            sortino REAL DEFAULT 0.0,
            max_drawdown_pct REAL DEFAULT 0.0,
            profit_factor REAL DEFAULT 0.0,
            p_value REAL DEFAULT 1.0,
            kelly_pct REAL DEFAULT 0.0,
            portfolio_final REAL DEFAULT 1000.0,        -- paper portfolio value
            portfolio_return_pct REAL DEFAULT 0.0,
            is_significant INTEGER DEFAULT 0,
            is_winner INTEGER DEFAULT 0,
            failure_reason TEXT,
            eval_period TEXT,                            -- e.g. "2026-02-15_to_2026-03-02"
            last_updated TEXT NOT NULL,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id)
        );

        -- Live paper-trading portfolio tracking
        CREATE TABLE IF NOT EXISTS live_performance (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            date TEXT NOT NULL,                         -- YYYY-MM-DD
            portfolio_value REAL NOT NULL DEFAULT 1000.0,
            daily_pnl_pct REAL DEFAULT 0.0,
            cumulative_pnl_pct REAL DEFAULT 0.0,
            open_positions INTEGER DEFAULT 0,
            trades_today INTEGER DEFAULT 0,
            wins_today INTEGER DEFAULT 0,
            max_drawdown_pct REAL DEFAULT 0.0,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id),
            UNIQUE(combo_id, date)
        );

        -- Elimination / resurrection audit log
        CREATE TABLE IF NOT EXISTS elimination_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            action TEXT NOT NULL,                       -- ELIMINATED, PROBATION, RESURRECTED, PROMOTED, PHOENIX
            reason TEXT,
            metrics_at_action TEXT,                     -- JSON snapshot of metrics when action taken
            failure_signature TEXT,                     -- JSON: classified failure type + conditions
            timestamp TEXT NOT NULL,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id)
        );

        -- Walk-forward validation results
        CREATE TABLE IF NOT EXISTS walkforward_results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            fold_number INTEGER NOT NULL,
            train_start TEXT NOT NULL,
            train_end TEXT NOT NULL,
            test_start TEXT NOT NULL,
            test_end TEXT NOT NULL,
            train_sharpe REAL DEFAULT 0.0,
            test_sharpe REAL DEFAULT 0.0,
            train_wr REAL DEFAULT 0.0,
            test_wr REAL DEFAULT 0.0,
            train_trades INTEGER DEFAULT 0,
            test_trades INTEGER DEFAULT 0,
            oos_degradation_pct REAL DEFAULT 0.0,       -- (train_sharpe - test_sharpe) / train_sharpe * 100
            is_robust INTEGER DEFAULT 0,                 -- test_sharpe > 0 and degradation < 50%
            timestamp TEXT NOT NULL,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id)
        );

        -- Adversarial compatibility matrix
        CREATE TABLE IF NOT EXISTS adversarial_compat (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            combo_id TEXT NOT NULL,
            system_a TEXT NOT NULL,
            system_b TEXT NOT NULL,
            correlation REAL DEFAULT 0.0,                -- return correlation
            failure_overlap_pct REAL DEFAULT 0.0,        -- % of time both fail simultaneously
            diversification_score REAL DEFAULT 0.0,      -- 1 - failure_overlap (higher = better)
            timestamp TEXT NOT NULL,
            FOREIGN KEY (combo_id) REFERENCES permutations(combo_id)
        );

        -- Indexes for performance
        CREATE INDEX IF NOT EXISTS idx_perm_status ON permutations(status);
        CREATE INDEX IF NOT EXISTS idx_perm_combo ON permutations(combo_id);
        CREATE INDEX IF NOT EXISTS idx_psig_combo ON permutation_signals(combo_id);
        CREATE INDEX IF NOT EXISTS idx_psig_status ON permutation_signals(status);
        CREATE INDEX IF NOT EXISTS idx_psig_symbol ON permutation_signals(symbol);
        CREATE INDEX IF NOT EXISTS idx_pres_combo ON permutation_results(combo_id);
        CREATE INDEX IF NOT EXISTS idx_pres_winner ON permutation_results(is_winner);
        CREATE INDEX IF NOT EXISTS idx_live_combo ON live_performance(combo_id);
        CREATE INDEX IF NOT EXISTS idx_elog_combo ON elimination_log(combo_id);
        CREATE INDEX IF NOT EXISTS idx_wf_combo ON walkforward_results(combo_id);
        CREATE INDEX IF NOT EXISTS idx_wf_robust ON walkforward_results(is_robust);
        CREATE INDEX IF NOT EXISTS idx_adv_combo ON adversarial_compat(combo_id);
    """)

    # Migrations: add columns that may be missing from older DBs
    for col, col_type in [
        ("failure_signature", "TEXT"),
        ("metrics_at_action", "TEXT"),
    ]:
        try:
            conn.execute(f"ALTER TABLE elimination_log ADD COLUMN {col} {col_type}")
        except sqlite3.OperationalError:
            pass  # column already exists

    conn.commit()


def register_permutation(conn, combo_id: str, systems: list, logic_type: str = "majority",
                          weights: dict = None, min_agreement: int = 2,
                          parameters: dict = None) -> None:
    """Register a new permutation (skip if exists)."""
    now = datetime.now(timezone.utc).isoformat()
    try:
        conn.execute("""
            INSERT OR IGNORE INTO permutations
                (combo_id, systems, logic_type, weights, min_agreement, parameters, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (combo_id, json.dumps(systems), logic_type,
              json.dumps(weights) if weights else None,
              min_agreement,
              json.dumps(parameters) if parameters else None,
              now))
        conn.commit()
    except Exception:
        pass


def save_result(conn, combo_id: str, symbol: str, metrics: dict) -> None:
    """Save or update backtest result for a permutation."""
    now = datetime.now(timezone.utc).isoformat()
    conn.execute("""
        INSERT OR REPLACE INTO permutation_results
            (combo_id, symbol, total_trades, wins, losses, win_rate,
             avg_pnl_pct, total_pnl_pct, sharpe, sortino, max_drawdown_pct,
             profit_factor, p_value, kelly_pct, portfolio_final,
             portfolio_return_pct, is_significant, is_winner,
             failure_reason, eval_period, last_updated)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (combo_id, symbol,
          metrics.get("total_trades", 0),
          metrics.get("wins", 0),
          metrics.get("losses", 0),
          metrics.get("win_rate", 0),
          metrics.get("avg_pnl_pct", 0),
          metrics.get("total_pnl_pct", 0),
          metrics.get("sharpe", 0),
          metrics.get("sortino", 0),
          metrics.get("max_drawdown_pct", 0),
          metrics.get("profit_factor", 0),
          metrics.get("p_value", 1.0),
          metrics.get("kelly_pct", 0),
          metrics.get("portfolio_final", 1000),
          metrics.get("portfolio_return_pct", 0),
          1 if metrics.get("is_significant") else 0,
          1 if metrics.get("is_winner") else 0,
          metrics.get("failure_reason"),
          metrics.get("eval_period", ""),
          now))
    conn.commit()


def log_signal(conn, combo_id: str, symbol: str, direction: str,
               confidence: float, entry_price: float,
               tp: float, sl: float, source_signals: dict) -> int:
    """Log a signal from a permutation."""
    now = datetime.now(timezone.utc).isoformat()
    cur = conn.execute("""
        INSERT INTO permutation_signals
            (combo_id, symbol, direction, confidence, entry_price,
             take_profit, stop_loss, timestamp, source_signals)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (combo_id, symbol, direction, confidence, entry_price,
          tp, sl, now, json.dumps(source_signals)))
    conn.commit()
    return cur.lastrowid


def resolve_signal(conn, signal_id: int, status: str,
                   exit_price: float, pnl_pct: float) -> None:
    """Close a signal with outcome."""
    now = datetime.now(timezone.utc).isoformat()
    conn.execute("""
        UPDATE permutation_signals
        SET status = ?, exit_price = ?, exit_timestamp = ?, pnl_pct = ?
        WHERE id = ?
    """, (status, exit_price, now, pnl_pct, signal_id))
    conn.commit()


def eliminate_combo(conn, combo_id: str, reason: str, metrics: dict = None) -> None:
    """Eliminate a permutation."""
    now = datetime.now(timezone.utc).isoformat()
    conn.execute("""
        UPDATE permutations SET status = 'ELIMINATED', eliminated_at = ?,
            elimination_reason = ?
        WHERE combo_id = ?
    """, (now, reason, combo_id))
    conn.execute("""
        INSERT INTO elimination_log (combo_id, action, reason, metrics_at_action, timestamp)
        VALUES (?, 'ELIMINATED', ?, ?, ?)
    """, (combo_id, reason, json.dumps(metrics) if metrics else None, now))
    conn.commit()


def resurrect_combo(conn, combo_id: str, reason: str) -> None:
    """Resurrect an eliminated permutation."""
    now = datetime.now(timezone.utc).isoformat()
    conn.execute("""
        UPDATE permutations SET status = 'RESURRECTED', eliminated_at = NULL,
            elimination_reason = NULL,
            resurrection_count = resurrection_count + 1,
            consecutive_failures = 0
        WHERE combo_id = ?
    """, (combo_id,))
    conn.execute("""
        INSERT INTO elimination_log (combo_id, action, reason, timestamp)
        VALUES (?, 'RESURRECTED', ?, ?)
    """, (combo_id, reason, now))
    conn.commit()


def save_walkforward_result(conn, combo_id: str, fold: int,
                            train_start: str, train_end: str,
                            test_start: str, test_end: str,
                            train_metrics: dict, test_metrics: dict) -> None:
    """Save a walk-forward validation fold result."""
    now = datetime.now(timezone.utc).isoformat()
    train_sharpe = train_metrics.get("sharpe", 0)
    test_sharpe = test_metrics.get("sharpe", 0)
    degradation = 0.0
    if train_sharpe > 0:
        degradation = (train_sharpe - test_sharpe) / train_sharpe * 100
    is_robust = 1 if test_sharpe > 0 and degradation < 50 else 0

    conn.execute("""
        INSERT INTO walkforward_results
            (combo_id, fold_number, train_start, train_end,
             test_start, test_end, train_sharpe, test_sharpe,
             train_wr, test_wr, train_trades, test_trades,
             oos_degradation_pct, is_robust, timestamp)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (combo_id, fold, train_start, train_end, test_start, test_end,
          train_sharpe, test_sharpe,
          train_metrics.get("win_rate", 0), test_metrics.get("win_rate", 0),
          train_metrics.get("total_trades", 0), test_metrics.get("total_trades", 0),
          round(degradation, 2), is_robust, now))
    conn.commit()


def save_adversarial_compat(conn, combo_id: str, sys_a: str, sys_b: str,
                            correlation: float, failure_overlap: float) -> None:
    """Save adversarial compatibility between two systems in a combo."""
    now = datetime.now(timezone.utc).isoformat()
    conn.execute("""
        INSERT OR REPLACE INTO adversarial_compat
            (combo_id, system_a, system_b, correlation,
             failure_overlap_pct, diversification_score, timestamp)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (combo_id, sys_a, sys_b, round(correlation, 4),
          round(failure_overlap, 4), round(1 - failure_overlap, 4), now))
    conn.commit()


def get_active_permutations(conn) -> list:
    """Get all active/resurrected permutations."""
    rows = conn.execute("""
        SELECT * FROM permutations
        WHERE status IN ('ACTIVE', 'RESURRECTED', 'PROBATION')
        ORDER BY combo_id
    """).fetchall()
    return [dict(r) for r in rows]


def get_winners(conn, min_sharpe: float = 0.5, min_trades: int = 5) -> list:
    """Get winning permutations."""
    rows = conn.execute("""
        SELECT pr.*, p.systems, p.logic_type, p.status
        FROM permutation_results pr
        JOIN permutations p ON p.combo_id = pr.combo_id
        WHERE pr.is_winner = 1
          AND pr.total_trades >= ?
          AND pr.sharpe >= ?
        ORDER BY pr.sharpe DESC
    """, (min_trades, min_sharpe)).fetchall()
    return [dict(r) for r in rows]
