"""
Swarm Edge Auditor — Async hierarchical swarm for edge auditing.

Architecture
------------
1. **BlackboardMemory** — shared mutable state (the *blackboard*).
2. **BaseAgent** — abstract async agent interface.
3. **MySQLPickDataAgent** — loads raw picks from MySQL into the blackboard.
4. **StatisticalEdgeCalculatorAgent** — runs edge metrics on the blackboard picks.
5. **OptimizationCriticAgent** — flags weak/no-edge asset classes.
6. **SwarmEdgeAuditor** — orchestrator that wires agents and runs them sequentially.

Typical usage::

    from swarm_edge_auditor import SwarmEdgeAuditor

    auditor = SwarmEdgeAuditor()
    report = await auditor.run_full_audit()
    print(report)
"""

from __future__ import annotations

import asyncio
import json
import logging
import textwrap
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from mysql_pick_adapter import MySQLPickAdapter
from statistical_edge_engine import (
    ConcentrationMetrics,
    EdgeMetrics,
    StatisticalEdgeEngine,
)

logger = logging.getLogger("swarm.auditor")


# ---------------------------------------------------------------------------
# Shared blackboard state
# ---------------------------------------------------------------------------

@dataclass
class BlackboardMemory:
    """Central shared state (blackboard) consumed / produced by all agents.

    Attributes
    ----------
    raw_picks:
        Unprocessed pick dictionaries straight from the DB / JSON fallback.
    metrics_per_class:
        Mapping ``asset_class → EdgeMetrics`` populated by the
        *StatisticalEdgeCalculatorAgent*.
    portfolio_metrics:
        Aggregate :class:`~statistical_edge_engine.EdgeMetrics` for the
        whole portfolio.
    concentration:
        :class:`~statistical_edge_engine.ConcentrationMetrics`.
    degradation_alerts:
        List of alert dicts produced by the *OptimizationCriticAgent*.
    enhancement_suggestions:
        Free-text recommendations generated by the critic.
    system_status:
        Overall swarm status: ``HEALTHY``, ``DEGRADED``, or ``CRITICAL``.
    audit_timestamp:
        ISO-8601 UTC timestamp set when the audit begins.
    metadata:
        Arbitrary key/value pairs for cross-agent communication.
    """

    raw_picks: List[Dict[str, Any]] = field(default_factory=list)
    metrics_per_class: Dict[str, EdgeMetrics] = field(default_factory=dict)
    portfolio_metrics: Optional[EdgeMetrics] = None
    concentration: Optional[ConcentrationMetrics] = None
    degradation_alerts: List[Dict[str, Any]] = field(default_factory=list)
    enhancement_suggestions: List[str] = field(default_factory=list)
    system_status: str = "PENDING"
    audit_timestamp: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the blackboard to a JSON-compatible dictionary."""
        return {
            "audit_timestamp": self.audit_timestamp,
            "system_status": self.system_status,
            "raw_picks_count": len(self.raw_picks),
            "metrics_per_class": {
                k: v.to_dict() for k, v in self.metrics_per_class.items()
            },
            "portfolio_metrics": (
                self.portfolio_metrics.to_dict()
                if self.portfolio_metrics is not None
                else None
            ),
            "concentration": (
                self.concentration.to_dict()
                if self.concentration is not None
                else None
            ),
            "degradation_alerts": self.degradation_alerts,
            "enhancement_suggestions": self.enhancement_suggestions,
            "metadata": self.metadata,
        }


# ---------------------------------------------------------------------------
# Abstract agent
# ---------------------------------------------------------------------------

class BaseAgent(ABC):
    """Abstract base for every agent in the swarm.

    Subclasses must implement ``execute`` and should read / mutate the
    provided :class:`BlackboardMemory` in-place.

    Parameters
    ----------
    name:
        Human-readable agent identifier (used in logging and reports).
    """

    def __init__(self, name: str) -> None:
        self.name: str = name

    @abstractmethod
    async def execute(self, blackboard: BlackboardMemory) -> None:
        """Run the agent's logic against *blackboard*.

        Parameters
        ----------
        blackboard:
            The shared state object.  Implementations may read **and**
            write this structure.
        """
        ...

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r})"


# ---------------------------------------------------------------------------
# Concrete agents
# ---------------------------------------------------------------------------

class MySQLPickDataAgent(BaseAgent):
    """Agent that hydrates the blackboard with raw picks from MySQL.

    If the database is unreachable the adapter automatically falls back
    to a local JSON cache file.

    Parameters
    ----------
    adapter:
        An instance of :class:`mysql_pick_adapter.MySQLPickAdapter`.
        When *None* a default adapter is constructed.
    """

    def __init__(
        self,
        adapter: Optional[MySQLPickAdapter] = None,
    ) -> None:
        super().__init__(name="MySQLPickDataAgent")
        self._adapter: MySQLPickAdapter = adapter or MySQLPickAdapter()

    async def execute(self, blackboard: BlackboardMemory) -> None:
        """Load closed picks from MySQL into ``blackboard.raw_picks``."""
        logger.info("[%s] Fetching picks from MySQL…", self.name)
        try:
            # Offload blocking DB I/O to a thread
            picks: List[Dict[str, Any]] = await asyncio.to_thread(
                self._adapter.fetch_picks
            )
            if not picks:
                logger.warning("[%s] No picks returned from DB — trying JSON fallback", self.name)
                picks = await asyncio.to_thread(
                    self._adapter.fetch_all_closed
                )
            blackboard.raw_picks = picks
            logger.info("[%s] Loaded %d pick(s)", self.name, len(picks))
        except Exception as exc:  # noqa: BLE001
            logger.error("[%s] Failed to load picks: %s", self.name, exc)
            blackboard.raw_picks = []
            blackboard.system_status = "DEGRADED"
            blackboard.metadata["data_agent_error"] = str(exc)


class StatisticalEdgeCalculatorAgent(BaseAgent):
    """Agent that runs the statistical edge engine over the blackboard picks.

    Populates ``blackboard.metrics_per_class``,
    ``blackboard.portfolio_metrics``, and
    ``blackboard.concentration``.
    """

    def __init__(self) -> None:
        super().__init__(name="StatisticalEdgeCalculatorAgent")

    async def execute(self, blackboard: BlackboardMemory) -> None:
        """Compute edge metrics and concentration indices."""
        logger.info("[%s] Computing edge metrics…", self.name)

        if not blackboard.raw_picks:
            logger.warning("[%s] No raw picks to analyse", self.name)
            blackboard.system_status = "DEGRADED"
            return

        engine = StatisticalEdgeEngine(blackboard.raw_picks)

        # Run blocking calculations in a thread
        blackboard.metrics_per_class = await asyncio.to_thread(
            engine.compute_all_metrics
        )
        blackboard.portfolio_metrics = await asyncio.to_thread(
            engine.compute_portfolio_metrics
        )
        blackboard.concentration = await asyncio.to_thread(
            engine.compute_concentration_index
        )

        pm = blackboard.portfolio_metrics
        logger.info(
            "[%s] Portfolio — trades=%d EV=%.4f PF=%.4f status=%s",
            self.name,
            pm.total_trades,
            pm.expected_value,
            pm.profit_factor,
            pm.status_assessment,
        )


class OptimizationCriticAgent(BaseAgent):
    """Agent that critiques edge quality and produces improvement suggestions.

    Writes to ``blackboard.degradation_alerts`` and
    ``blackboard.enhancement_suggestions``.
    """

    def __init__(
        self,
        ev_threshold: float = 0.005,
    ) -> None:
        super().__init__(name="OptimizationCriticAgent")
        self._ev_threshold: float = ev_threshold

    async def execute(self, blackboard: BlackboardMemory) -> None:
        """Flag weak/no-edge asset classes and generate recommendations."""
        logger.info("[%s] Running optimization critique…", self.name)

        if not blackboard.raw_picks:
            blackboard.enhancement_suggestions.append(
                "No pick data available — cannot perform edge critique."
            )
            blackboard.system_status = "CRITICAL"
            return

        engine = StatisticalEdgeEngine(blackboard.raw_picks)

        # Degradation alerts
        alerts: List[Dict[str, Any]] = await asyncio.to_thread(
            engine.alert_on_degradation, self._ev_threshold
        )
        blackboard.degradation_alerts = alerts

        # Build enhancement suggestions
        suggestions: List[str] = []
        metrics = blackboard.metrics_per_class

        for ac, em in metrics.items():
            if em.status_assessment == "NO_EDGE":
                suggestions.append(
                    f"**{ac}** — edge has vanished (EV={em.expected_value:.4f}). "
                    f"Consider halting new trades in this asset class and reviewing model inputs."
                )
            elif em.status_assessment == "WEAK_EDGE":
                suggestions.append(
                    f"**{ac}** — weak edge detected (EV={em.expected_value:.4f}, "
                    f"PF={em.profit_factor:.2f}).  Recommend: reduce position sizing by 30%% "
                    f"or tighten SL criteria."
                )
            elif em.kelly_fraction < 0.05:
                suggestions.append(
                    f"**{ac}** — Kelly fraction is very low ({em.kelly_fraction:.4f}). "
                    f"Position sizing may be too conservative; review risk parameters."
                )

        # Concentration warning
        if blackboard.concentration is not None:
            hhi = blackboard.concentration.herfindahl_index
            if hhi > 0.5:
                suggestions.append(
                    f"Portfolio is highly concentrated (HHI={hhi:.4f}). "
                    "Diversify across additional asset classes to reduce drawdown risk."
                )
            elif hhi < 0.15:
                suggestions.append(
                    f"Portfolio is overly diversified (HHI={hhi:.4f}). "
                    "Concentrate on the 2-3 strongest asset classes to maximise edge."
                )

        blackboard.enhancement_suggestions = suggestions

        # Derive overall system status
        if any(a["severity"] == "critical" for a in alerts):
            blackboard.system_status = "CRITICAL"
        elif alerts:
            blackboard.system_status = "DEGRADED"
        else:
            blackboard.system_status = "HEALTHY"

        logger.info(
            "[%s] Alerts=%d Suggestions=%d Status=%s",
            self.name,
            len(alerts),
            len(suggestions),
            blackboard.system_status,
        )


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

class SwarmEdgeAuditor:
    """Sequential swarm orchestrator for the full edge-audit pipeline.

    Agents are executed in registration order::

        1. MySQLPickDataAgent          — load picks
        2. StatisticalEdgeCalculatorAgent — compute metrics
        3. OptimizationCriticAgent     — critique & recommend

    Parameters
    ----------
    adapter:
        Optional pre-configured :class:`mysql_pick_adapter.MySQLPickAdapter`.
    ev_threshold:
        Expected-value threshold passed to the critic agent.
    """

    def __init__(
        self,
        adapter: Optional[MySQLPickAdapter] = None,
        ev_threshold: float = 0.005,
    ) -> None:
        self._agents: List[BaseAgent] = []
        self._adapter: Optional[MySQLPickAdapter] = adapter
        self._ev_threshold: float = ev_threshold

        # Register default agents
        self.register(MySQLPickDataAgent(adapter=adapter))
        self.register(StatisticalEdgeCalculatorAgent())
        self.register(OptimizationCriticAgent(ev_threshold=ev_threshold))

    def register(self, agent: BaseAgent) -> None:
        """Add an agent to the execution pipeline.

        Parameters
        ----------
        agent:
            Concrete :class:`BaseAgent` implementation.
        """
        self._agents.append(agent)
        logger.info("Registered agent: %s", agent.name)

    async def run(self) -> BlackboardMemory:
        """Execute every registered agent sequentially against a fresh blackboard.

        Returns
        -------
        BlackboardMemory
            The fully populated blackboard after all agents have run.
        """
        blackboard = BlackboardMemory()
        blackboard.audit_timestamp = datetime.now(timezone.utc).isoformat()
        logger.info("Audit started at %s", blackboard.audit_timestamp)

        for agent in self._agents:
            logger.info("Running agent: %s", agent.name)
            try:
                await agent.execute(blackboard)
            except Exception as exc:  # noqa: BLE001
                logger.exception("Agent %s failed: %s", agent.name, exc)
                blackboard.system_status = "CRITICAL"
                blackboard.metadata[f"{agent.name}_error"] = str(exc)

        logger.info(
            "Audit complete — status=%s agents=%d",
            blackboard.system_status,
            len(self._agents),
        )
        return blackboard

    async def run_full_audit(self) -> str:
        """Run the full audit pipeline and return a markdown report.

        Returns
        -------
        str
            A formatted markdown string containing all metrics, alerts,
            and recommendations.
        """
        blackboard = await self.run()
        report = self._render_markdown(blackboard)
        return report

    # -- report renderer ---------------------------------------------------

    @staticmethod
    def _render_markdown(bb: BlackboardMemory) -> str:
        """Generate a human-readable markdown report from *bb*."""
        ts = bb.audit_timestamp or datetime.now(timezone.utc).isoformat()
        lines: List[str] = [
            "# Swarm Edge Audit Report",
            "",
            f"**Generated:** `{ts}`  ",
            f"**Status:** `{bb.system_status}`  ",
            f"**Raw picks:** {len(bb.raw_picks)}",
            "",
            "---",
            "",
        ]

        # Portfolio summary
        if bb.portfolio_metrics is not None:
            pm = bb.portfolio_metrics
            lines.extend(
                [
                    "## Portfolio Summary",
                    "",
                    "| Metric | Value |",
                    "|--------|-------|",
                    f"| Total Trades | {pm.total_trades} |",
                    f"| Win Rate | {pm.win_rate:.2%} |",
                    f"| Avg Win | {pm.avg_win:.4f} |",
                    f"| Avg Loss | {pm.avg_loss:.4f} |",
                    f"| Expected Value | {pm.expected_value:.6f} |",
                    f"| Profit Factor | {pm.profit_factor:.4f} |",
                    f"| Sharpe Ratio | {pm.sharpe_ratio:.4f} |",
                    f"| Kelly Fraction | {pm.kelly_fraction:.4f} |",
                    f"| Max Drawdown % | {pm.max_drawdown_pct:.2f}% |",
                    f"| Assessment | **{pm.status_assessment}** |",
                    "",
                ]
            )

        # Per-asset-class metrics
        if bb.metrics_per_class:
            lines.extend(
                [
                    "## Per-Asset-Class Metrics",
                    "",
                    "| Asset Class | Trades | Win Rate | EV | PF | Sharpe | Kelly | Status |",
                    "|-------------|--------|----------|-----|-----|--------|-------|--------|",
                ]
            )
            for ac, em in sorted(bb.metrics_per_class.items()):
                pf_str = f"{em.profit_factor:.4f}" if em.profit_factor != float("inf") else "inf"
                lines.append(
                    f"| {ac} | {em.total_trades} | {em.win_rate:.2%} | "
                    f"{em.expected_value:.6f} | {pf_str} | "
                    f"{em.sharpe_ratio:.4f} | {em.kelly_fraction:.4f} | "
                    f"{em.status_assessment} |"
                )
            lines.append("")

        # Concentration
        if bb.concentration is not None:
            cm = bb.concentration
            lines.extend(
                [
                    "## Concentration Analysis",
                    "",
                    "| Metric | Value |",
                    "|--------|-------|",
                    f"| Herfindahl Index | {cm.herfindahl_index:.6f} |",
                    f"| Gini Coefficient | {cm.gini_coefficient:.6f} |",
                    "",
                    "**Asset-class shares:**",
                    "",
                ]
            )
            for ac, share in sorted(cm.asset_class_shares.items()):
                lines.append(f"- {ac}: {share:.2%}")
            lines.append("")

        # Degradation alerts
        if bb.degradation_alerts:
            lines.extend(
                [
                    "## Degradation Alerts",
                    "",
                    "| Asset Class | EV | Status | Severity |",
                    "|-------------|-----|--------|----------|",
                ]
            )
            for alert in bb.degradation_alerts:
                lines.append(
                    f"| {alert['asset_class']} | {alert['expected_value']} | "
                    f"{alert['status_assessment']} | {alert['severity']} |"
                )
            lines.append("")
        else:
            lines.extend(
                [
                    "## Degradation Alerts",
                    "",
                    "No degradation alerts — all asset classes meet the EV threshold.",
                    "",
                ]
            )

        # Suggestions
        if bb.enhancement_suggestions:
            lines.extend(
                [
                    "## Enhancement Suggestions",
                    "",
                ]
            )
            for idx, sug in enumerate(bb.enhancement_suggestions, start=1):
                lines.append(f"{idx}. {sug}")
            lines.append("")

        # Metadata / errors
        if bb.metadata:
            lines.extend(
                [
                    "## Metadata",
                    "",
                    "```json",
                    json.dumps(bb.metadata, indent=2, default=str),
                    "```",
                    "",
                ]
            )

        lines.append("---")
        lines.append("*End of report*")
        return "\n".join(lines)

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"agents={len(self._agents)}, "
            f"ev_threshold={self._ev_threshold})"
        )
