#!/usr/bin/env python3
"""
Extract canvas animation code from blog200-249 HTML files.
Generates theme-animations.js with per-theme animation IIFEs.
"""
import re
import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

animations = {}

# blog200-249 (root level files)
for i in range(200, 250):
    filepath = os.path.join(ROOT, 'blog{}.html'.format(i))
    if not os.path.exists(filepath):
        print('  SKIP blog{}.html (not found)'.format(i))
        continue

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract the canvas animation script block
    # Pattern: /* Canvas Animation: ... */ followed by IIFE (function(){...}());
    match = re.search(
        r'/\* Canvas Animation: (.+?)\s*\*/\s*\(function\(\)\{(.+?)\}\(\)\);?',
        content,
        re.DOTALL
    )
    if match:
        anim_name = match.group(1).strip()
        # Get the full IIFE including wrapper
        full_code = '(function(){' + match.group(2) + '}())'
        animations['blog{}'.format(i)] = {
            'name': anim_name,
            'code': full_code
        }
        print('  OK blog{}.html -> "{}"'.format(i, anim_name))
    else:
        print('  WARN blog{}.html - no canvas animation found'.format(i))

# Also check blog100-149 series (in build/blog/)
build_dir = os.path.join(ROOT, 'TORONTOEVENTS_ANTIGRAVITY', 'build', 'blog')
for i in range(100, 150):
    filepath = os.path.join(build_dir, 'blog{}.html'.format(i))
    if not os.path.exists(filepath):
        continue

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    match = re.search(
        r'/\* Canvas Animation: (.+?)\s*\*/\s*\(function\(\)\{(.+?)\}\(\)\);?',
        content,
        re.DOTALL
    )
    if match:
        anim_name = match.group(1).strip()
        full_code = '(function(){' + match.group(2) + '}())'
        animations['blog{}'.format(i)] = {
            'name': anim_name,
            'code': full_code
        }
        print('  OK blog{}.html (build) -> "{}"'.format(i, anim_name))

# Also check blog3-53 series (in build/blog/)
for i in range(3, 54):
    filepath = os.path.join(build_dir, 'blog{}.html'.format(i))
    if not os.path.exists(filepath):
        continue

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    match = re.search(
        r'/\* Canvas Animation: (.+?)\s*\*/\s*\(function\(\)\{(.+?)\}\(\)\);?',
        content,
        re.DOTALL
    )
    if match:
        anim_name = match.group(1).strip()
        full_code = '(function(){' + match.group(2) + '}())'
        animations['blog{}'.format(i)] = {
            'name': anim_name,
            'code': full_code
        }
        print('  OK blog{}.html (build) -> "{}"'.format(i, anim_name))

print('\nTotal animations extracted: {}'.format(len(animations)))

# Generate theme-animations.js
output_lines = [
    '/**',
    ' * Theme Animations — Per-theme canvas animation code',
    ' * Auto-generated by tools/extract_animations.py',
    ' * Each entry maps a theme ID to its unique canvas animation IIFE.',
    ' * The code expects a <canvas id="bg-canvas"> element in the DOM.',
    ' */',
    'window.THEME_ANIMATIONS = {};',
    ''
]

for theme_id in sorted(animations.keys(), key=lambda x: int(re.search(r'\d+', x).group())):
    info = animations[theme_id]
    # JSON-encode the code string to safely embed it
    code_json = json.dumps(info['code'])
    output_lines.append('// {} — {}'.format(theme_id, info['name']))
    output_lines.append('window.THEME_ANIMATIONS["{}"] = {};'.format(theme_id, code_json))
    output_lines.append('')

output_path = os.path.join(ROOT, 'theme-animations.js')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(output_lines))

print('Written to: {}'.format(output_path))
print('File size: {:.1f} KB'.format(os.path.getsize(output_path) / 1024))
