"""Generate HTML companion pages + a landing page for the 90-Day Plan (May 15 2026).

For each source .md it renders a dark-themed standalone HTML companion under
reports/90day_pages_2026-05-15/, and builds a landing page
reports/90day_plan_2026-05-15.html with a table-of-contents grouped by
asset class and content type.

Run from repo root:  python tools/generate_90day_plan_pages.py
Idempotent — overwrites its own output. No other files touched.
"""

from __future__ import annotations

import datetime
import html
from pathlib import Path

import markdown

REPO = Path(__file__).resolve().parent.parent
REPORTS = REPO / "reports"
OUT_DIR = REPORTS / "90day_pages_2026-05-15"
LANDING = REPORTS / "90day_plan_2026-05-15.html"

# (source_md, title, group, accent)
PAGES = [
    ("SUPREME_PLAN_90days.md", "Supreme Plan — 90-Day Roadmap", "Roadmap", "#f59e0b"),
    ("asset_class_90day_plan_COMMODITY_2026-05-15.md", "COMMODITY — 90-Day Plan", "Asset Class", "#f59e0b"),
    ("asset_class_90day_plan_EQUITY_2026-05-15.md", "EQUITY — 90-Day Plan", "Asset Class", "#22c55e"),
    ("asset_class_90day_plan_ETF_2026-05-15.md", "ETF — 90-Day Plan", "Asset Class", "#06b6d4"),
    ("asset_class_90day_plan_CRYPTO_2026-05-15.md", "CRYPTO — 90-Day Plan", "Asset Class", "#a78bfa"),
    ("asset_class_90day_plan_BOND_2026-05-15.md", "BOND — 90-Day Plan", "Asset Class", "#60a5fa"),
    ("asset_class_90day_plan_FOREX_2026-05-15.md", "FOREX — 90-Day Plan", "Asset Class", "#f472b6"),
    ("asset_class_90day_plan_FUTURES_2026-05-15.md", "FUTURES — 90-Day Plan", "Asset Class", "#fb923c"),
    ("asset_class_90day_plan_PENNY_MEME_2026-05-15.md", "PENNY / MEME — 90-Day Plan", "Asset Class", "#ef4444"),
    ("strategy_polymarket_assessment_2026-05-15.md", "Polymarket — Assessment", "Prediction Markets", "#a78bfa"),
    ("strategy_kalshi_assessment_2026-05-15.md", "Kalshi — Assessment", "Prediction Markets", "#a78bfa"),
    ("strategy_copytrader_assessment_2026-05-15.md", "CopyTrader Intel — Assessment", "Strategy / Data Source", "#06b6d4"),
    ("hyrotrader_methodology_enhancements_2026-05-15.md", "HyroTrader — Methodology Enhancements", "Strategy / Data Source", "#06b6d4"),
    ("data_flow_integrity_audit_2026-05-15.md", "Data Flow Integrity Audit", "Pipeline Audit", "#ef4444"),
]

PAGE_CSS = """
  body{background:#0b0f17;color:#d1d5db;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
       line-height:1.65;margin:0;padding:0}
  .wrap{max-width:920px;margin:0 auto;padding:32px 22px 80px}
  a{color:#60a5fa;text-decoration:none}a:hover{text-decoration:underline}
  h1,h2,h3,h4{color:#f3f4f6;line-height:1.3;margin:1.6em 0 .5em}
  h1{font-size:1.7em;border-bottom:2px solid var(--accent);padding-bottom:.3em;margin-top:0}
  h2{font-size:1.3em;border-bottom:1px solid #1f2937;padding-bottom:.2em}
  h3{font-size:1.08em;color:#cbd5e1}
  code{background:#1f2937;color:#fbbf24;padding:1px 6px;border-radius:4px;font-size:.88em}
  pre{background:#111827;border:1px solid #1f2937;border-radius:8px;padding:14px;overflow-x:auto}
  pre code{background:none;color:#d1d5db;padding:0}
  table{border-collapse:collapse;width:100%;margin:1em 0;font-size:.9em}
  th,td{border:1px solid #1f2937;padding:7px 11px;text-align:left}
  th{background:#1f2937;color:#f3f4f6}
  tr:nth-child(even){background:#0f1623}
  blockquote{border-left:3px solid var(--accent);margin:1em 0;padding:.3em 1em;color:#9ca3af;background:#0f1623}
  ul,ol{padding-left:24px}
  hr{border:none;border-top:1px solid #1f2937;margin:2em 0}
  .nav{font-size:.85em;color:#9ca3af;margin-bottom:24px}
  .src{font-size:.8em;color:#6b7280;margin-top:40px;border-top:1px solid #1f2937;padding-top:12px}
"""


def render_page(md_path: Path, title: str, accent: str) -> str:
    body = markdown.markdown(
        md_path.read_text(encoding="utf-8"),
        extensions=["tables", "fenced_code", "sane_lists"],
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)} — findtorontoevents.ca</title>
<style>:root{{--accent:{accent}}}{PAGE_CSS}</style>
</head><body><div class="wrap">
<div class="nav"><a href="../90day_plan_2026-05-15.html">&larr; 90-Day Plan landing</a> &nbsp;|&nbsp;
<a href="/updates/">Updates feed</a></div>
{body}
<div class="src">Source: <code>reports/{md_path.name}</code> &middot;
90-Day Plan — May 15 2026 Edition &middot; generated by tools/generate_90day_plan_pages.py</div>
</div></body></html>
"""


def build_landing(generated: list[tuple[str, str, str, str]]) -> str:
    groups: dict[str, list[tuple[str, str, str]]] = {}
    for htmlname, title, group, accent in generated:
        groups.setdefault(group, []).append((htmlname, title, accent))

    order = ["Roadmap", "Asset Class", "Prediction Markets", "Strategy / Data Source", "Pipeline Audit"]
    toc_cards = []
    for group in order:
        if group not in groups:
            continue
        items = "".join(
            f'<li><a href="90day_pages_2026-05-15/{hn}" style="color:{ac}">{html.escape(t)}</a></li>'
            for hn, t, ac in groups[group]
        )
        toc_cards.append(
            f'<div class="card"><h2>{html.escape(group)}</h2><ul>{items}</ul></div>'
        )

    today = datetime.date(2026, 5, 15).strftime("%B %d, %Y")
    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>90-Day Plan — May 15 2026 Edition — findtorontoevents.ca</title>
<style>
  body{{background:#0b0f17;color:#d1d5db;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
       line-height:1.6;margin:0;padding:0}}
  a{{text-decoration:none}}a:hover{{text-decoration:underline}}
  .wrap{{max-width:1080px;margin:0 auto;padding:40px 22px 80px}}
  h1{{color:#f3f4f6;font-size:2em;margin:0 0 6px;border-bottom:3px solid #f59e0b;padding-bottom:.3em}}
  .sub{{color:#9ca3af;font-size:.95em;margin:0 0 28px}}
  .intro{{background:#0f1623;border:1px solid #1f2937;border-radius:10px;padding:16px 20px;margin-bottom:30px;font-size:.93em}}
  .intro strong{{color:#fbbf24}}
  .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:18px}}
  .card{{background:#0f1623;border:1px solid #1f2937;border-radius:10px;padding:14px 20px}}
  .card h2{{color:#f3f4f6;font-size:1.1em;margin:.2em 0 .6em;border-bottom:1px solid #1f2937;padding-bottom:.3em}}
  .card ul{{margin:0;padding-left:20px}}
  .card li{{margin:6px 0}}
  .warn{{background:#1f1410;border:1px solid #b45309;border-radius:8px;padding:12px 16px;margin:24px 0;
         color:#fcd34d;font-size:.9em}}
  .foot{{color:#6b7280;font-size:.82em;margin-top:36px;border-top:1px solid #1f2937;padding-top:14px}}
</style>
</head><body><div class="wrap">
<h1>&#x1F5FA;&#xFE0F; 90-Day Plan — May 15 2026 Edition</h1>
<p class="sub">findtorontoevents.ca &middot; multi-asset money-maker execution roadmap &middot; <a href="/updates/" style="color:#60a5fa">back to Updates feed</a></p>

<div class="intro">
Full 90-day execution roadmap — one plan per asset class plus prediction-market and prop-firm
strategy assessments. Generated via the <strong>money-maker-continual-improve</strong> skill,
cross-checked against the MySQL backtest tables and GitHub Actions job logs. Pick a section below.
</div>

<div class="grid">
{''.join(toc_cards)}
</div>

<div class="warn">
&#x26A0;&#xFE0F; <strong>Note:</strong> these plans predate the cotton kill autopsy. Cotton (CT=F) is
blacklisted in the quality gates and is <strong>not</strong> a near-term real-money pilot. The current
verdict is HOLD_KILLED_PENDING_DATA. See <code>reports/deep_dive_cotton_2026-05-15.md</code> and
<code>reports/phase2d_kill_audit_2026-05-15.md</code>. The highest-leverage fix is M-055 kill-threshold
recalibration (shipped — <code>audit_trail/kill_gate.py</code>), not a cotton pilot.
</div>

<div class="foot">90-Day Plan — May 15 2026 Edition &middot; companion pages generated by
<code>tools/generate_90day_plan_pages.py</code> &middot; last built {today}</div>
</div></body></html>
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    generated: list[tuple[str, str, str, str]] = []
    for md_name, title, group, accent in PAGES:
        md_path = REPORTS / md_name
        if not md_path.exists():
            print(f"SKIP (missing): {md_name}")
            continue
        html_name = md_path.stem + ".html"
        (OUT_DIR / html_name).write_text(render_page(md_path, title, accent), encoding="utf-8")
        generated.append((html_name, title, group, accent))
        print(f"OK  {html_name}")
    LANDING.write_text(build_landing(generated), encoding="utf-8")
    print(f"OK  landing: {LANDING.relative_to(REPO)}")
    print(f"{len(generated)} companion pages + 1 landing page")


if __name__ == "__main__":
    main()
