#!/usr/bin/env python3
"""
Generate 50 uniquely themed Toronto Events blog landing pages.
Each page has: event filtering, stunning animations, navigation arrows,
and full "Other Stuff" menu.

Generated by Claude Code VS Code - Anthropic's CLI for Claude
"""

import os

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                          "TORONTOEVENTS_ANTIGRAVITY", "build", "blog")

# 50 themes: blog3 through blog53 (skipping blog52 which exists)
THEMES = [
    # (number, name, subtitle, primary, secondary, accent, bg_dark, bg_light, font_import, title_font, animation_type)
    (3, "Cyberpunk Neon", "Neon-lit digital city", "#ff2d95", "#00f0ff", "#b400ff", "#0a0014", "#120020", "Orbitron:wght@700;900", "Orbitron", "neon_grid"),
    (4, "Retro Arcade", "8-bit pixel paradise", "#00ff41", "#ff6b00", "#ffdd00", "#0d0208", "#1a0510", "Press+Start+2P&family=VT323", "Press Start 2P", "pixel_rain"),
    (5, "Vaporwave Dreams", "A e s t h e t i c", "#ff71ce", "#01cdfe", "#b967ff", "#1a0030", "#2d0050", "Lobster&family=Inter:wght@400;700", "Lobster", "vaporwave"),
    (6, "Brutalist Raw", "No decoration. Pure function.", "#ffffff", "#ff0000", "#000000", "#e8e8e8", "#f5f5f5", "Space+Mono:wght@400;700&family=Inter:wght@700;900", "Space Mono", "brutalist"),
    (7, "Art Deco Gatsby", "The roaring twenties reborn", "#d4af37", "#f5e6cc", "#8b7355", "#0a0a0a", "#1a1510", "Playfair+Display:ital,wght@0,700;0,900;1,700", "Playfair Display", "deco_lines"),
    (8, "Y2K Chrome", "Welcome to the future past", "#c0c0c0", "#e8e8ff", "#7b68ee", "#0a0a1a", "#14142a", "Orbitron:wght@400;700&family=Inter:wght@400;700", "Orbitron", "chrome_orbs"),
    (9, "Matrix Code", "Follow the white rabbit", "#00ff41", "#003b00", "#00cc33", "#000000", "#001100", "Share+Tech+Mono&family=Inter:wght@400;700", "Share Tech Mono", "matrix_rain"),
    (10, "Synthwave Sunset", "Ride into the neon horizon", "#ff6ec7", "#7b2ff7", "#ff9e2c", "#0f0028", "#1a0040", "Audiowide&family=Inter:wght@400;700", "Audiowide", "synthwave_sun"),
    (11, "Paper Origami", "Folded with care", "#e07c5a", "#5a8f7b", "#d4a574", "#faf5f0", "#fff8f2", "Crimson+Text:ital,wght@0,400;0,700;1,400", "Crimson Text", "paper_fold"),
    (12, "Deep Ocean", "Beneath the waves", "#00b4d8", "#0077b6", "#90e0ef", "#001220", "#002030", "Quicksand:wght@400;600;700", "Quicksand", "bubbles"),
    (13, "Cosmic Explorer", "Among the stars", "#e8d5f5", "#7c3aed", "#f59e0b", "#05051a", "#0a0a2a", "Exo+2:wght@400;700;900", "Exo 2", "starfield"),
    (14, "Steampunk Machine", "Gears of wonder", "#cd853f", "#8b4513", "#daa520", "#1a1208", "#2a1e10", "Cinzel:wght@400;700;900", "Cinzel", "gears"),
    (15, "Film Noir", "Shadows and secrets", "#c0c0c0", "#808080", "#ffffff", "#0a0a0a", "#141414", "Libre+Baskerville:ital,wght@0,400;0,700;1,400", "Libre Baskerville", "noir_grain"),
    (16, "Pop Art Comic", "POW! BAM! WOW!", "#ff3366", "#ffcc00", "#3366ff", "#ffffff", "#fff5f5", "Bangers&family=Inter:wght@400;700", "Bangers", "halftone"),
    (17, "Zen Minimal", "Less is everything", "#1a1a1a", "#999999", "#e0d5c1", "#fafaf8", "#ffffff", "Noto+Serif+JP:wght@400;700", "Noto Serif JP", "zen_circles"),
    (18, "Glitch Art", "Error is beauty", "#ff0000", "#00ff00", "#0000ff", "#0a0a0a", "#141414", "Space+Grotesk:wght@400;700", "Space Grotesk", "glitch"),
    (19, "Tropical Paradise", "Island vibes only", "#ff6b6b", "#ffd93d", "#6bcb77", "#002b1a", "#003d25", "Pacifico&family=Inter:wght@400;700", "Pacifico", "palm_leaves"),
    (20, "Aurora Borealis", "Northern light show", "#00ff87", "#7b2ff7", "#00d4ff", "#020810", "#041020", "Rajdhani:wght@400;600;700", "Rajdhani", "aurora"),
    (21, "Holographic Prism", "Shift the spectrum", "#ff6ec7", "#7b68ee", "#00ced1", "#0a0a14", "#14142a", "Syne:wght@400;700;800", "Syne", "holographic"),
    (22, "Black & Gold Luxury", "Opulence defined", "#d4af37", "#b8860b", "#fff8dc", "#050505", "#0a0a0a", "Cormorant+Garamond:ital,wght@0,400;0,700;1,400", "Cormorant Garamond", "gold_particles"),
    (23, "Glassmorphism", "Through the frosted glass", "#667eea", "#764ba2", "#f093fb", "#0f0c29", "#1a1440", "Poppins:wght@300;400;600;700", "Poppins", "glass_panels"),
    (24, "Soft Neumorphism", "Touch the surface", "#6c63ff", "#3f3d56", "#a8a4ff", "#e0e5ec", "#ecf0f3", "DM+Sans:wght@400;500;700", "DM Sans", "neumorphic"),
    (25, "Neon Tokyo", "Lost in translation", "#ff1493", "#00ff7f", "#ff4500", "#0a0014", "#140020", "Zen+Dots&family=Inter:wght@400;700", "Zen Dots", "tokyo_rain"),
    (26, "Retro Terminal", "C:\\> ACCESS GRANTED", "#33ff33", "#00cc00", "#009900", "#0a0a0a", "#0d0d0d", "Fira+Code:wght@400;700", "Fira Code", "terminal"),
    (27, "Watercolor Bloom", "Painted by hand", "#e8a87c", "#d291bc", "#85c1e2", "#fef9f5", "#ffffff", "Dancing+Script:wght@400;700&family=Inter:wght@400;700", "Dancing Script", "watercolor"),
    (28, "Geometric Prism", "Sharp angles, bold forms", "#e74c3c", "#3498db", "#2ecc71", "#0a0a14", "#141428", "Russo+One&family=Inter:wght@400;700", "Russo One", "triangles"),
    (29, "Gradient Flux", "Flowing color fields", "#f72585", "#7209b7", "#4361ee", "#0a0014", "#14002a", "Plus+Jakarta+Sans:wght@400;600;800", "Plus Jakarta Sans", "gradient_mesh"),
    (30, "Fire & Ember", "Feel the heat", "#ff4500", "#ff6347", "#ffd700", "#1a0800", "#2a1000", "Bebas+Neue&family=Inter:wght@400;700", "Bebas Neue", "fire_particles"),
    (31, "Ice Crystal", "Frozen in time", "#a8d8ea", "#b0d4f1", "#ffffff", "#081828", "#0c2038", "Comfortaa:wght@400;700", "Comfortaa", "snowflakes"),
    (32, "Psychedelic 60s", "Turn on, tune in", "#ff1493", "#ff8c00", "#00ff00", "#1a0028", "#2a0040", "Bungee&family=Inter:wght@400;700", "Bungee", "psychedelic"),
    (33, "Bauhaus Modern", "Form follows function", "#e63946", "#1d3557", "#f1c40f", "#ffffff", "#f8f8f8", "Archivo+Black&family=Inter:wght@400;700", "Archivo Black", "bauhaus"),
    (34, "Rain City", "Neon reflected in puddles", "#00bfff", "#ff1493", "#7cfc00", "#050510", "#0a0a1a", "Chakra+Petch:wght@400;600;700", "Chakra Petch", "rain"),
    (35, "Earth & Stone", "Rooted in nature", "#8d6e63", "#4caf50", "#795548", "#1a1510", "#2a2520", "Merriweather:wght@400;700;900", "Merriweather", "organic"),
    (36, "Memphis 80s", "Squiggles and shapes", "#ff6b9d", "#c44eff", "#00f5d4", "#1a1028", "#2a1a40", "Righteous&family=Inter:wght@400;700", "Righteous", "memphis"),
    (37, "Isometric World", "A new dimension", "#4fc3f7", "#7c4dff", "#69f0ae", "#0a1020", "#141a30", "IBM+Plex+Mono:wght@400;600;700", "IBM Plex Mono", "isometric"),
    (38, "Vintage Press", "Extra! Extra! Read all about it!", "#2c1810", "#8b4513", "#d2691e", "#f5f0e8", "#faf5ed", "Playfair+Display+SC:wght@400;700;900", "Playfair Display SC", "newspaper"),
    (39, "Wireframe Neon", "Blueprint of the future", "#00ff88", "#ff00ff", "#ffff00", "#050510", "#0a0a1a", "Orbitron:wght@400;700;900", "Orbitron", "wireframe"),
    (40, "Candy Pastel", "Sweet as sugar", "#ffb3ba", "#bae1ff", "#baffc9", "#fff5f7", "#ffffff", "Fredoka:wght@400;600;700", "Fredoka", "candy"),
    (41, "Dark Steel", "Industrial strength", "#708090", "#b0c4de", "#c0c0c0", "#0a0a0e", "#14141a", "Oswald:wght@400;600;700", "Oswald", "steel"),
    (42, "Sunset Beach", "Golden hour vibes", "#ff7e5f", "#feb47b", "#ff6b6b", "#1a0e08", "#2a1a10", "Satisfy&family=Inter:wght@400;700", "Satisfy", "sunset"),
    (43, "Nebula Cosmic", "Born from stardust", "#9b59b6", "#e74c3c", "#3498db", "#050508", "#0a0a14", "Orbitron:wght@400;700;900", "Orbitron", "nebula"),
    (44, "Retro Film", "Lights, camera, action", "#daa520", "#cd853f", "#f5deb3", "#0a0808", "#1a1210", "Special+Elite&family=Inter:wght@400;700", "Special Elite", "film_strip"),
    (45, "Liquid Chrome", "Morphing metal", "#c0c0c0", "#e8e8ff", "#a8a8ff", "#0a0a14", "#14142a", "Outfit:wght@400;600;800", "Outfit", "liquid"),
    (46, "Botanical Garden", "Where nature thrives", "#228b22", "#90ee90", "#556b2f", "#0a1a0a", "#142a14", "Playfair+Display:wght@400;700", "Playfair Display", "botanical"),
    (47, "Moonlight Silver", "Under the pale moon", "#c0c0c0", "#4169e1", "#e6e6fa", "#080810", "#10101a", "Cinzel+Decorative:wght@400;700;900", "Cinzel Decorative", "moonlight"),
    (48, "Electric Storm", "Thunder and lightning", "#ffd700", "#ff4500", "#1e90ff", "#050508", "#0a0a14", "Teko:wght@400;600;700", "Teko", "lightning"),
    (49, "Vintage Polaroid", "Instant memories", "#f5e6d3", "#d4a373", "#ccd5ae", "#faf5ef", "#ffffff", "Caveat:wght@400;700", "Caveat", "polaroid"),
    (50, "Coral Reef", "Living color underwater", "#ff7f50", "#20b2aa", "#f0e68c", "#081520", "#0c2030", "Nunito:wght@400;600;800", "Nunito", "coral"),
    (51, "Stained Glass", "Cathedral light", "#ff4444", "#4444ff", "#44ff44", "#0a0808", "#1a1210", "Uncial+Antiqua&family=Inter:wght@400;700", "Uncial Antiqua", "stained_glass"),
    (53, "Future Chrome", "Tomorrow is now", "#e0e0e0", "#6366f1", "#22d3ee", "#050508", "#0a0a10", "Inter:wght@300;400;600;800", "Inter", "future"),
]

def get_animation_js(anim_type, primary, secondary, accent, bg_dark="#0a0a0a", bg_light="#1a1a1a"):
    """Return canvas animation JavaScript for each theme type."""

    animations = {
        "neon_grid": f"""
            const particles = [];
            for(let i = 0; i < 80; i++) particles.push({{
                x: Math.random()*w, y: Math.random()*h,
                vx: (Math.random()-0.5)*2, vy: (Math.random()-0.5)*2,
                r: Math.random()*3+1, color: Math.random()>0.5 ? '{primary}' : '{accent}'
            }});
            function draw() {{
                ctx.fillStyle = 'rgba(10,0,20,0.1)'; ctx.fillRect(0,0,w,h);
                // Grid
                ctx.strokeStyle = '{primary}22'; ctx.lineWidth = 0.5;
                for(let x=0;x<w;x+=40){{ ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,h); ctx.stroke(); }}
                for(let y=0;y<h;y+=40){{ ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(w,y); ctx.stroke(); }}
                particles.forEach(p => {{
                    p.x += p.vx; p.y += p.vy;
                    if(p.x<0||p.x>w) p.vx*=-1;
                    if(p.y<0||p.y>h) p.vy*=-1;
                    ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
                    ctx.fillStyle = p.color; ctx.shadowColor = p.color;
                    ctx.shadowBlur = 15; ctx.fill(); ctx.shadowBlur = 0;
                }});
                for(let i=0;i<particles.length;i++) for(let j=i+1;j<particles.length;j++) {{
                    const dx=particles[i].x-particles[j].x, dy=particles[i].y-particles[j].y;
                    const d=Math.sqrt(dx*dx+dy*dy);
                    if(d<120){{ ctx.beginPath(); ctx.moveTo(particles[i].x,particles[i].y);
                        ctx.lineTo(particles[j].x,particles[j].y);
                        ctx.strokeStyle='{primary}'+(Math.floor((1-d/120)*60)).toString(16).padStart(2,'0');
                        ctx.lineWidth=0.5; ctx.stroke(); }}
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "pixel_rain": f"""
            const cols = Math.floor(w/16); const drops = new Array(cols).fill(0);
            const chars = '01TORONTOEVENTSFUN';
            function draw() {{
                ctx.fillStyle = 'rgba(13,2,8,0.08)'; ctx.fillRect(0,0,w,h);
                ctx.font = '14px "Press Start 2P", monospace';
                drops.forEach((y,i) => {{
                    const c = chars[Math.floor(Math.random()*chars.length)];
                    ctx.fillStyle = Math.random()>0.9 ? '{secondary}' : '{primary}';
                    ctx.fillText(c, i*16, y*16);
                    if(y*16 > h && Math.random()>0.975) drops[i]=0;
                    drops[i]++;
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "vaporwave": f"""
            let t = 0;
            function draw() {{
                t += 0.01;
                const grd = ctx.createLinearGradient(0,0,w,h);
                grd.addColorStop(0, '{primary}33'); grd.addColorStop(0.5, '{accent}33'); grd.addColorStop(1, '{secondary}33');
                ctx.fillStyle = 'rgba(26,0,48,0.05)'; ctx.fillRect(0,0,w,h);
                // Horizon grid
                ctx.strokeStyle = '{secondary}44';
                for(let y=h*0.5;y<h;y+=20) {{
                    ctx.beginPath(); ctx.moveTo(0,y+(y-h*0.5)*Math.sin(t)*0.1); ctx.lineTo(w,y+(y-h*0.5)*Math.sin(t+2)*0.1); ctx.stroke();
                }}
                for(let x=0;x<w;x+=40) {{
                    ctx.beginPath(); ctx.moveTo(w/2,h*0.5); ctx.lineTo(x,h); ctx.stroke();
                }}
                // Sun
                const sunGrd = ctx.createRadialGradient(w/2,h*0.4,20,w/2,h*0.4,100);
                sunGrd.addColorStop(0, '{primary}'); sunGrd.addColorStop(1, '{primary}00');
                ctx.fillStyle = sunGrd; ctx.fillRect(0,0,w,h);
                requestAnimationFrame(draw);
            }} draw();""",

        "brutalist": f"""
            function draw() {{
                ctx.fillStyle = '#e8e8e8'; ctx.fillRect(0,0,w,h);
                ctx.fillStyle = '#000'; ctx.font = 'bold 200px sans-serif';
                ctx.globalAlpha = 0.03;
                for(let i=0;i<5;i++) ctx.fillText('TORONTO', Math.random()*w-200, Math.random()*h);
                ctx.globalAlpha = 1;
                ctx.fillStyle = '{secondary}';
                ctx.fillRect(Math.random()*w, Math.random()*h, Math.random()*200+50, Math.random()*8+2);
            }} setInterval(draw, 2000); draw();""",

        "deco_lines": f"""
            let t = 0;
            function draw() {{
                t += 0.005;
                ctx.fillStyle = 'rgba(10,10,10,0.03)'; ctx.fillRect(0,0,w,h);
                ctx.strokeStyle = '{primary}'; ctx.lineWidth = 1;
                for(let i=0;i<12;i++) {{
                    const a = t + i * Math.PI/6;
                    ctx.beginPath();
                    ctx.moveTo(w/2 + Math.cos(a)*50, h/2 + Math.sin(a)*50);
                    ctx.lineTo(w/2 + Math.cos(a)*300, h/2 + Math.sin(a)*300);
                    ctx.globalAlpha = 0.3; ctx.stroke(); ctx.globalAlpha = 1;
                }}
                // Diamond
                ctx.strokeStyle = '{primary}66'; ctx.lineWidth = 2;
                const s = 150 + Math.sin(t*2)*20;
                ctx.beginPath(); ctx.moveTo(w/2,h/2-s); ctx.lineTo(w/2+s,h/2);
                ctx.lineTo(w/2,h/2+s); ctx.lineTo(w/2-s,h/2); ctx.closePath(); ctx.stroke();
                requestAnimationFrame(draw);
            }} draw();""",

        "chrome_orbs": f"""
            const orbs = [];
            for(let i=0;i<20;i++) orbs.push({{
                x:Math.random()*w, y:Math.random()*h, r:Math.random()*40+20,
                vx:(Math.random()-0.5)*1, vy:(Math.random()-0.5)*1
            }});
            function draw() {{
                ctx.fillStyle = 'rgba(10,10,26,0.1)'; ctx.fillRect(0,0,w,h);
                orbs.forEach(o => {{
                    o.x+=o.vx; o.y+=o.vy;
                    if(o.x<0||o.x>w) o.vx*=-1; if(o.y<0||o.y>h) o.vy*=-1;
                    const g = ctx.createRadialGradient(o.x-o.r*0.3,o.y-o.r*0.3,0,o.x,o.y,o.r);
                    g.addColorStop(0,'#ffffff88'); g.addColorStop(0.5,'{primary}44'); g.addColorStop(1,'{accent}22');
                    ctx.beginPath(); ctx.arc(o.x,o.y,o.r,0,Math.PI*2);
                    ctx.fillStyle=g; ctx.fill();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "matrix_rain": f"""
            const cols=Math.floor(w/14); const drops=new Array(cols).fill(0);
            const chars='アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン0123456789TORONTO';
            function draw() {{
                ctx.fillStyle='rgba(0,0,0,0.05)'; ctx.fillRect(0,0,w,h);
                ctx.font='14px monospace';
                drops.forEach((y,i)=>{{
                    const c=chars[Math.floor(Math.random()*chars.length)];
                    ctx.fillStyle=y*14<50?'#fff':'{primary}';
                    ctx.fillText(c,i*14,y*14);
                    if(y*14>h&&Math.random()>0.975) drops[i]=0;
                    drops[i]++;
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "synthwave_sun": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(15,0,40,0.1)'; ctx.fillRect(0,0,w,h);
                // Sun
                const sg=ctx.createRadialGradient(w/2,h*0.45,10,w/2,h*0.45,120);
                sg.addColorStop(0,'{accent}'); sg.addColorStop(0.5,'{primary}'); sg.addColorStop(1,'{secondary}00');
                ctx.fillStyle=sg; ctx.beginPath(); ctx.arc(w/2,h*0.45,120,0,Math.PI*2); ctx.fill();
                // Grid floor
                ctx.strokeStyle='{primary}55'; ctx.lineWidth=1;
                for(let y=h*0.6;y<h;y+=15){{ ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(w,y); ctx.stroke(); }}
                for(let x=-200;x<w+200;x+=40){{
                    ctx.beginPath(); ctx.moveTo(w/2,h*0.6);
                    ctx.lineTo(x+(x-w/2)*2,h); ctx.stroke();
                }}
                // Stars
                if(Math.random()>0.95){{ ctx.fillStyle='#fff'; ctx.fillRect(Math.random()*w,Math.random()*h*0.5,2,2); }}
                requestAnimationFrame(draw);
            }} draw();""",

        "paper_fold": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Paper texture
            for(let i=0;i<5000;i++){{
                ctx.fillStyle='rgba(0,0,0,'+(Math.random()*0.03)+')';
                ctx.fillRect(Math.random()*w,Math.random()*h,1,1);
            }}
            // Fold lines
            ctx.strokeStyle='{primary}44'; ctx.lineWidth=1;
            for(let i=0;i<5;i++){{
                const y=h*(i+1)/6;
                ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(w,y); ctx.stroke();
                ctx.fillStyle='rgba(0,0,0,0.02)'; ctx.fillRect(0,y,w,3);
            }}""",
    }

    # Remaining animations - Part 2
    animations.update({
        "bubbles": f"""
            const bubbles=[];
            for(let i=0;i<60;i++) bubbles.push({{
                x:Math.random()*w, y:h+Math.random()*100, r:Math.random()*15+3,
                speed:Math.random()*1+0.5, wobble:Math.random()*Math.PI*2
            }});
            function draw(){{
                ctx.fillStyle='rgba(0,18,32,0.08)'; ctx.fillRect(0,0,w,h);
                // Water gradient
                const wg=ctx.createLinearGradient(0,0,0,h);
                wg.addColorStop(0,'{secondary}11'); wg.addColorStop(1,'{primary}22');
                ctx.fillStyle=wg; ctx.fillRect(0,0,w,h);
                bubbles.forEach(b=>{{
                    b.y-=b.speed; b.wobble+=0.02;
                    b.x+=Math.sin(b.wobble)*0.5;
                    if(b.y<-20){{ b.y=h+20; b.x=Math.random()*w; }}
                    ctx.beginPath(); ctx.arc(b.x,b.y,b.r,0,Math.PI*2);
                    ctx.strokeStyle='{accent}66'; ctx.lineWidth=1; ctx.stroke();
                    const bg=ctx.createRadialGradient(b.x-b.r*0.3,b.y-b.r*0.3,0,b.x,b.y,b.r);
                    bg.addColorStop(0,'{accent}33'); bg.addColorStop(1,'{accent}05');
                    ctx.fillStyle=bg; ctx.fill();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "starfield": f"""
            const stars=[];
            for(let i=0;i<300;i++) stars.push({{
                x:Math.random()*w-w/2, y:Math.random()*h-h/2, z:Math.random()*1000
            }});
            function draw(){{
                ctx.fillStyle='rgba(5,5,26,0.2)'; ctx.fillRect(0,0,w,h);
                stars.forEach(s=>{{
                    s.z-=2; if(s.z<1){{ s.z=1000; s.x=Math.random()*w-w/2; s.y=Math.random()*h-h/2; }}
                    const sx=s.x/s.z*400+w/2, sy=s.y/s.z*400+h/2;
                    const r=Math.max(0,(1-s.z/1000)*3);
                    ctx.beginPath(); ctx.arc(sx,sy,r,0,Math.PI*2);
                    ctx.fillStyle='rgba(255,255,255,'+(1-s.z/1000)+')'; ctx.fill();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "gears": f"""
            let t=0;
            function drawGear(cx,cy,r,teeth,rot){{
                ctx.beginPath();
                for(let i=0;i<teeth*2;i++){{
                    const a=rot+i*Math.PI/teeth;
                    const rr=i%2===0?r:r*0.75;
                    ctx.lineTo(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr);
                }}
                ctx.closePath(); ctx.strokeStyle='{primary}88'; ctx.lineWidth=2; ctx.stroke();
            }}
            function draw(){{
                t+=0.005; ctx.fillStyle='rgba(26,18,8,0.05)'; ctx.fillRect(0,0,w,h);
                drawGear(w*0.3,h*0.4,80,12,t);
                drawGear(w*0.55,h*0.35,60,10,-t*1.2);
                drawGear(w*0.7,h*0.55,90,14,t*0.8);
                drawGear(w*0.2,h*0.7,50,8,-t*1.5);
                requestAnimationFrame(draw);
            }} draw();""",

        "noir_grain": f"""
            function draw(){{
                ctx.fillStyle='rgba(10,10,10,0.3)'; ctx.fillRect(0,0,w,h);
                // Film grain
                const imgData=ctx.getImageData(0,0,w,h);
                for(let i=0;i<imgData.data.length;i+=4){{
                    const v=Math.random()*30-15;
                    imgData.data[i]+=v; imgData.data[i+1]+=v; imgData.data[i+2]+=v;
                }}
                ctx.putImageData(imgData,0,0);
                // Spotlight
                const sg=ctx.createRadialGradient(w/2,h*0.3,20,w/2,h*0.3,300);
                sg.addColorStop(0,'rgba(255,255,255,0.05)'); sg.addColorStop(1,'transparent');
                ctx.fillStyle=sg; ctx.fillRect(0,0,w,h);
                setTimeout(()=>requestAnimationFrame(draw),100);
            }} draw();""",

        "halftone": f"""
            let t=0;
            function draw(){{
                t+=0.02; ctx.fillStyle='#fff'; ctx.fillRect(0,0,w,h);
                for(let x=0;x<w;x+=20) for(let y=0;y<h;y+=20){{
                    const d=Math.sqrt((x-w/2)**2+(y-h/2)**2);
                    const r=Math.max(1,(1-d/(w*0.5))*8+Math.sin(t+d*0.01)*3);
                    ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2);
                    const colors=['{primary}','{secondary}','{accent}'];
                    ctx.fillStyle=colors[Math.floor((x+y)/40)%3]; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "zen_circles": f"""
            let t=0;
            function draw(){{
                t+=0.003; ctx.fillStyle='rgba(250,250,248,0.02)'; ctx.fillRect(0,0,w,h);
                ctx.strokeStyle='rgba(26,26,26,0.08)'; ctx.lineWidth=1;
                for(let i=0;i<5;i++){{
                    const r=50+i*60+Math.sin(t+i)*10;
                    ctx.beginPath(); ctx.arc(w/2,h/2,r,0,Math.PI*2); ctx.stroke();
                }}
                // Enso brush stroke
                ctx.beginPath();
                for(let a=0;a<Math.PI*1.8;a+=0.05){{
                    const r=120+Math.sin(a*3+t)*5;
                    ctx.lineTo(w/2+Math.cos(a+t*0.5)*r,h/2+Math.sin(a+t*0.5)*r);
                }}
                ctx.strokeStyle='rgba(26,26,26,0.15)'; ctx.lineWidth=3; ctx.stroke();
                requestAnimationFrame(draw);
            }} draw();""",

        "glitch": f"""
            let t=0;
            function draw(){{
                t++;
                ctx.fillStyle='rgba(10,10,10,0.1)'; ctx.fillRect(0,0,w,h);
                if(t%10<3){{ // Glitch frames
                    const sliceH=Math.random()*40+10;
                    const y=Math.random()*h;
                    const imgData=ctx.getImageData(0,y,w,sliceH);
                    ctx.putImageData(imgData,Math.random()*40-20,y+Math.random()*10-5);
                    ctx.fillStyle=Math.random()>0.5?'{primary}22':'{accent}22';
                    ctx.fillRect(0,Math.random()*h,w,Math.random()*5);
                }}
                // Scan lines
                for(let y=0;y<h;y+=4){{
                    ctx.fillStyle='rgba(0,0,0,0.03)'; ctx.fillRect(0,y,w,2);
                }}
                ctx.fillStyle='{primary}'; ctx.font='bold 80px sans-serif';
                ctx.globalAlpha=0.1;
                ctx.fillText('TORONTO',w/2-200+Math.random()*4,h/2+Math.random()*4);
                ctx.globalAlpha=1;
                requestAnimationFrame(draw);
            }} draw();""",

        "palm_leaves": f"""
            let t=0;
            function drawLeaf(x,y,size,angle){{
                ctx.save(); ctx.translate(x,y); ctx.rotate(angle);
                ctx.beginPath(); ctx.moveTo(0,0);
                ctx.quadraticCurveTo(size*0.5,-size*0.3,size,0);
                ctx.quadraticCurveTo(size*0.5,size*0.3,0,0);
                ctx.fillStyle='{accent}22'; ctx.fill();
                ctx.strokeStyle='{accent}44'; ctx.lineWidth=1; ctx.stroke();
                ctx.restore();
            }}
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(0,43,26,0.03)'; ctx.fillRect(0,0,w,h);
                for(let i=0;i<8;i++){{
                    drawLeaf(w*0.1+i*w*0.12, 50+Math.sin(t+i)*10, 80, Math.sin(t+i*0.5)*0.1+0.3);
                    drawLeaf(w*0.05+i*w*0.12, h-30+Math.sin(t+i+1)*8, 70, Math.PI+Math.sin(t+i*0.5)*0.1-0.3);
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "aurora": f"""
            let t=0;
            function draw(){{
                t+=0.008; ctx.fillStyle='rgba(2,8,16,0.05)'; ctx.fillRect(0,0,w,h);
                for(let band=0;band<4;band++){{
                    ctx.beginPath();
                    ctx.moveTo(0,h*0.3+band*30);
                    for(let x=0;x<w;x+=5){{
                        const y=h*0.3+band*30+Math.sin(x*0.005+t+band)*60+Math.sin(x*0.01+t*1.5)*30;
                        ctx.lineTo(x,y);
                    }}
                    ctx.lineTo(w,h); ctx.lineTo(0,h); ctx.closePath();
                    const colors=['{primary}15','{secondary}10','{accent}12','{primary}08'];
                    ctx.fillStyle=colors[band]; ctx.fill();
                }}
                // Stars
                for(let i=0;i<3;i++){{ ctx.fillStyle='rgba(255,255,255,'+Math.random()*0.5+')';
                    ctx.fillRect(Math.random()*w,Math.random()*h*0.4,1.5,1.5); }}
                requestAnimationFrame(draw);
            }} draw();""",
    })

    # Remaining animations - Part 3
    animations.update({
        "holographic": f"""
            let t=0;
            function draw(){{
                t+=0.015; ctx.fillStyle='rgba(10,10,20,0.08)'; ctx.fillRect(0,0,w,h);
                for(let i=0;i<150;i++){{
                    const x=w/2+Math.cos(t*0.5+i*0.1)*200*Math.sin(i*0.05+t);
                    const y=h/2+Math.sin(t*0.7+i*0.1)*150*Math.cos(i*0.03+t);
                    const hue=(i*3+t*50)%360;
                    ctx.beginPath(); ctx.arc(x,y,2,0,Math.PI*2);
                    ctx.fillStyle='hsl('+hue+',100%,70%)'; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "gold_particles": f"""
            const ps=[];
            for(let i=0;i<120;i++) ps.push({{
                x:Math.random()*w,y:Math.random()*h,
                vx:(Math.random()-0.5)*1.5,vy:(Math.random()-0.5)*1.5,
                r:Math.random()*2+1,a:Math.random()
            }});
            function draw(){{
                ctx.fillStyle='rgba(5,5,5,0.08)'; ctx.fillRect(0,0,w,h);
                ps.forEach(p=>{{
                    p.x+=p.vx; p.y+=p.vy; p.a+=0.01;
                    if(p.x<0||p.x>w) p.vx*=-1; if(p.y<0||p.y>h) p.vy*=-1;
                    ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
                    ctx.fillStyle='{primary}'; ctx.shadowColor='{primary}';
                    ctx.shadowBlur=10; ctx.fill(); ctx.shadowBlur=0;
                }});
                for(let i=0;i<ps.length;i++) for(let j=i+1;j<ps.length;j++){{
                    const dx=ps[i].x-ps[j].x,dy=ps[i].y-ps[j].y,d=Math.sqrt(dx*dx+dy*dy);
                    if(d<100){{ ctx.beginPath(); ctx.moveTo(ps[i].x,ps[i].y); ctx.lineTo(ps[j].x,ps[j].y);
                        ctx.strokeStyle='{primary}'+(Math.floor((1-d/100)*40)).toString(16).padStart(2,'0');
                        ctx.lineWidth=0.5; ctx.stroke(); }}
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "glass_panels": f"""
            let t=0;
            const panels=[];
            for(let i=0;i<8;i++) panels.push({{
                x:Math.random()*w*0.6+w*0.2, y:Math.random()*h*0.6+h*0.2,
                w:Math.random()*150+80, h2:Math.random()*100+60, speed:Math.random()*0.5+0.2
            }});
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(15,12,41,0.05)'; ctx.fillRect(0,0,w,h);
                panels.forEach((p,i)=>{{
                    p.x+=Math.sin(t*p.speed+i)*0.5; p.y+=Math.cos(t*p.speed+i)*0.3;
                    ctx.fillStyle='rgba(255,255,255,0.05)';
                    ctx.strokeStyle='rgba(255,255,255,0.1)'; ctx.lineWidth=1;
                    ctx.beginPath();
                    const rx=12;
                    ctx.roundRect(p.x,p.y,p.w,p.h2,rx);
                    ctx.fill(); ctx.stroke();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "neumorphic": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Subtle shapes
            function drawNeumorphic(x,y,r){{
                ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2);
                ctx.fillStyle='{bg_dark}'; ctx.fill();
                ctx.shadowColor='rgba(255,255,255,0.5)'; ctx.shadowBlur=10;
                ctx.shadowOffsetX=-5; ctx.shadowOffsetY=-5; ctx.fill();
                ctx.shadowColor='rgba(0,0,0,0.3)'; ctx.shadowOffsetX=5; ctx.shadowOffsetY=5; ctx.fill();
                ctx.shadowBlur=0; ctx.shadowOffsetX=0; ctx.shadowOffsetY=0;
            }}
            for(let i=0;i<12;i++) drawNeumorphic(Math.random()*w,Math.random()*h,Math.random()*30+10);""",

        "tokyo_rain": f"""
            const drops=[];
            for(let i=0;i<200;i++) drops.push({{
                x:Math.random()*w, y:Math.random()*h, speed:Math.random()*5+2, len:Math.random()*20+10
            }});
            function draw(){{
                ctx.fillStyle='rgba(10,0,20,0.15)'; ctx.fillRect(0,0,w,h);
                drops.forEach(d=>{{
                    d.y+=d.speed; if(d.y>h){{ d.y=-d.len; d.x=Math.random()*w; }}
                    const g=ctx.createLinearGradient(d.x,d.y,d.x,d.y+d.len);
                    g.addColorStop(0,Math.random()>0.5?'{primary}':'{secondary}');
                    g.addColorStop(1,'transparent');
                    ctx.strokeStyle=g; ctx.lineWidth=1.5;
                    ctx.beginPath(); ctx.moveTo(d.x,d.y); ctx.lineTo(d.x,d.y+d.len); ctx.stroke();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "terminal": f"""
            let line=0; const lines=['C:\\\\TORONTO> dir events /s','','Scanning... 2,847 events found.','','[OK] Loading event database...','[OK] Filters initialized.','[OK] Toronto Events System v2.0','','Ready.'];
            ctx.fillStyle='#0a0a0a'; ctx.fillRect(0,0,w,h);
            ctx.font='14px "Fira Code", monospace';
            function typeNext(){{
                if(line>=lines.length){{ line=0; ctx.fillStyle='#0a0a0a'; ctx.fillRect(0,0,w,h); }}
                ctx.fillStyle='{primary}'; ctx.fillText(lines[line],20,30+line*22);
                line++; setTimeout(typeNext,500);
            }} typeNext();
            // Cursor blink
            setInterval(()=>{{ ctx.fillStyle=ctx.fillStyle==='{primary}'?'#0a0a0a':'{primary}';
                ctx.fillRect(20+lines[Math.min(line,lines.length-1)].length*8.4,15+line*22,10,16); }},500);""",

        "watercolor": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            function blob(x,y,r,color){{
                for(let i=0;i<20;i++){{
                    ctx.beginPath();
                    ctx.arc(x+Math.random()*r-r/2, y+Math.random()*r-r/2, Math.random()*r*0.8, 0, Math.PI*2);
                    ctx.fillStyle=color+'08'; ctx.fill();
                }}
            }}
            blob(w*0.3,h*0.4,120,'{primary}'); blob(w*0.6,h*0.3,100,'{secondary}');
            blob(w*0.5,h*0.6,140,'{accent}'); blob(w*0.7,h*0.7,80,'{primary}');""",

        "triangles": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(10,10,20,0.05)'; ctx.fillRect(0,0,w,h);
                const colors=['{primary}','{secondary}','{accent}'];
                for(let i=0;i<6;i++){{
                    const cx=w/2+Math.cos(t+i*Math.PI/3)*150;
                    const cy=h/2+Math.sin(t+i*Math.PI/3)*150;
                    const s=40+Math.sin(t*2+i)*15;
                    ctx.beginPath();
                    for(let j=0;j<3;j++){{
                        const a=t*0.5+j*Math.PI*2/3+i;
                        ctx.lineTo(cx+Math.cos(a)*s,cy+Math.sin(a)*s);
                    }}
                    ctx.closePath(); ctx.strokeStyle=colors[i%3]+'88'; ctx.lineWidth=2; ctx.stroke();
                    ctx.fillStyle=colors[i%3]+'11'; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "gradient_mesh": f"""
            let t=0;
            function draw(){{
                t+=0.005;
                const g1=ctx.createRadialGradient(w*0.3+Math.sin(t)*100,h*0.4+Math.cos(t)*100,0,w/2,h/2,w*0.7);
                g1.addColorStop(0,'{primary}44'); g1.addColorStop(0.5,'{secondary}22'); g1.addColorStop(1,'{accent}11');
                ctx.fillStyle='rgba(10,0,20,0.03)'; ctx.fillRect(0,0,w,h);
                ctx.fillStyle=g1; ctx.fillRect(0,0,w,h);
                const g2=ctx.createRadialGradient(w*0.7+Math.cos(t*1.3)*80,h*0.6+Math.sin(t*0.7)*80,0,w/2,h/2,w*0.5);
                g2.addColorStop(0,'{accent}33'); g2.addColorStop(1,'transparent');
                ctx.fillStyle=g2; ctx.fillRect(0,0,w,h);
                requestAnimationFrame(draw);
            }} draw();""",

        "fire_particles": f"""
            const ps=[];
            for(let i=0;i<100;i++) ps.push({{
                x:w/2+Math.random()*200-100, y:h, vx:(Math.random()-0.5)*2,
                vy:-Math.random()*3-1, life:Math.random()*60+30, maxLife:90, r:Math.random()*4+2
            }});
            function draw(){{
                ctx.fillStyle='rgba(26,8,0,0.12)'; ctx.fillRect(0,0,w,h);
                ps.forEach(p=>{{
                    p.x+=p.vx; p.y+=p.vy; p.vy-=0.01; p.life--;
                    if(p.life<0){{ p.x=w/2+Math.random()*200-100; p.y=h; p.life=p.maxLife; p.vy=-Math.random()*3-1; }}
                    const pct=p.life/p.maxLife;
                    ctx.beginPath(); ctx.arc(p.x,p.y,p.r*pct,0,Math.PI*2);
                    ctx.fillStyle=pct>0.5?'{accent}':'rgba(255,69,0,'+(pct)+')';
                    ctx.shadowColor='{accent}'; ctx.shadowBlur=10; ctx.fill(); ctx.shadowBlur=0;
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "snowflakes": f"""
            const flakes=[];
            for(let i=0;i<200;i++) flakes.push({{
                x:Math.random()*w, y:Math.random()*h, r:Math.random()*3+1,
                speed:Math.random()*1+0.3, wobble:Math.random()*Math.PI*2
            }});
            function draw(){{
                ctx.fillStyle='rgba(8,24,40,0.08)'; ctx.fillRect(0,0,w,h);
                flakes.forEach(f=>{{
                    f.y+=f.speed; f.wobble+=0.01; f.x+=Math.sin(f.wobble)*0.5;
                    if(f.y>h){{ f.y=-5; f.x=Math.random()*w; }}
                    ctx.beginPath(); ctx.arc(f.x,f.y,f.r,0,Math.PI*2);
                    ctx.fillStyle='rgba(255,255,255,'+(0.3+f.r/6)+')'; ctx.fill();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "psychedelic": f"""
            let t=0;
            function draw(){{
                t+=0.02;
                for(let x=0;x<w;x+=8) for(let y=0;y<h;y+=8){{
                    const d=Math.sqrt((x-w/2)**2+(y-h/2)**2);
                    const hue=(d*0.5+t*100)%360;
                    ctx.fillStyle='hsl('+hue+',80%,50%)';
                    ctx.globalAlpha=0.1; ctx.fillRect(x,y,8,8);
                }}
                ctx.globalAlpha=1;
                requestAnimationFrame(draw);
            }} draw();""",

        "bauhaus": f"""
            ctx.fillStyle='#f8f8f8'; ctx.fillRect(0,0,w,h);
            const colors=['{primary}','{secondary}','{accent}'];
            // Geometric shapes
            ctx.fillStyle='{primary}22'; ctx.beginPath(); ctx.arc(w*0.3,h*0.4,120,0,Math.PI*2); ctx.fill();
            ctx.fillStyle='{secondary}22'; ctx.fillRect(w*0.5,h*0.2,200,200);
            ctx.fillStyle='{accent}22'; ctx.beginPath(); ctx.moveTo(w*0.7,h*0.7); ctx.lineTo(w*0.85,h*0.9); ctx.lineTo(w*0.55,h*0.9); ctx.fill();
            // Grid lines
            ctx.strokeStyle='#00000011'; ctx.lineWidth=1;
            for(let x=0;x<w;x+=80){{ ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,h); ctx.stroke(); }}
            for(let y=0;y<h;y+=80){{ ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(w,y); ctx.stroke(); }}""",
    })

    # Remaining animations - Part 4
    animations.update({
        "rain": f"""
            const drops=[];
            for(let i=0;i<300;i++) drops.push({{
                x:Math.random()*w, y:Math.random()*h, speed:Math.random()*8+4, len:Math.random()*15+5
            }});
            function draw(){{
                ctx.fillStyle='rgba(5,5,16,0.15)'; ctx.fillRect(0,0,w,h);
                ctx.strokeStyle='{primary}44'; ctx.lineWidth=1;
                drops.forEach(d=>{{
                    d.y+=d.speed; if(d.y>h){{ d.y=-d.len; d.x=Math.random()*w; }}
                    ctx.beginPath(); ctx.moveTo(d.x,d.y); ctx.lineTo(d.x-1,d.y+d.len); ctx.stroke();
                }});
                // Neon reflections at bottom
                ctx.fillStyle='{secondary}08'; ctx.fillRect(0,h*0.85,w,h*0.15);
                requestAnimationFrame(draw);
            }} draw();""",

        "organic": f"""
            let t=0;
            function draw(){{
                t+=0.003; ctx.fillStyle='rgba(26,21,16,0.02)'; ctx.fillRect(0,0,w,h);
                ctx.strokeStyle='{secondary}22'; ctx.lineWidth=2;
                for(let i=0;i<8;i++){{
                    ctx.beginPath();
                    for(let a=0;a<Math.PI*2;a+=0.1){{
                        const r=80+Math.sin(a*3+t+i)*30+Math.sin(a*5+t*2)*15;
                        ctx.lineTo(w*0.3+i*w*0.06+Math.cos(a)*r,h/2+Math.sin(a)*r);
                    }}
                    ctx.closePath(); ctx.stroke();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "memphis": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(26,16,40,0.05)'; ctx.fillRect(0,0,w,h);
                const colors=['{primary}','{secondary}','{accent}'];
                // Squiggles
                for(let i=0;i<5;i++){{
                    ctx.beginPath(); ctx.strokeStyle=colors[i%3]+'66'; ctx.lineWidth=3;
                    for(let x=0;x<100;x+=5){{
                        ctx.lineTo(100+i*150+x, 100+i*80+Math.sin(x*0.1+t+i)*20);
                    }}
                    ctx.stroke();
                }}
                // Dots
                for(let i=0;i<10;i++){{
                    ctx.beginPath(); ctx.arc(50+i*80+Math.sin(t+i)*10,h-100+Math.cos(t+i)*10,5,0,Math.PI*2);
                    ctx.fillStyle=colors[i%3]+'44'; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "isometric": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(10,16,32,0.05)'; ctx.fillRect(0,0,w,h);
                const size=30; ctx.strokeStyle='{primary}33'; ctx.lineWidth=0.5;
                for(let x=-5;x<15;x++) for(let y=-5;y<15;y++){{
                    const ix=w/2+(x-y)*size*1.5;
                    const iy=h*0.3+(x+y)*size*0.75;
                    const hh=Math.sin(x*0.5+y*0.5+t)*size*0.5;
                    // Top face
                    ctx.beginPath(); ctx.moveTo(ix,iy-hh); ctx.lineTo(ix+size*1.5,iy+size*0.75-hh);
                    ctx.lineTo(ix,iy+size*1.5-hh); ctx.lineTo(ix-size*1.5,iy+size*0.75-hh); ctx.closePath();
                    ctx.fillStyle='{primary}0a'; ctx.fill(); ctx.stroke();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "newspaper": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            ctx.strokeStyle='#2c181022'; ctx.lineWidth=1;
            for(let y=0;y<h;y+=18){{ ctx.beginPath(); ctx.moveTo(40,y); ctx.lineTo(w-40,y); ctx.stroke(); }}
            // Column dividers
            ctx.strokeStyle='#2c181033'; ctx.lineWidth=2;
            ctx.beginPath(); ctx.moveTo(w/3,60); ctx.lineTo(w/3,h-60); ctx.stroke();
            ctx.beginPath(); ctx.moveTo(w*2/3,60); ctx.lineTo(w*2/3,h-60); ctx.stroke();""",

        "wireframe": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(5,5,16,0.1)'; ctx.fillRect(0,0,w,h);
                // 3D wireframe cube rotation
                const pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];
                const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];
                const s=100;
                const proj=pts.map(([x,y,z])=>{{
                    const rx=x*Math.cos(t)-z*Math.sin(t);
                    const rz=x*Math.sin(t)+z*Math.cos(t);
                    const ry=y*Math.cos(t*0.7)-rz*Math.sin(t*0.7);
                    const rz2=y*Math.sin(t*0.7)+rz*Math.cos(t*0.7);
                    const scale=300/(300+rz2*s);
                    return [w/2+rx*s*scale,h/2+ry*s*scale];
                }});
                edges.forEach(([a,b])=>{{
                    ctx.beginPath(); ctx.moveTo(proj[a][0],proj[a][1]); ctx.lineTo(proj[b][0],proj[b][1]);
                    ctx.strokeStyle='{primary}'; ctx.lineWidth=2; ctx.shadowColor='{primary}';
                    ctx.shadowBlur=10; ctx.stroke(); ctx.shadowBlur=0;
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "candy": f"""
            let t=0;
            function draw(){{
                t+=0.005; ctx.fillStyle='rgba(255,245,247,0.03)'; ctx.fillRect(0,0,w,h);
                for(let i=0;i<20;i++){{
                    const x=w/2+Math.cos(t+i*0.3)*200;
                    const y=h/2+Math.sin(t*1.3+i*0.3)*150;
                    ctx.beginPath(); ctx.arc(x,y,20+Math.sin(t+i)*10,0,Math.PI*2);
                    const colors=['{primary}22','{secondary}22','{accent}22'];
                    ctx.fillStyle=colors[i%3]; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "steel": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Brushed metal texture
            for(let i=0;i<2000;i++){{
                const y=Math.random()*h;
                ctx.strokeStyle='rgba(176,196,222,'+(Math.random()*0.05)+')';
                ctx.lineWidth=1;
                ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(w,y+Math.random()*2); ctx.stroke();
            }}
            // Rivets
            for(let x=50;x<w;x+=100) for(let y=50;y<h;y+=100){{
                ctx.beginPath(); ctx.arc(x,y,4,0,Math.PI*2);
                ctx.fillStyle='#70809055'; ctx.fill();
                ctx.strokeStyle='#50607033'; ctx.lineWidth=1; ctx.stroke();
            }}""",

        "sunset": f"""
            let t=0;
            function draw(){{
                t+=0.005;
                const g=ctx.createLinearGradient(0,0,0,h);
                g.addColorStop(0,'#1a0e08'); g.addColorStop(0.3,'{primary}44'); g.addColorStop(0.5,'{secondary}33'); g.addColorStop(1,'#1a0e08');
                ctx.fillStyle=g; ctx.fillRect(0,0,w,h);
                // Sun
                ctx.beginPath(); ctx.arc(w/2,h*0.4,80,0,Math.PI*2);
                const sg=ctx.createRadialGradient(w/2,h*0.4,0,w/2,h*0.4,80);
                sg.addColorStop(0,'{secondary}'); sg.addColorStop(1,'{primary}44');
                ctx.fillStyle=sg; ctx.fill();
                // Waves
                ctx.strokeStyle='{primary}44';
                for(let i=0;i<5;i++){{
                    ctx.beginPath();
                    for(let x=0;x<w;x+=5){{
                        ctx.lineTo(x, h*0.65+i*25+Math.sin(x*0.02+t+i)*15);
                    }}
                    ctx.stroke();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "nebula": f"""
            let t=0;
            function draw(){{
                t+=0.003; ctx.fillStyle='rgba(5,5,8,0.03)'; ctx.fillRect(0,0,w,h);
                for(let i=0;i<3;i++){{
                    const g=ctx.createRadialGradient(
                        w/2+Math.cos(t+i*2)*200, h/2+Math.sin(t+i*2)*150, 0,
                        w/2, h/2, 300);
                    const colors=['{primary}','{secondary}','{accent}'];
                    g.addColorStop(0,colors[i]+'15'); g.addColorStop(1,'transparent');
                    ctx.fillStyle=g; ctx.fillRect(0,0,w,h);
                }}
                // Stars
                for(let i=0;i<2;i++){{ ctx.fillStyle='rgba(255,255,255,'+Math.random()*0.6+')';
                    ctx.fillRect(Math.random()*w,Math.random()*h,1.5,1.5); }}
                requestAnimationFrame(draw);
            }} draw();""",

        "film_strip": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Film strip borders
            ctx.fillStyle='#1a1a1a';
            ctx.fillRect(0,0,60,h); ctx.fillRect(w-60,0,60,h);
            // Perforations
            for(let y=20;y<h;y+=40){{
                ctx.fillStyle='#0a0808';
                ctx.fillRect(15,y,30,20); ctx.fillRect(w-45,y,30,20);
            }}
            // Frames
            ctx.strokeStyle='{primary}33'; ctx.lineWidth=1;
            for(let y=0;y<h;y+=200){{
                ctx.strokeRect(70,y+10,w-140,180);
            }}""",

        "liquid": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(10,10,20,0.08)'; ctx.fillRect(0,0,w,h);
                for(let i=0;i<5;i++){{
                    ctx.beginPath();
                    for(let a=0;a<Math.PI*2;a+=0.05){{
                        const r=80+Math.sin(a*3+t+i)*30+Math.sin(a*7+t*2)*15+Math.sin(a*11+t*3)*8;
                        ctx.lineTo(w/2+i*30-60+Math.cos(a)*r, h/2+Math.sin(a)*r);
                    }}
                    ctx.closePath();
                    ctx.strokeStyle='{primary}'+(30+i*10).toString(16); ctx.lineWidth=2; ctx.stroke();
                    ctx.fillStyle='{primary}05'; ctx.fill();
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "botanical": f"""
            let t=0;
            function drawBranch(x,y,len,angle,depth){{
                if(depth<=0||len<5) return;
                const ex=x+Math.cos(angle)*len, ey=y+Math.sin(angle)*len;
                ctx.beginPath(); ctx.moveTo(x,y); ctx.lineTo(ex,ey);
                ctx.strokeStyle='{primary}'+(20+depth*15).toString(16).padStart(2,'0');
                ctx.lineWidth=depth; ctx.stroke();
                drawBranch(ex,ey,len*0.7,angle-0.4+Math.sin(t)*0.1,depth-1);
                drawBranch(ex,ey,len*0.7,angle+0.4+Math.cos(t)*0.1,depth-1);
            }}
            function draw(){{
                t+=0.003; ctx.fillStyle='rgba(10,26,10,0.02)'; ctx.fillRect(0,0,w,h);
                drawBranch(w/2,h,80,-Math.PI/2,7);
                requestAnimationFrame(draw);
            }} draw();""",

        "moonlight": f"""
            let t=0;
            function draw(){{
                t+=0.005; ctx.fillStyle='rgba(8,8,16,0.05)'; ctx.fillRect(0,0,w,h);
                // Moon
                const mg=ctx.createRadialGradient(w*0.7,h*0.25,30,w*0.7,h*0.25,80);
                mg.addColorStop(0,'rgba(230,230,250,0.3)'); mg.addColorStop(1,'transparent');
                ctx.fillStyle=mg; ctx.fillRect(0,0,w,h);
                ctx.beginPath(); ctx.arc(w*0.7,h*0.25,40,0,Math.PI*2);
                ctx.fillStyle='rgba(230,230,250,0.2)'; ctx.fill();
                // Stars twinkle
                for(let i=0;i<5;i++){{
                    const brightness=0.3+Math.sin(t*3+i)*0.2;
                    ctx.fillStyle='rgba(255,255,255,'+brightness+')';
                    ctx.fillRect(100+i*150+Math.sin(i)*50, 50+i*40+Math.cos(i)*30, 2, 2);
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "lightning": f"""
            let t=0; let flash=0;
            function drawBolt(x1,y1,x2,y2,depth){{
                if(depth<=0)return;
                const mx=(x1+x2)/2+Math.random()*60-30;
                const my=(y1+y2)/2+Math.random()*60-30;
                ctx.beginPath(); ctx.moveTo(x1,y1); ctx.lineTo(mx,my); ctx.lineTo(x2,y2);
                ctx.strokeStyle='{primary}'; ctx.lineWidth=depth; ctx.shadowColor='{primary}';
                ctx.shadowBlur=20; ctx.stroke(); ctx.shadowBlur=0;
                if(depth>1){{ drawBolt(x1,y1,mx,my,depth-1); drawBolt(mx,my,x2,y2,depth-1); }}
            }}
            function draw(){{
                t++; ctx.fillStyle='rgba(5,5,8,0.2)'; ctx.fillRect(0,0,w,h);
                if(t%60===0||flash>0){{
                    if(flash===0){{ flash=5; drawBolt(Math.random()*w,0,Math.random()*w,h,4); }}
                    else{{ flash--; ctx.fillStyle='rgba(255,255,255,'+(flash*0.02)+')'; ctx.fillRect(0,0,w,h); }}
                }}
                requestAnimationFrame(draw);
            }} draw();""",

        "polaroid": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Scattered polaroids
            for(let i=0;i<6;i++){{
                ctx.save();
                const x=100+i*120+Math.random()*50;
                const y=80+Math.random()*200;
                ctx.translate(x,y); ctx.rotate(Math.random()*0.3-0.15);
                // White border
                ctx.fillStyle='#fff'; ctx.shadowColor='rgba(0,0,0,0.2)';
                ctx.shadowBlur=15; ctx.shadowOffsetY=5;
                ctx.fillRect(-50,-50,100,120);
                ctx.shadowBlur=0;
                // Photo area
                const colors=['{primary}44','{secondary}44','{accent}44'];
                ctx.fillStyle=colors[i%3]; ctx.fillRect(-40,-40,80,80);
                ctx.restore();
            }}""",

        "coral": f"""
            const ps=[];
            for(let i=0;i<80;i++) ps.push({{
                x:Math.random()*w, y:Math.random()*h,
                vx:(Math.random()-0.5)*0.5, vy:Math.random()*-0.5-0.2,
                r:Math.random()*4+2, color:Math.random()>0.5?'{primary}':'{secondary}'
            }});
            function draw(){{
                ctx.fillStyle='rgba(8,21,32,0.06)'; ctx.fillRect(0,0,w,h);
                // Water caustics
                const wg=ctx.createLinearGradient(0,0,0,h);
                wg.addColorStop(0,'rgba(32,178,170,0.03)'); wg.addColorStop(1,'rgba(8,21,32,0.01)');
                ctx.fillStyle=wg; ctx.fillRect(0,0,w,h);
                ps.forEach(p=>{{
                    p.x+=p.vx; p.y+=p.vy;
                    if(p.y<-10){{ p.y=h+10; p.x=Math.random()*w; }}
                    if(p.x<0||p.x>w) p.vx*=-1;
                    ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
                    ctx.fillStyle=p.color+'66'; ctx.fill();
                }});
                requestAnimationFrame(draw);
            }} draw();""",

        "stained_glass": f"""
            ctx.fillStyle='{bg_dark}'; ctx.fillRect(0,0,w,h);
            // Generate Voronoi-like cells
            const pts=[];
            for(let i=0;i<30;i++) pts.push([Math.random()*w,Math.random()*h]);
            const colors=['{primary}33','{secondary}33','{accent}33','#ffaa0033','#aa00ff33','#00ffaa33'];
            for(let x=0;x<w;x+=4) for(let y=0;y<h;y+=4){{
                let minD=Infinity, minI=0;
                pts.forEach((p,i)=>{{ const d=(x-p[0])**2+(y-p[1])**2; if(d<minD){{ minD=d; minI=i; }} }});
                ctx.fillStyle=colors[minI%colors.length]; ctx.fillRect(x,y,4,4);
            }}
            // Black leading
            ctx.strokeStyle='#00000088'; ctx.lineWidth=2;
            pts.forEach(p=>{{ ctx.beginPath(); ctx.arc(p[0],p[1],3,0,Math.PI*2); ctx.stroke(); }});""",

        "future": f"""
            let t=0;
            function draw(){{
                t+=0.01; ctx.fillStyle='rgba(5,5,8,0.06)'; ctx.fillRect(0,0,w,h);
                // Scanning line
                const scanY=(t*100)%h;
                ctx.fillStyle='{accent}11'; ctx.fillRect(0,scanY,w,2);
                // Floating data points
                for(let i=0;i<40;i++){{
                    const x=w/2+Math.cos(t+i*0.15)*300*Math.sin(i*0.1);
                    const y=h/2+Math.sin(t*0.7+i*0.15)*200*Math.cos(i*0.07);
                    ctx.beginPath(); ctx.arc(x,y,1.5,0,Math.PI*2);
                    ctx.fillStyle=i%3===0?'{secondary}88':'{accent}88'; ctx.fill();
                }}
                // HUD corners
                ctx.strokeStyle='{accent}33'; ctx.lineWidth=1;
                [[20,20,40,0,0,40],[w-20,20,-40,0,0,40],[20,h-20,40,0,0,-40],[w-20,h-20,-40,0,0,-40]].forEach(([x,y,dx,dy,dx2,dy2])=>{{
                    ctx.beginPath(); ctx.moveTo(x+dx,y+dy); ctx.lineTo(x,y); ctx.lineTo(x+dx2,y+dy2); ctx.stroke();
                }});
                requestAnimationFrame(draw);
            }} draw();""",
    })

    return animations.get(anim_type, animations["starfield"])


def generate_html(num, name, subtitle, primary, secondary, accent, bg_dark, bg_light, font_import, title_font, anim_type):
    """Generate a complete themed HTML page."""

    # Calculate prev/next navigation
    all_nums = [t[0] for t in THEMES]
    idx = all_nums.index(num)
    prev_num = all_nums[idx - 1] if idx > 0 else all_nums[-1]
    next_num = all_nums[idx + 1] if idx < len(all_nums) - 1 else all_nums[0]

    # Determine if light or dark theme
    is_light = anim_type in ("brutalist", "bauhaus", "paper_fold", "watercolor", "candy", "neumorphic", "newspaper", "polaroid", "zen_circles")
    text_primary = "#1a1a1a" if is_light else "#f0f0f0"
    text_secondary = "#555555" if is_light else "#a0a0a0"
    text_muted = "#888888" if is_light else "#666666"
    card_bg = "rgba(0,0,0,0.03)" if is_light else "rgba(255,255,255,0.05)"
    card_border = "rgba(0,0,0,0.08)" if is_light else "rgba(255,255,255,0.08)"
    nav_bg = "rgba(255,255,255,0.9)" if is_light else "rgba(10,10,10,0.9)"
    overlay_bg = "rgba(255,255,255,0.95)" if is_light else "rgba(10,10,14,0.95)"
    input_bg = "rgba(0,0,0,0.05)" if is_light else "rgba(255,255,255,0.08)"

    animation_js = get_animation_js(anim_type, primary, secondary, accent, bg_dark, bg_light)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toronto Events - {name} Theme | Find Events in Toronto</title>
    <meta name="description" content="Discover events in Toronto with our {name} themed experience. Filter, search, and explore things to do in Toronto this weekend.">
    <meta name="keywords" content="Toronto Events, Events in Toronto, Things to do in Toronto, {name}">
    <link rel="canonical" href="https://findtorontoevents.ca/blog/blog{num}.html">
    <link rel="icon" href="/favicon.ico" sizes="256x256" type="image/x-icon">
    <!-- Generated by Claude Code VS Code - Anthropic CLI for Claude -->
    <!-- Theme #{num}: {name} - {subtitle} -->

    <meta property="og:title" content="Toronto Events - {name} Theme">
    <meta property="og:description" content="Discover events in Toronto with our {name} themed experience.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://findtorontoevents.ca/blog/blog{num}.html">
    <meta property="og:image" content="https://findtorontoevents.ca/blog/images/events-in-toronto.jpg">
    <meta property="og:site_name" content="Toronto Events">
    <meta property="og:locale" content="en_CA">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Toronto Events - {name}">
    <meta name="twitter:description" content="Discover events in Toronto with our {name} themed experience.">

    <meta name="geo.region" content="CA-ON">
    <meta name="geo.placename" content="Toronto">

    <script type="application/ld+json">
    {{
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": "Toronto Events - {name} Theme",
        "description": "Discover events in Toronto with our {name} themed experience.",
        "url": "https://findtorontoevents.ca/blog/blog{num}.html"
    }}
    </script>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7893721225790912" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family={font_import}&display=swap" rel="stylesheet">

    <style>
        :root {{
            --primary: {primary};
            --secondary: {secondary};
            --accent: {accent};
            --bg-dark: {bg_dark};
            --bg-light: {bg_light};
            --text-1: {text_primary};
            --text-2: {text_secondary};
            --text-3: {text_muted};
            --card-bg: {card_bg};
            --card-border: {card_border};
            --nav-bg: {nav_bg};
            --overlay-bg: {overlay_bg};
            --input-bg: {input_bg};
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg-dark);
            color: var(--text-1);
            line-height: 1.6;
            min-height: 100vh;
            overflow-x: hidden;
        }}

        /* ===== CANVAS BACKGROUND ===== */
        #bg-canvas {{
            position: fixed;
            top: 0; left: 0;
            width: 100%; height: 100%;
            z-index: 0;
            pointer-events: none;
        }}

        /* ===== NAVIGATION ===== */
        .top-nav {{
            position: fixed; top: 0; left: 0; right: 0; z-index: 1000;
            background: var(--nav-bg);
            backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px);
            border-bottom: 1px solid var(--card-border);
            padding: 0.6rem 1.5rem;
            display: flex; align-items: center; justify-content: space-between;
        }}
        .nav-brand {{
            font-family: '{title_font}', sans-serif;
            font-weight: 900; font-size: 1.1rem;
            color: var(--text-1); text-decoration: none;
        }}
        .nav-brand span {{ color: var(--primary); }}
        .nav-links {{ display: flex; gap: 1rem; align-items: center; }}
        .nav-links a {{
            font-size: 0.75rem; font-weight: 600; text-transform: uppercase;
            letter-spacing: 0.08em; color: var(--text-2); text-decoration: none;
            transition: color 0.2s;
        }}
        .nav-links a:hover {{ color: var(--primary); }}
        .nav-links a.active {{ color: var(--primary); }}
        .theme-badge {{
            font-size: 0.6rem; font-weight: 800;
            padding: 0.2rem 0.6rem; border-radius: 999px;
            background: var(--primary); color: var(--bg-dark);
            text-transform: uppercase; letter-spacing: 0.05em;
        }}

        /* ===== HERO ===== */
        .hero {{
            position: relative; z-index: 1;
            min-height: 70vh;
            display: flex; flex-direction: column;
            align-items: center; justify-content: center;
            text-align: center;
            padding: 6rem 1.5rem 3rem;
        }}
        .hero-sub {{
            font-size: 0.85rem; letter-spacing: 4px;
            text-transform: uppercase; font-weight: 700;
            color: var(--primary); opacity: 0.8;
            margin-bottom: 0.5rem;
        }}
        .hero-title {{
            font-family: '{title_font}', sans-serif;
            font-size: clamp(2.5rem, 7vw, 5rem);
            font-weight: 900; line-height: 1;
            letter-spacing: -2px;
            margin-bottom: 1rem;
            color: var(--text-1);
        }}
        .hero-desc {{
            font-size: 1.1rem; color: var(--text-2);
            max-width: 600px; margin-bottom: 2rem;
        }}

        /* ===== SEARCH BAR ===== */
        .search-container {{
            position: relative; z-index: 1;
            max-width: 700px; width: 100%;
            margin: 0 auto 2rem; padding: 0 1.5rem;
        }}
        .search-bar {{
            display: flex; gap: 0.5rem;
            background: var(--overlay-bg);
            border: 1px solid var(--card-border);
            border-radius: 16px;
            padding: 0.5rem;
            backdrop-filter: blur(20px);
        }}
        .search-bar input {{
            flex: 1; background: var(--input-bg);
            border: none; border-radius: 12px;
            padding: 0.75rem 1rem;
            color: var(--text-1); font-size: 0.95rem;
            outline: none;
        }}
        .search-bar input::placeholder {{ color: var(--text-3); }}
        .search-bar button {{
            background: var(--primary); color: var(--bg-dark);
            border: none; border-radius: 12px;
            padding: 0.75rem 1.5rem;
            font-weight: 700; font-size: 0.85rem;
            cursor: pointer; transition: all 0.2s;
            text-transform: uppercase; letter-spacing: 0.05em;
        }}
        .search-bar button:hover {{ opacity: 0.85; transform: scale(1.02); }}

        /* ===== FILTERS ===== */
        .filters {{
            position: relative; z-index: 1;
            max-width: 900px; margin: 0 auto 2rem;
            padding: 0 1.5rem;
            display: flex; flex-wrap: wrap; gap: 0.5rem;
            justify-content: center;
        }}
        .filter-btn {{
            padding: 0.45rem 1rem; border-radius: 999px;
            border: 1px solid var(--card-border);
            background: var(--card-bg);
            color: var(--text-2); font-size: 0.75rem;
            font-weight: 600; cursor: pointer;
            transition: all 0.2s; text-transform: uppercase;
            letter-spacing: 0.03em;
        }}
        .filter-btn:hover {{ border-color: var(--primary); color: var(--primary); }}
        .filter-btn.active {{
            background: var(--primary); color: var(--bg-dark);
            border-color: var(--primary);
        }}

        /* ===== EVENT GRID ===== */
        .events-section {{
            position: relative; z-index: 1;
            max-width: 1200px; margin: 0 auto;
            padding: 0 1.5rem 3rem;
        }}
        .events-header {{
            display: flex; justify-content: space-between;
            align-items: center; margin-bottom: 1.5rem;
        }}
        .events-header h2 {{
            font-family: '{title_font}', sans-serif;
            font-size: 1.4rem; font-weight: 800;
        }}
        .events-count {{
            font-size: 0.8rem; color: var(--text-3);
            font-weight: 600;
        }}
        .events-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: 1.25rem;
        }}
        .event-card {{
            background: var(--overlay-bg);
            border: 1px solid var(--card-border);
            border-radius: 16px;
            overflow: hidden;
            transition: all 0.3s ease;
            backdrop-filter: blur(10px);
            cursor: pointer;
        }}
        .event-card:hover {{
            transform: translateY(-4px);
            border-color: var(--primary);
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }}
        .event-card-img {{
            height: 160px; width: 100%;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            display: flex; align-items: center; justify-content: center;
            font-size: 3rem; position: relative; overflow: hidden;
        }}
        .event-card-img::after {{
            content: ''; position: absolute; inset: 0;
            background: linear-gradient(to top, var(--bg-dark), transparent 60%);
        }}
        .event-card-body {{ padding: 1rem 1.25rem; }}
        .event-card-tag {{
            display: inline-block; font-size: 0.6rem;
            font-weight: 800; text-transform: uppercase;
            letter-spacing: 0.08em; padding: 0.2rem 0.5rem;
            border-radius: 999px;
            background: {primary}22; color: var(--primary);
            margin-bottom: 0.5rem;
        }}
        .event-card-title {{
            font-size: 1rem; font-weight: 700;
            margin-bottom: 0.4rem; line-height: 1.3;
        }}
        .event-card-meta {{
            font-size: 0.75rem; color: var(--text-3);
            display: flex; gap: 0.75rem; flex-wrap: wrap;
        }}
        .event-card-meta span {{ display: flex; align-items: center; gap: 0.25rem; }}

        /* ===== LOADING ===== */
        .loading {{
            text-align: center; padding: 3rem;
            color: var(--text-3); font-size: 0.9rem;
        }}
        .loading-spinner {{
            width: 40px; height: 40px; border: 3px solid var(--card-border);
            border-top-color: var(--primary); border-radius: 50%;
            animation: spin 0.8s linear infinite;
            margin: 0 auto 1rem;
        }}
        @keyframes spin {{ to {{ transform: rotate(360deg); }} }}

        /* ===== NAVIGATION ARROWS ===== */
        .blog-nav {{
            position: fixed; z-index: 999;
            top: 50%; transform: translateY(-50%);
            display: flex; flex-direction: column; gap: 0.5rem;
        }}
        .blog-nav.left {{ left: 10px; }}
        .blog-nav.right {{ right: 10px; }}
        .blog-nav a {{
            width: 44px; height: 44px; border-radius: 50%;
            background: var(--overlay-bg); border: 1px solid var(--card-border);
            display: flex; align-items: center; justify-content: center;
            text-decoration: none; color: var(--text-2);
            font-size: 1.2rem; font-weight: 700;
            transition: all 0.3s; backdrop-filter: blur(10px);
        }}
        .blog-nav a:hover {{
            background: var(--primary); color: var(--bg-dark);
            border-color: var(--primary); transform: scale(1.1);
        }}
        .blog-nav .nav-label {{
            font-size: 0.55rem; text-align: center;
            color: var(--text-3); font-weight: 600;
            text-transform: uppercase; letter-spacing: 0.05em;
        }}

        /* ===== OTHER STUFF MENU ===== */
        .menu-toggle {{
            position: fixed; bottom: 20px; right: 20px; z-index: 998;
            width: 56px; height: 56px; border-radius: 50%;
            background: var(--primary); color: var(--bg-dark);
            border: none; font-size: 1.5rem; cursor: pointer;
            box-shadow: 0 4px 20px {primary}44;
            transition: all 0.3s; display: flex;
            align-items: center; justify-content: center;
        }}
        .menu-toggle:hover {{ transform: scale(1.1); box-shadow: 0 6px 30px {primary}66; }}
        .menu-toggle.open {{ transform: rotate(45deg); }}

        .mega-menu {{
            position: fixed; inset: 0; z-index: 997;
            background: rgba(0,0,0,0.6); backdrop-filter: blur(5px);
            opacity: 0; pointer-events: none;
            transition: opacity 0.3s;
        }}
        .mega-menu.open {{ opacity: 1; pointer-events: auto; }}

        .mega-menu-panel {{
            position: fixed; bottom: 90px; right: 20px;
            width: 380px; max-width: 90vw; max-height: 70vh;
            overflow-y: auto; background: var(--overlay-bg);
            border: 1px solid var(--card-border);
            border-radius: 20px; padding: 1rem;
            transform: translateY(20px) scale(0.95);
            transition: all 0.3s;
        }}
        .mega-menu.open .mega-menu-panel {{
            transform: translateY(0) scale(1);
        }}

        .menu-section {{ margin-bottom: 0.75rem; }}
        .menu-section-title {{
            font-size: 0.6rem; font-weight: 800;
            text-transform: uppercase; letter-spacing: 0.1em;
            color: var(--text-3); padding: 0.25rem 0.5rem;
            margin-bottom: 0.25rem;
        }}
        .menu-item {{
            display: flex; align-items: center; gap: 0.75rem;
            padding: 0.6rem 0.75rem; border-radius: 12px;
            text-decoration: none; color: var(--text-1);
            transition: all 0.2s; font-size: 0.85rem;
        }}
        .menu-item:hover {{
            background: var(--card-bg);
            transform: translateX(4px);
        }}
        .menu-item .mi-icon {{
            width: 36px; height: 36px; border-radius: 10px;
            display: flex; align-items: center; justify-content: center;
            font-size: 1.1rem; flex-shrink: 0;
        }}
        .menu-item .mi-title {{ font-weight: 600; font-size: 0.82rem; }}
        .menu-item .mi-desc {{ font-size: 0.65rem; color: var(--text-3); }}

        /* ===== FOOTER ===== */
        .site-footer {{
            position: relative; z-index: 1;
            text-align: center; padding: 2rem 1.5rem;
            border-top: 1px solid var(--card-border);
            color: var(--text-3); font-size: 0.75rem;
        }}
        .site-footer a {{ color: var(--text-2); text-decoration: none; }}
        .site-footer a:hover {{ color: var(--primary); }}

        .theme-gallery {{
            position: relative; z-index: 1;
            max-width: 1200px; margin: 0 auto 2rem;
            padding: 0 1.5rem;
        }}
        .theme-gallery h3 {{
            font-family: '{title_font}', sans-serif;
            font-size: 1.2rem; margin-bottom: 1rem;
            text-align: center;
        }}
        .theme-dots {{
            display: flex; flex-wrap: wrap; gap: 6px;
            justify-content: center;
        }}
        .theme-dot {{
            width: 36px; height: 36px; border-radius: 50%;
            border: 2px solid var(--card-border);
            display: flex; align-items: center; justify-content: center;
            text-decoration: none; color: var(--text-3);
            font-size: 0.65rem; font-weight: 700;
            transition: all 0.3s;
        }}
        .theme-dot:hover {{
            border-color: var(--primary); color: var(--primary);
            transform: scale(1.15);
        }}
        .theme-dot.current {{
            background: var(--primary); color: var(--bg-dark);
            border-color: var(--primary); transform: scale(1.15);
        }}

        /* ===== AD SLOTS ===== */
        .ad-slot {{
            position: relative; z-index: 1;
            max-width: 900px; margin: 1rem auto;
            padding: 0 1.5rem; text-align: center;
        }}

        /* ===== RESPONSIVE ===== */
        @media (max-width: 768px) {{
            .hero {{ min-height: 50vh; padding: 5rem 1rem 2rem; }}
            .hero-title {{ font-size: clamp(2rem, 8vw, 3.5rem); }}
            .events-grid {{ grid-template-columns: 1fr 1fr; }}
            .blog-nav {{ display: none; }}
            .mobile-nav {{ display: flex !important; }}
            .mega-menu-panel {{ width: calc(100vw - 40px); bottom: 80px; right: 20px; }}
        }}
        @media (max-width: 480px) {{
            .events-grid {{ grid-template-columns: 1fr; }}
            .nav-links {{ gap: 0.5rem; }}
            .nav-links a {{ font-size: 0.65rem; }}
        }}

        .mobile-nav {{
            display: none;
            position: fixed; bottom: 0; left: 0; right: 0; z-index: 998;
            background: var(--nav-bg); backdrop-filter: blur(20px);
            border-top: 1px solid var(--card-border);
            padding: 0.5rem; justify-content: center; gap: 0.5rem;
        }}
        .mobile-nav a {{
            padding: 0.5rem 1rem; border-radius: 10px;
            text-decoration: none; color: var(--text-2);
            font-size: 0.75rem; font-weight: 600;
            transition: all 0.2s;
        }}
        .mobile-nav a:hover {{ color: var(--primary); background: var(--card-bg); }}

        /* ===== ANIMATIONS ===== */
        @keyframes fadeInUp {{
            from {{ opacity: 0; transform: translateY(30px); }}
            to {{ opacity: 1; transform: translateY(0); }}
        }}
        .fade-in {{ animation: fadeInUp 0.6s ease forwards; }}
        .fade-in-delay {{ animation: fadeInUp 0.6s ease 0.2s forwards; opacity: 0; }}
        .fade-in-delay2 {{ animation: fadeInUp 0.6s ease 0.4s forwards; opacity: 0; }}
    </style>
</head>
<body>
    <!-- Generated by Claude Code VS Code - Anthropic CLI for Claude -->
    <!-- Theme #{num} of 50: {name} -->
    <!-- {subtitle} -->

    <!-- Background Canvas -->
    <canvas id="bg-canvas"></canvas>

    <!-- Navigation -->
    <nav class="top-nav">
        <a href="/" class="nav-brand"><span>Toronto</span> Events</a>
        <div class="nav-links">
            <a href="/">Home</a>
            <a href="/blog/">Blog</a>
            <a href="/MOVIESHOWS/">Movies</a>
            <a href="/findstocks">Stocks</a>
            <span class="theme-badge">{name}</span>
        </div>
    </nav>

    <!-- Prev/Next Navigation Arrows -->
    <div class="blog-nav left">
        <a href="blog{prev_num}.html" title="Previous: Blog {prev_num}">&#8592;</a>
        <div class="nav-label">#{prev_num}</div>
    </div>
    <div class="blog-nav right">
        <a href="blog{next_num}.html" title="Next: Blog {next_num}">&#8594;</a>
        <div class="nav-label">#{next_num}</div>
    </div>

    <!-- Hero Section -->
    <section class="hero">
        <div class="hero-sub fade-in">{subtitle}</div>
        <h1 class="hero-title fade-in">Toronto Events</h1>
        <p class="hero-desc fade-in-delay">Discover the best things to do in Toronto. Filter by category, search by keyword, and find your next adventure in the city.</p>
    </section>

    <!-- Search -->
    <div class="search-container fade-in-delay2">
        <div class="search-bar">
            <input type="text" id="search-input" placeholder="Search events in Toronto..." autocomplete="off">
            <button onclick="filterEvents()">Search</button>
        </div>
    </div>

    <!-- Category Filters -->
    <div class="filters" id="filters">
        <button class="filter-btn active" data-cat="all">All Events</button>
        <button class="filter-btn" data-cat="music">Music</button>
        <button class="filter-btn" data-cat="food">Food & Drink</button>
        <button class="filter-btn" data-cat="arts">Arts & Culture</button>
        <button class="filter-btn" data-cat="sports">Sports</button>
        <button class="filter-btn" data-cat="nightlife">Nightlife</button>
        <button class="filter-btn" data-cat="family">Family</button>
        <button class="filter-btn" data-cat="outdoor">Outdoor</button>
        <button class="filter-btn" data-cat="community">Community</button>
    </div>

    <!-- Events Grid -->
    <section class="events-section">
        <div class="events-header">
            <h2>Upcoming Events</h2>
            <span class="events-count" id="events-count">Loading...</span>
        </div>
        <div class="events-grid" id="events-grid">
            <div class="loading">
                <div class="loading-spinner"></div>
                Loading Toronto events...
            </div>
        </div>
    </section>

    <!-- Ad Slot -->
    <div class="ad-slot">
        <ins class="adsbygoogle" style="display:block"
             data-ad-client="ca-pub-7893721225790912"
             data-ad-slot="auto" data-ad-format="auto"
             data-full-width-responsive="true"></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({{}});</script>
    </div>

    <!-- Theme Gallery -->
    <div class="theme-gallery">
        <h3>Explore All 50 Themes</h3>
        <div class="theme-dots" id="theme-dots"></div>
    </div>

    <!-- Footer -->
    <footer class="site-footer">
        <p>Built with love for Toronto &middot; <a href="/">Toronto Events</a> &middot; <a href="https://tdotevent.ca">TdotEvent.ca</a></p>
        <p style="margin-top:0.5rem">Generated by Claude Code VS Code | Theme #{num}: {name}</p>
    </footer>

    <!-- Mobile Bottom Nav -->
    <div class="mobile-nav">
        <a href="blog{prev_num}.html">&#8592; Prev</a>
        <a href="/">Home</a>
        <a href="blog{next_num}.html">Next &#8594;</a>
    </div>

    <!-- Other Stuff Menu Toggle -->
    <button class="menu-toggle" id="menu-toggle" title="Menu">&#9776;</button>

    <!-- Mega Menu -->
    <div class="mega-menu" id="mega-menu">
        <div class="mega-menu-panel">
            <div class="menu-section">
                <div class="menu-section-title">Explore</div>
                <a href="/" class="menu-item"><span class="mi-icon">&#127760;</span><div><div class="mi-title">Toronto Events</div><div class="mi-desc">Main event feed</div></div></a>
                <a href="/news/" class="menu-item"><span class="mi-icon">&#128240;</span><div><div class="mi-title">News Aggregator</div><div class="mi-desc">20+ RSS sources</div></div></a>
                <a href="/deals/" class="menu-item"><span class="mi-icon">&#128184;</span><div><div class="mi-title">Deals & Freebies</div><div class="mi-desc">Birthday freebies, Canadian deals</div></div></a>
                <a href="/weather/" class="menu-item"><span class="mi-icon">&#9748;</span><div><div class="mi-title">Weather</div><div class="mi-desc">Toronto forecast</div></div></a>
            </div>
            <div class="menu-section">
                <div class="menu-section-title">Entertainment</div>
                <a href="/MOVIESHOWS/" class="menu-item"><span class="mi-icon">&#127916;</span><div><div class="mi-title">Movies & Trailers</div><div class="mi-desc">Now showing in Toronto</div></div></a>
                <a href="/movieshows2/" class="menu-item"><span class="mi-icon">&#127902;</span><div><div class="mi-title">The Film Vault</div><div class="mi-desc">4,000+ curated titles</div></div></a>
                <a href="/MOVIESHOWS3/" class="menu-item"><span class="mi-icon">&#127871;</span><div><div class="mi-title">Binge Mode</div><div class="mi-desc">Save & queue trailers</div></div></a>
                <a href="/fc/#/guest" class="menu-item"><span class="mi-icon">&#128142;</span><div><div class="mi-title">Fav Creators</div><div class="mi-desc">Track your favorites</div></div></a>
            </div>
            <div class="menu-section">
                <div class="menu-section-title">Finance</div>
                <a href="/findstocks" class="menu-item"><span class="mi-icon">&#128200;</span><div><div class="mi-title">Find Stocks</div><div class="mi-desc">Stock analysis tools</div></div></a>
                <a href="/investments/" class="menu-item"><span class="mi-icon">&#128176;</span><div><div class="mi-title">Investment Hub</div><div class="mi-desc">Portfolio & dividends</div></div></a>
                <a href="/live-monitor/" class="menu-item"><span class="mi-icon">&#128202;</span><div><div class="mi-title">Live Trading</div><div class="mi-desc">20 algo paper trading</div></div></a>
                <a href="/live-monitor/sports-betting.html" class="menu-item"><span class="mi-icon">&#9917;</span><div><div class="mi-title">Sports Betting</div><div class="mi-desc">AI-powered picks</div></div></a>
            </div>
            <div class="menu-section">
                <div class="menu-section-title">Tools</div>
                <a href="/WINDOWSFIXER/" class="menu-item"><span class="mi-icon">&#128736;</span><div><div class="mi-title">Windows Boot Fixer</div><div class="mi-desc">Fix boot issues</div></div></a>
                <a href="/MENTALHEALTHRESOURCES/" class="menu-item"><span class="mi-icon">&#129504;</span><div><div class="mi-title">Mental Health</div><div class="mi-desc">Resources & support</div></div></a>
                <a href="/gotjob/" class="menu-item"><span class="mi-icon">&#128188;</span><div><div class="mi-title">GotJob</div><div class="mi-desc">Job finding hub</div></div></a>
                <a href="/vr/" class="menu-item"><span class="mi-icon">&#127918;</span><div><div class="mi-title">VR Experiences</div><div class="mi-desc">Virtual reality</div></div></a>
                <a href="/updates/" class="menu-item"><span class="mi-icon">&#128203;</span><div><div class="mi-title">Latest Updates</div><div class="mi-desc">What&#8217;s new</div></div></a>
            </div>
        </div>
    </div>

    <script>
    /* === Claude Code VS Code === */
    /* === Theme #{num}: {name} === */

    // ===== CANVAS ANIMATION =====
    (function() {{
        const c = document.getElementById('bg-canvas');
        const ctx = c.getContext('2d');
        let w, h;
        function resize() {{ w = c.width = window.innerWidth; h = c.height = window.innerHeight; }}
        resize(); window.addEventListener('resize', resize);
        {animation_js}
    }})();

    // ===== EVENT LOADING =====
    let allEvents = [];
    let currentCategory = 'all';
    let searchQuery = '';

    const EVENT_SOURCES = [
        '/next/events.json',
        '/events.json',
        '/data/events.json',
        'https://raw.githubusercontent.com/eltonaguiar/findtorontoevents.ca/main/next/events.json'
    ];

    async function loadEvents() {{
        for (const src of EVENT_SOURCES) {{
            try {{
                const res = await fetch(src);
                if (!res.ok) continue;
                const data = await res.json();
                allEvents = data.events || data || [];
                console.log('[Blog{num}] Loaded ' + allEvents.length + ' events from ' + src);
                renderEvents();
                return;
            }} catch(e) {{ continue; }}
        }}
        document.getElementById('events-grid').innerHTML =
            '<p style="text-align:center;color:var(--text-3);padding:2rem;">Unable to load events. <a href="/" style="color:var(--primary)">Visit main site</a></p>';
        document.getElementById('events-count').textContent = '';
    }}

    function categorizeEvent(evt) {{
        const text = ((evt.title || '') + ' ' + (evt.category || '') + ' ' + (evt.description || '')).toLowerCase();
        if (/music|concert|dj|band|live music|festival|jazz|hip.hop|rap|rock/.test(text)) return 'music';
        if (/food|drink|restaurant|wine|beer|tasting|brunch|dinner|culinary|chef/.test(text)) return 'food';
        if (/art|gallery|museum|exhibit|theatre|theater|dance|film|cinema|book/.test(text)) return 'arts';
        if (/sport|game|hockey|basketball|soccer|baseball|tennis|run|marathon/.test(text)) return 'sports';
        if (/night|club|bar|lounge|party|rave|afterhours/.test(text)) return 'nightlife';
        if (/family|kids|children|youth|teen|playground/.test(text)) return 'family';
        if (/outdoor|park|garden|hike|trail|beach|nature|camping/.test(text)) return 'outdoor';
        if (/community|market|fair|bazaar|volunteer|charity|workshop/.test(text)) return 'community';
        return 'community';
    }}

    function getEventEmoji(cat) {{
        const emojis = {{ music:'&#127925;', food:'&#127860;', arts:'&#127912;', sports:'&#9917;',
            nightlife:'&#127878;', family:'&#128106;', outdoor:'&#127795;', community:'&#127963;' }};
        return emojis[cat] || '&#128197;';
    }}

    function renderEvents() {{
        let filtered = allEvents;
        if (currentCategory !== 'all') {{
            filtered = filtered.filter(e => categorizeEvent(e) === currentCategory);
        }}
        if (searchQuery) {{
            const q = searchQuery.toLowerCase();
            filtered = filtered.filter(e =>
                (e.title || '').toLowerCase().includes(q) ||
                (e.description || '').toLowerCase().includes(q) ||
                (e.location || '').toLowerCase().includes(q)
            );
        }}

        const grid = document.getElementById('events-grid');
        const count = document.getElementById('events-count');

        if (filtered.length === 0) {{
            grid.innerHTML = '<p style="text-align:center;color:var(--text-3);padding:2rem;grid-column:1/-1;">No events found. Try a different filter or search.</p>';
            count.textContent = '0 events';
            return;
        }}

        count.textContent = filtered.length + ' event' + (filtered.length !== 1 ? 's' : '');

        grid.innerHTML = filtered.slice(0, 50).map(evt => {{
            const cat = categorizeEvent(evt);
            const emoji = getEventEmoji(cat);
            const date = evt.date || evt.start_date || '';
            const loc = evt.location || evt.venue || 'Toronto';
            const title = (evt.title || 'Event').replace(/</g, '&lt;');
            const url = evt.url || evt.link || '#';
            return `
                <div class="event-card" onclick="if('${{url}}'!=='#')window.open('${{url}}','_blank')">
                    <div class="event-card-img">${{emoji}}</div>
                    <div class="event-card-body">
                        <span class="event-card-tag">${{cat}}</span>
                        <div class="event-card-title">${{title}}</div>
                        <div class="event-card-meta">
                            ${{date ? '<span>&#128197; ' + date + '</span>' : ''}}
                            <span>&#128205; ${{loc.replace(/</g, '&lt;')}}</span>
                        </div>
                    </div>
                </div>`;
        }}).join('');
    }}

    function filterEvents() {{
        searchQuery = document.getElementById('search-input').value.trim();
        renderEvents();
    }}

    // Filter buttons
    document.getElementById('filters').addEventListener('click', function(e) {{
        if (e.target.classList.contains('filter-btn')) {{
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            currentCategory = e.target.dataset.cat;
            renderEvents();
        }}
    }});

    // Search on Enter
    document.getElementById('search-input').addEventListener('keyup', function(e) {{
        if (e.key === 'Enter') filterEvents();
    }});

    // Load events
    loadEvents();

    // ===== MENU TOGGLE =====
    const menuToggle = document.getElementById('menu-toggle');
    const megaMenu = document.getElementById('mega-menu');
    menuToggle.addEventListener('click', function() {{
        this.classList.toggle('open');
        megaMenu.classList.toggle('open');
        this.innerHTML = this.classList.contains('open') ? '&#10005;' : '&#9776;';
    }});
    megaMenu.addEventListener('click', function(e) {{
        if (e.target === this) {{
            menuToggle.classList.remove('open');
            megaMenu.classList.remove('open');
            menuToggle.innerHTML = '&#9776;';
        }}
    }});

    // ===== THEME DOTS =====
    (function() {{
        const nums = [{','.join(str(t[0]) for t in THEMES)}];
        const dots = document.getElementById('theme-dots');
        nums.forEach(n => {{
            const a = document.createElement('a');
            a.href = 'blog' + n + '.html';
            a.className = 'theme-dot' + (n === {num} ? ' current' : '');
            a.textContent = n;
            a.title = 'Theme #' + n;
            dots.appendChild(a);
        }});
    }})();
    </script>
</body>
</html>'''


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for theme in THEMES:
        num = theme[0]
        filename = f"blog{num}.html"
        filepath = os.path.join(OUTPUT_DIR, filename)

        html = generate_html(*theme)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"[OK] Generated {filename} - {theme[1]}")

    print(f"\nDone! Generated {len(THEMES)} themed blog pages in {OUTPUT_DIR}")


if __name__ == '__main__':
    main()
