"""Convert a Claude Code session JSONL transcript to a redacted Markdown log.

Usage:
    python tools/redact_session_log.py <input.jsonl> <output.md>

Redacts API keys, tokens, and credentials by pattern.
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

# Order matters: more-specific patterns first.
KEY_PATTERNS = [
    # Provider-prefixed keys
    (re.compile(r"sk-or-v1-[A-Za-z0-9]{40,}"),       "<<OPENROUTER_KEY_REDACTED>>"),
    (re.compile(r"sk-nous-[A-Za-z0-9]{20,}"),        "<<NOUS_KEY_REDACTED>>"),
    (re.compile(r"csk-[a-z0-9]{30,}"),               "<<CEREBRAS_KEY_REDACTED>>"),
    (re.compile(r"xai-[A-Za-z0-9]{40,}"),            "<<XAI_KEY_REDACTED>>"),
    (re.compile(r"phc_[A-Za-z0-9]{30,}"),            "<<POSTHOG_KEY_REDACTED>>"),
    (re.compile(r"bg_[a-f0-9]{20,}"),                "<<BITGET_KEY_REDACTED>>"),
    (re.compile(r"sk_[a-f0-9]{30,}"),                "<<INCEPTION_KEY_REDACTED>>"),
    (re.compile(r"sk-[a-zA-Z0-9]{30,}"),             "<<API_KEY_REDACTED>>"),
    # JWT-ish
    (re.compile(r"eyJ[A-Za-z0-9_./+-]{40,}"),        "<<JWT_REDACTED>>"),
    # Discord bot token: 24+chars.6.27+chars
    (re.compile(r"M[A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}"), "<<DISCORD_TOKEN_REDACTED>>"),
    # Long opaque hex (40-64 char) — covers FRED, generic
    (re.compile(r"\b[a-f0-9]{40,64}\b"),             "<<HEX_KEY_REDACTED>>"),
    # GOCSPX-... (Google client secret)
    (re.compile(r"GOCSPX-[A-Za-z0-9_-]{20,}"),       "<<GOOGLE_SECRET_REDACTED>>"),
    # OAuth client id pattern (digits-string.apps.googleusercontent.com)
    (re.compile(r"\d{10,}-[a-z0-9]{30,}\.apps\.googleusercontent\.com"), "<<GOOGLE_CLIENT_ID_REDACTED>>"),
    # NAME_API_KEY=value or NAME_TOKEN=value style
    (re.compile(r"((?:[A-Z][A-Z0-9_]+)?(?:_API_KEY|_TOKEN|_SECRET|_KEY|_PASS)\s*=\s*)([A-Za-z0-9_./+-]{16,})"),
     r"\1<<REDACTED>>"),
    # Standalone alphanumeric tokens >=32 chars (catch-all, may have false positives)
    (re.compile(r"\b[A-Za-z0-9]{32,}\b"),            "<<LONG_TOKEN_REDACTED>>"),
]


def redact(text: str) -> str:
    if not isinstance(text, str):
        return text
    for pattern, replacement in KEY_PATTERNS:
        text = pattern.sub(replacement, text)
    return text


def extract_text(content) -> str:
    """Pull text out of a message content field (string or list-of-blocks)."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict):
                t = block.get("type")
                if t == "text":
                    parts.append(block.get("text", ""))
                elif t == "tool_use":
                    name = block.get("name", "?")
                    inp = block.get("input", {})
                    # Summarize tool calls compactly
                    summary = json.dumps(inp, default=str)[:600]
                    parts.append(f"\n[tool: {name}] {summary}")
                elif t == "tool_result":
                    raw = block.get("content", "")
                    raw = extract_text(raw) if not isinstance(raw, str) else raw
                    parts.append(f"\n[tool result] {raw[:1500]}")
        return "\n".join(parts)
    return str(content)


def main(in_path: Path, out_path: Path) -> int:
    out_lines = []
    out_lines.append("# Claude Code Session — Redacted Log\n")
    out_lines.append(f"Source: `{in_path.name}` (size {in_path.stat().st_size:,} bytes)  ")
    out_lines.append("Generated by `tools/redact_session_log.py`. API keys, tokens, and credentials are redacted by regex; long opaque tokens (32+ chars) are also masked.\n")
    out_lines.append("---\n")

    msg_count = 0
    with in_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            mtype = rec.get("type")
            ts = rec.get("timestamp", "")
            if mtype == "user":
                msg = rec.get("message", {})
                text = extract_text(msg.get("content"))
                if text:
                    out_lines.append(f"\n## User — {ts}\n")
                    out_lines.append(redact(text)[:8000])
                    out_lines.append("\n")
                    msg_count += 1
            elif mtype == "assistant":
                msg = rec.get("message", {})
                text = extract_text(msg.get("content"))
                if text:
                    out_lines.append(f"\n## Assistant — {ts}\n")
                    out_lines.append(redact(text)[:8000])
                    out_lines.append("\n")
                    msg_count += 1

    out_lines.append(f"\n---\n\n_Total messages processed: {msg_count}_\n")
    out_path.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes, {msg_count} messages)")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.exit(main(Path(sys.argv[1]), Path(sys.argv[2])))
