#!/usr/bin/env python3
"""
Schema-only dump of ejaguiar1_stocks @ mysql.50webs.com
Outputs CREATE TABLE statements to schema-baseline.sql
Uses information_schema to generate DDL (mysqldump not available).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import pymysql

DB = {
    "host": "mysql.50webs.com", "port": 3306,
    "user": "ejaguiar1_stocks", "password": "stocks",
    "database": "ejaguiar1_stocks",
    "connect_timeout": 30, "read_timeout": 60,
    "charset": "utf8mb4", "autocommit": True,
}


def main():
    c = pymysql.connect(**DB)
    cur = c.cursor()

    # Get all tables
    cur.execute("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=%s ORDER BY TABLE_NAME", (DB["database"],))
    tables = [r[0] for r in cur.fetchall()]

    lines = []
    lines.append("-- Schema Baseline Dump")
    lines.append(f"-- DB: {DB['database']} @ {DB['host']}")
    lines.append("-- Generated by tools/schema_dump.py")
    lines.append("")

    for table in tables:
        # Get CREATE TABLE
        cur.execute(f"SHOW CREATE TABLE `{table}`")
        _, ddl = cur.fetchone()
        lines.append(ddl + ";")
        lines.append("")

    cur.close()
    c.close()

    path = "schema-baseline.sql"
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[DONE] Schema dumped to {path} ({len(tables)} tables)")


if __name__ == "__main__":
    main()
