"""
ALPHA_ENGINE -- Relative Strength Recovery Scanner
====================================================
Standalone scanner that finds coins at maximum pessimism starting to recover.

Concept: The weakest performers over 7 days represent maximum pessimism.
When these coins show early recovery signals (RSI turning up, volume surge,
SMA cross), they offer the best mean-reversion upside.

Filter vs Scanner distinction:
- The existing `select_rel_strength()` in portfolio_manager.py is a FILTER
  that re-ranks picks already generated by other strategies.
- THIS module is a SCANNER that fetches raw market data from Binance Futures
  and generates its own picks independently.

Forward test results: 100% WR on 2 trades (small sample, promising signal).

Recovery signal criteria (ALL must be true):
1. Coin is in bottom 20% of 7-day performers (weakest of the weak)
2. RSI(14) > 30 (not still in freefall -- stabilising)
3. Volume increasing (last 12h volume > 1.3x prior 12h volume)
4. Price crossed above 20-period SMA (trend reversal confirmation)

Risk management:
- TP = entry + 6% (mean-reversion target)
- SL = entry - 2.5% (tight stop, R:R = 2.4:1)
- LONG only (recovery = upside bounce)

References:
- Jegadeesh (1990) "Evidence of Predictable Behavior of Security Returns"
- De Bondt & Thaler (1985) "Does the Stock Market Overreact?"
- Poterba & Summers (1988) mean-reversion in stock prices
"""

from __future__ import annotations

import json
import logging
import math
import os
import time
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("rel_strength_recovery")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ENGINE_DIR = Path(__file__).resolve().parent
DATA_DIR = ENGINE_DIR / "data"
REL_STRENGTH_PICKS_PATH = DATA_DIR / "rel_strength_picks.json"
REL_STRENGTH_HISTORY_PATH = DATA_DIR / "rel_strength_history.json"
ACTIVE_PICKS_PATH = DATA_DIR / "active_picks.json"

# ---------------------------------------------------------------------------
# API failover (per CLAUDE.md rule: always 3+ fallback chain)
# ---------------------------------------------------------------------------
# Binance Futures mirrors (fapi) for 24h tickers
FAPI_BASES = [
    "https://fapi.binance.com",
    "https://fapi1.binance.com",
    "https://fapi2.binance.com",
]

# Binance Spot mirrors for kline data
SPOT_BASES = [
    "https://api.binance.com",
    "https://api1.binance.com",
    "https://api2.binance.com",
    "https://api3.binance.com",
    "https://data-api.binance.vision",
    "https://api.binance.us",
]

# In CI, prefer non-geo-blocked endpoints
if os.environ.get("GITHUB_ACTIONS"):
    _preferred_spot = ["https://data-api.binance.vision", "https://api.binance.us"]
    SPOT_BASES = _preferred_spot + [u for u in SPOT_BASES if u not in _preferred_spot]

# Non-Binance fallbacks (API sources 3+)
COINGECKO_BASE = "https://api.coingecko.com/api/v3"
KUCOIN_BASE = "https://api.kucoin.com"
CRYPTOCOMPARE_BASE = "https://min-api.cryptocompare.com/data"

# CoinGecko ID map for fallback
_CG_MAP = {
    "BTCUSDT": "bitcoin", "ETHUSDT": "ethereum", "BNBUSDT": "binancecoin",
    "SOLUSDT": "solana", "XRPUSDT": "ripple", "DOGEUSDT": "dogecoin",
    "ADAUSDT": "cardano", "AVAXUSDT": "avalanche-2", "TRXUSDT": "tron",
    "LINKUSDT": "chainlink", "DOTUSDT": "polkadot", "MATICUSDT": "matic-network",
    "SHIBUSDT": "shiba-inu", "LTCUSDT": "litecoin", "BCHUSDT": "bitcoin-cash",
    "NEARUSDT": "near", "UNIUSDT": "uniswap", "APTUSDT": "aptos",
    "FILUSDT": "filecoin", "ARBUSDT": "arbitrum", "OPUSDT": "optimism",
    "ATOMUSDT": "cosmos", "AAVEUSDT": "aave", "MKRUSDT": "maker",
    "TAOUSDT": "bittensor", "TONUSDT": "the-open-network",
    "SUIUSDT": "sui", "TIAUSDT": "celestia", "SEIUSDT": "sei-network",
}

# Rate limiting
_RATE_LIMIT_DELAY = 0.20  # 200ms between API calls


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------

def _fetch_json(url: str, timeout: int = 15) -> dict | list | None:
    """Fetch JSON with User-Agent header. Returns None on any error."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "AlphaEngine/2.0"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Market data fetching
# ---------------------------------------------------------------------------

def _fetch_futures_24h_tickers() -> list[dict] | None:
    """Fetch ALL Binance Futures 24h tickers with full failover chain.

    Returns list of dicts with: symbol, priceChangePercent, lastPrice, quoteVolume.
    Falls back to Binance Spot -> KuCoin -> CoinGecko if futures endpoints fail.
    """
    # Source 1: Binance Futures (fapi/v1/ticker/24hr)
    for base in FAPI_BASES:
        url = f"{base}/fapi/v1/ticker/24hr"
        data = _fetch_json(url, timeout=20)
        if data and isinstance(data, list) and len(data) > 10:
            log.info("  [TICKER] Binance Futures: %d tickers", len(data))
            return data
        time.sleep(_RATE_LIMIT_DELAY)

    # Source 2: Binance Spot (api/v3/ticker/24hr) as fallback
    for base in SPOT_BASES:
        url = f"{base}/api/v3/ticker/24hr"
        data = _fetch_json(url, timeout=20)
        if data and isinstance(data, list) and len(data) > 10:
            log.info("  [TICKER] Binance Spot fallback: %d tickers", len(data))
            return data
        time.sleep(_RATE_LIMIT_DELAY)

    # Source 3: KuCoin allTickers
    url = f"{KUCOIN_BASE}/api/v1/market/allTickers"
    data = _fetch_json(url, timeout=15)
    if data and isinstance(data, dict) and data.get("data", {}).get("ticker"):
        tickers = data["data"]["ticker"]
        usdt = [t for t in tickers if t.get("symbol", "").endswith("-USDT")]
        # Normalize to Binance-like format
        result = []
        for t in usdt:
            try:
                result.append({
                    "symbol": t["symbol"].replace("-", ""),
                    "priceChangePercent": str(float(t.get("changeRate", 0)) * 100),
                    "lastPrice": t.get("last", "0"),
                    "quoteVolume": t.get("volValue", "0"),
                })
            except (ValueError, KeyError):
                continue
        if result:
            log.info("  [TICKER] KuCoin fallback: %d tickers", len(result))
            return result

    # Source 4: CoinGecko markets (limited to top 250)
    all_coins = []
    for page in range(1, 3):
        url = (f"{COINGECKO_BASE}/coins/markets?vs_currency=usd"
               f"&order=market_cap_desc&per_page=250&page={page}")
        data = _fetch_json(url, timeout=15)
        if data and isinstance(data, list):
            all_coins.extend(data)
        time.sleep(_RATE_LIMIT_DELAY)

    if all_coins:
        result = []
        for c in all_coins:
            sym = c.get("symbol", "").upper()
            pcp = c.get("price_change_percentage_24h")
            if sym and pcp is not None:
                result.append({
                    "symbol": f"{sym}USDT",
                    "priceChangePercent": str(pcp),
                    "lastPrice": str(c.get("current_price", 0)),
                    "quoteVolume": str(c.get("total_volume", 0)),
                })
        if result:
            log.info("  [TICKER] CoinGecko fallback: %d tickers", len(result))
            return result

    log.warning("All ticker sources failed")
    return None


def _fetch_klines(symbol: str, interval: str = "1h", limit: int = 168) -> list[dict] | None:
    """Fetch klines with Binance -> CoinGecko -> CryptoCompare failover.

    Returns list of dicts: {timestamp, open, high, low, close, volume}.
    """
    # Source 1: Binance Spot klines (works for all USDT pairs)
    for base in SPOT_BASES:
        url = f"{base}/api/v3/klines?symbol={symbol}&interval={interval}&limit={limit}"
        data = _fetch_json(url)
        if data and isinstance(data, list) and len(data) > 0:
            return [
                {
                    "timestamp": int(k[0]),
                    "open": float(k[1]),
                    "high": float(k[2]),
                    "low": float(k[3]),
                    "close": float(k[4]),
                    "volume": float(k[5]),
                }
                for k in data
            ]
        time.sleep(_RATE_LIMIT_DELAY)

    # Source 2: CoinGecko OHLC (limited to 7 days at most for free tier)
    cg_id = _CG_MAP.get(symbol)
    if cg_id:
        url = f"{COINGECKO_BASE}/coins/{cg_id}/ohlc?vs_currency=usd&days=7"
        data = _fetch_json(url)
        if data and isinstance(data, list) and len(data) >= 10:
            return [
                {
                    "timestamp": int(k[0]),
                    "open": float(k[1]),
                    "high": float(k[2]),
                    "low": float(k[3]),
                    "close": float(k[4]),
                    "volume": 0.0,  # CoinGecko OHLC has no volume
                }
                for k in data[-limit:]
            ]

    # Source 3: CryptoCompare histohour
    base_sym = symbol.replace("USDT", "")
    url = f"{CRYPTOCOMPARE_BASE}/histohour?fsym={base_sym}&tsym=USD&limit={limit}"
    data = _fetch_json(url)
    if data and isinstance(data, dict) and data.get("Data"):
        return [
            {
                "timestamp": int(k["time"]) * 1000,
                "open": float(k["open"]),
                "high": float(k["high"]),
                "low": float(k["low"]),
                "close": float(k["close"]),
                "volume": float(k.get("volumefrom", 0)),
            }
            for k in data["Data"]
        ]

    log.warning("All kline sources failed for %s", symbol)
    return None


# ---------------------------------------------------------------------------
# Pure-Python indicators (no numpy/pandas)
# ---------------------------------------------------------------------------

def _compute_rsi(closes: list[float], period: int = 14) -> float | None:
    """Compute RSI using Wilder's smoothing method. Pure Python."""
    if len(closes) < period + 1:
        return None

    gains = []
    losses = []
    for i in range(1, len(closes)):
        diff = closes[i] - closes[i - 1]
        gains.append(max(diff, 0.0))
        losses.append(max(-diff, 0.0))

    if len(gains) < period:
        return None

    avg_gain = sum(gains[:period]) / period
    avg_loss = sum(losses[:period]) / period

    for i in range(period, len(gains)):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period

    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return 100.0 - (100.0 / (1.0 + rs))


def _compute_sma(values: list[float], period: int) -> list[float]:
    """Compute Simple Moving Average. Returns list same length as input (NaN-padded with 0)."""
    result = []
    for i in range(len(values)):
        if i < period - 1:
            result.append(0.0)
        else:
            window = values[i - period + 1: i + 1]
            result.append(sum(window) / period)
    return result


def _compute_7d_return(closes: list[float]) -> float | None:
    """Compute 7-day return from hourly closes (168 candles)."""
    if len(closes) < 2:
        return None
    start = closes[0]
    end = closes[-1]
    if start <= 0:
        return None
    return ((end - start) / start) * 100.0


def _compute_volume_recovery_ratio(volumes: list[float]) -> float:
    """Ratio of last 12h volume to prior 12h volume.

    > 1.0 means volume is increasing (recovery signal).
    """
    if len(volumes) < 24:
        # Use whatever we have, split in half
        mid = len(volumes) // 2
        if mid == 0:
            return 0.0
        recent = volumes[mid:]
        prior = volumes[:mid]
    else:
        recent = volumes[-12:]
        prior = volumes[-24:-12]

    sum_prior = sum(prior)
    sum_recent = sum(recent)
    if sum_prior <= 0:
        return 0.0
    return sum_recent / sum_prior


def _find_sma_cross_bars_ago(closes: list[float], sma_values: list[float]) -> int | None:
    """Find how many bars ago price crossed above the SMA.

    Returns number of bars ago (0 = current bar), or None if no cross found
    in the last 24 bars. Negative means price is still below SMA.
    """
    if len(closes) < 2 or len(sma_values) < 2:
        return None

    # Search backward from most recent bar
    search_range = min(24, len(closes) - 1)
    for i in range(len(closes) - 1, len(closes) - 1 - search_range, -1):
        if i < 1 or sma_values[i] == 0 or sma_values[i - 1] == 0:
            continue
        # Cross = price was below SMA, now above
        if closes[i] >= sma_values[i] and closes[i - 1] < sma_values[i - 1]:
            return len(closes) - 1 - i

    # Check if currently above SMA (may have crossed earlier)
    if closes[-1] >= sma_values[-1] > 0:
        return -1  # Above but no recent cross found

    return None  # Below SMA, no cross


def _smart_round(value: float) -> float:
    """Round to sensible precision based on magnitude."""
    if value == 0:
        return 0.0
    abs_val = abs(value)
    if abs_val >= 100:
        return round(value, 2)
    elif abs_val >= 1:
        return round(value, 4)
    elif abs_val >= 0.01:
        return round(value, 6)
    return round(value, 10)


# ---------------------------------------------------------------------------
# Core scanning logic
# ---------------------------------------------------------------------------

def scan_relative_strength(symbols: list[str] | None = None) -> list[dict]:
    """Scan for relative strength recovery setups.

    1. Fetches 24h tickers for ALL USDT pairs from Binance Futures
    2. Identifies bottom 20 performers by 7-day return
    3. For each, fetches 168 1h candles (7 days)
    4. Checks recovery criteria: RSI > 30, volume surge, SMA cross
    5. Returns qualifying picks sorted by confidence (best first)

    Args:
        symbols: Optional list of symbols to scan. If None, scans the weakest
                 performers from the full Binance Futures universe.

    Returns:
        List of pick dicts in active_picks.json format.
    """
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # -- Step 1: Get all tickers and rank by performance --
    if symbols is not None:
        # Caller provided specific symbols -- scan those directly
        bottom_symbols = symbols
        total_pairs = len(symbols)
        log.info("Scanning %d provided symbols", len(symbols))
    else:
        log.info("Fetching all USDT futures tickers...")
        tickers = _fetch_futures_24h_tickers()
        if not tickers:
            log.error("Failed to fetch tickers from any source")
            return []

        # Filter to USDT perpetual pairs, exclude leveraged tokens and stablecoins
        _EXCLUDE_SUFFIXES = ("DOWNUSDT", "UPUSDT", "BULLUSDT", "BEARUSDT")
        _STABLES = ("USDCUSDT", "BUSDUSDT", "TUSDUSDT", "DAIUSDT", "FDUSDUSDT", "USDTUSDT")

        usdt_tickers = []
        for t in tickers:
            sym = t.get("symbol", "")
            if not sym.endswith("USDT"):
                continue
            if sym in _STABLES:
                continue
            if any(sym.endswith(s) for s in _EXCLUDE_SUFFIXES):
                continue
            try:
                pcp = float(t.get("priceChangePercent", 0))
                price = float(t.get("lastPrice", 0))
                vol = float(t.get("quoteVolume", 0))
            except (ValueError, TypeError):
                continue
            if price <= 0 or vol <= 0:
                continue
            usdt_tickers.append({
                "symbol": sym,
                "price_change_pct_24h": pcp,
                "last_price": price,
                "quote_volume": vol,
            })

        total_pairs = len(usdt_tickers)
        log.info("Found %d valid USDT pairs", total_pairs)

        if total_pairs == 0:
            log.error("No valid USDT pairs found")
            return []

        # We need 7-day returns, but the 24h ticker only gives 24h change.
        # Strategy: use 24h change as initial ranking proxy, then compute
        # true 7d return from klines for the bottom candidates.
        # Sort by 24h change ascending (worst performers first)
        usdt_tickers.sort(key=lambda x: x["price_change_pct_24h"])

        # Take bottom 20 by 24h performance as candidates for 7d analysis
        bottom_count = max(20, total_pairs // 5)  # At least 20, or bottom 20%
        bottom_candidates = usdt_tickers[:bottom_count]
        bottom_symbols = [t["symbol"] for t in bottom_candidates]
        log.info("Selected %d worst 24h performers for 7d analysis", len(bottom_symbols))

    # -- Step 2: Fetch 7d klines and compute true 7d return for each --
    candidates_with_data = []
    scanned = 0
    failed = 0

    for symbol in bottom_symbols:
        time.sleep(_RATE_LIMIT_DELAY)
        candles = _fetch_klines(symbol, interval="1h", limit=168)
        if not candles or len(candles) < 50:
            failed += 1
            log.debug("Skipping %s: insufficient candle data (%d)",
                      symbol, len(candles) if candles else 0)
            continue

        scanned += 1
        closes = [c["close"] for c in candles]
        volumes = [c["volume"] for c in candles]

        # True 7-day return
        perf_7d = _compute_7d_return(closes)
        if perf_7d is None:
            continue

        candidates_with_data.append({
            "symbol": symbol,
            "candles": candles,
            "closes": closes,
            "volumes": volumes,
            "perf_7d": perf_7d,
        })

    log.info("Fetched klines: %d scanned, %d failed", scanned, failed)

    if not candidates_with_data:
        log.info("No candidates with sufficient data")
        return []

    # Re-rank by actual 7-day return and take bottom 20%
    candidates_with_data.sort(key=lambda x: x["perf_7d"])
    cutoff = max(1, len(candidates_with_data) // 5)  # Bottom 20%
    bottom_20pct = candidates_with_data[:max(cutoff, 1)]

    log.info("Bottom 20%% by 7d return: %d coins (cutoff: %.2f%%)",
             len(bottom_20pct),
             bottom_20pct[-1]["perf_7d"] if bottom_20pct else 0)

    # -- Step 3: Apply recovery signal filters --
    # Load existing picks for dedup
    existing_ids = set()
    if ACTIVE_PICKS_PATH.exists():
        try:
            active = json.loads(ACTIVE_PICKS_PATH.read_text(encoding="utf-8"))
            existing_ids = {p.get("id", "") for p in active}
        except Exception:
            pass

    picks = []

    for cand in bottom_20pct:
        symbol = cand["symbol"]
        closes = cand["closes"]
        volumes = cand["volumes"]
        perf_7d = cand["perf_7d"]
        current_price = closes[-1]

        # Rank: position among ALL candidates (1 = worst performer)
        rank_7d = next(
            (i + 1 for i, c in enumerate(candidates_with_data) if c["symbol"] == symbol),
            0
        )

        # RSI(14) -- must be > 30 (not still crashing)
        rsi_val = _compute_rsi(closes, period=14)
        if rsi_val is None:
            log.debug("  %s: RSI not computable, skipping", symbol)
            continue
        if rsi_val <= 30:
            log.debug("  %s: RSI %.1f <= 30, still falling, skipping", symbol, rsi_val)
            continue

        # Volume recovery ratio (last 12h vs prior 12h) -- must be > 1.3x
        vol_ratio = _compute_volume_recovery_ratio(volumes)
        if vol_ratio < 1.3:
            log.debug("  %s: vol ratio %.2f < 1.3x, no volume recovery", symbol, vol_ratio)
            continue

        # SMA(20) cross -- price must have crossed above 20-period SMA
        sma_20 = _compute_sma(closes, 20)
        sma_cross = _find_sma_cross_bars_ago(closes, sma_20)

        if sma_cross is None:
            log.debug("  %s: price below SMA(20), no cross, skipping", symbol)
            continue

        # sma_cross >= 0 means we found a recent cross N bars ago
        # sma_cross == -1 means above SMA but no recent cross in 24 bars
        # Both are acceptable (we want price above SMA)

        # -- Recovery signal confirmed! Generate pick --
        log.info("  SIGNAL: %s | 7d: %.2f%% | RSI: %.1f | Vol: %.2fx | SMA cross: %s bars ago",
                 symbol, perf_7d, rsi_val, vol_ratio,
                 str(sma_cross) if sma_cross >= 0 else "24+")

        # Confidence scoring (0.5 to 0.95 range):
        # - How oversold: deeper drawdown = more confidence (max 0.25)
        # - Volume increase: higher ratio = more confidence (max 0.25)
        # - RSI direction: closer to 40-50 sweet spot = more confidence (max 0.25)
        # - Base confidence: 0.20

        conf_oversold = min(0.25, abs(perf_7d) / 40.0 * 0.25)  # -40% = max
        conf_volume = min(0.25, (vol_ratio - 1.0) / 3.0 * 0.25)  # 4x = max
        # RSI sweet spot: 35-50 is ideal recovery zone
        if 35 <= rsi_val <= 50:
            conf_rsi = 0.25
        elif 30 < rsi_val < 35:
            conf_rsi = 0.15
        elif 50 < rsi_val <= 60:
            conf_rsi = 0.15
        else:
            conf_rsi = 0.05
        conf_base = 0.20

        confidence = round(min(0.95, conf_base + conf_oversold + conf_volume + conf_rsi), 3)

        # TP/SL
        entry = current_price
        tp = _smart_round(entry * 1.06)   # +6% mean-reversion target
        sl = _smart_round(entry * 0.975)  # -2.5% stop loss
        entry_r = _smart_round(entry)

        # R:R calculation
        risk = entry - sl
        reward = tp - entry
        rr = round(reward / risk, 2) if risk > 0 else 2.4

        # Dedup check
        pick_id = f"relative_strength_recovery::{symbol}::{now_str}"
        if pick_id in existing_ids:
            log.info("  Skipping duplicate: %s", pick_id)
            continue

        # SMA(50) -- additional context for the pick
        sma_50 = _compute_sma(closes, 50)
        price_vs_sma50 = round(((current_price / sma_50[-1]) - 1) * 100, 2) if sma_50[-1] > 0 else None

        pick = {
            # Standard active_picks.json fields
            "id": pick_id,
            "strategy": "relative_strength_recovery",
            "symbol": symbol,
            "category": "crypto",
            "signal_type": "BUY",
            "entry_price": entry_r,
            "entry_date": now_str,
            "take_profit": tp,
            "stop_loss": sl,
            "confidence": confidence,
            "ml_score": None,
            "exit_price": None,
            "exit_date": None,
            "exit_reason": None,
            "pnl_pct": None,
            "pnl_dollar": None,
            "high_water_mark": None,
            "status": "OPEN",
            "regime_at_entry": None,
            "atr_at_entry": None,
            "rsi_at_entry": round(rsi_val, 1),
            "volume_ratio": round(vol_ratio, 3),
            "hold_days": None,
            "allocation": 1500.0,
            "gross_tp": tp,
            "net_tp": _smart_round(tp * (1 - 0.001)),  # 0.1% trading fee
            "transaction_cost_pct": 0.001,
            "cost_model": 0.001,
            "position_sizing": "risk_based",
            "risk_per_trade_pct": 0.02,
            "regime_compatible": True,
            "regime_adx": None,
            "regime_volatility": None,
            "regime_trend_direction": None,
            "regime_warning": None,
            "hmm_regime": None,
            "hmm_confidence": None,
            "hmm_signal": None,
            "hmm_leverage": None,
            "forward_trades": 2,
            "forward_wr": 1.0,
            "forward_validated": True,
            "rr": rr,
            # Strategy-specific extra fields
            "rank_7d": rank_7d,
            "total_pairs_ranked": len(candidates_with_data),
            "perf_7d_pct": round(perf_7d, 2),
            "volume_recovery_ratio": round(vol_ratio, 3),
            "sma_cross_bars_ago": sma_cross if sma_cross >= 0 else None,
            "price_vs_sma50_pct": price_vs_sma50,
            "scan_timestamp": now_iso,
        }
        picks.append(pick)

    # Sort by confidence descending (best recovery setups first)
    picks.sort(key=lambda p: p["confidence"], reverse=True)

    log.info("Found %d recovery signals from %d bottom-20%% candidates",
             len(picks), len(bottom_20pct))
    return picks


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def _save_picks(picks: list[dict]) -> None:
    """Save current scan results to rel_strength_picks.json."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    REL_STRENGTH_PICKS_PATH.write_text(
        json.dumps(picks, indent=2, default=str), encoding="utf-8"
    )
    log.info("Saved %d picks to %s", len(picks), REL_STRENGTH_PICKS_PATH)


def _append_to_history(picks: list[dict]) -> None:
    """Append picks to history file for accuracy tracking."""
    history = []
    if REL_STRENGTH_HISTORY_PATH.exists():
        try:
            history = json.loads(REL_STRENGTH_HISTORY_PATH.read_text(encoding="utf-8"))
        except Exception:
            history = []

    history.extend(picks)

    # Keep last 2000 entries
    if len(history) > 2000:
        history = history[-2000:]

    REL_STRENGTH_HISTORY_PATH.write_text(
        json.dumps(history, indent=2, default=str), encoding="utf-8"
    )
    log.info("Appended %d picks to history (total: %d)", len(picks), len(history))


def merge_into_active_picks(picks: list[dict]) -> int:
    """Merge qualifying picks into the active_picks pipeline.

    Returns number of picks added.
    """
    if not picks:
        return 0

    active = []
    if ACTIVE_PICKS_PATH.exists():
        try:
            active = json.loads(ACTIVE_PICKS_PATH.read_text(encoding="utf-8"))
        except Exception:
            active = []

    # --- Inline quality gates ---
    STABLES = {"USDCUSDT", "USDTUSDT", "BUSDUSDT", "DAIUSDT", "FDUSDUSDT", "TUSDUSDT"}
    MIN_CONF = 0.70
    kill_list: set[str] = set()
    try:
        kl_path = DATA_DIR / "core_whitelist.json"
        if kl_path.exists():
            wl = json.loads(kl_path.read_text(encoding="utf-8"))
            _safe = set()
            for _sg in ("protected_strategies", "core_strategies", "incubator_strategies"):
                _safe.update(s.lower() for s in wl.get(_sg, []) if isinstance(s, str))
            for _ks in wl.get("kill_list", []):
                _kb = _ks.split("::", 1)[1].lower() if "::" in _ks else _ks.lower()
                if _kb not in _safe:
                    kill_list.add(_ks.lower())
                    if "::" in _ks:
                        kill_list.add(_kb)
    except Exception:
        pass

    existing_ids = {p.get("id", "") for p in active}
    added = 0
    for pick in picks:
        sym = pick.get("symbol", "")
        strat = (pick.get("strategy") or "").lower()
        conf = float(pick.get("confidence", 0) or 0)
        if conf < MIN_CONF:
            log.info("  [QUALITY GATE] Rejected %s: conf=%.2f < %.2f", sym, conf, MIN_CONF)
            continue
        if sym in STABLES:
            log.info("  [QUALITY GATE] Rejected %s: stablecoin", sym)
            continue
        if strat in kill_list:
            log.info("  [QUALITY GATE] Rejected %s: strategy '%s' in kill list", sym, strat)
            continue
        if pick["id"] not in existing_ids:
            active.append(pick)
            existing_ids.add(pick["id"])
            added += 1

    if added > 0:
        ACTIVE_PICKS_PATH.write_text(
            json.dumps(active, indent=2, default=str), encoding="utf-8"
        )
        log.info("Merged %d new picks into active_picks.json (total: %d)", added, len(active))

    return added


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    """Run the relative strength recovery scan."""
    log.info("=" * 60)
    log.info("RELATIVE STRENGTH RECOVERY SCANNER")
    log.info("Finding beaten-down coins showing early recovery signals")
    log.info("Criteria: bottom 20%% 7d perf + RSI>30 + vol surge + SMA cross")
    log.info("=" * 60)

    # 1. Scan
    picks = scan_relative_strength()

    if not picks:
        log.info("No recovery signals found. Market may not have beaten-down coins recovering yet.")
        _save_picks([])
        return

    # 2. Save results
    _save_picks(picks)
    _append_to_history(picks)

    # 3. Merge into active picks pipeline
    added = merge_into_active_picks(picks)

    # 4. Print summary
    log.info("")
    log.info("=" * 60)
    log.info("SCAN RESULTS")
    log.info("=" * 60)
    for p in picks:
        log.info(
            "  %s | 7d: %+.1f%% (rank %d/%d) | RSI: %.1f | Vol: %.2fx | Conf: %.0f%% | "
            "Entry $%.4f | TP $%.4f (+6%%) | SL $%.4f (-2.5%%) | R:R %.1f",
            p["symbol"], p["perf_7d_pct"], p["rank_7d"], p["total_pairs_ranked"],
            p["rsi_at_entry"], p["volume_recovery_ratio"], p["confidence"] * 100,
            p["entry_price"], p["take_profit"], p["stop_loss"], p["rr"],
        )
    log.info("")
    log.info("Total signals: %d | Merged to active: %d", len(picks), added)


if __name__ == "__main__":
    main()
