"""Top-3 Cross-AI-Consensus Strategy Runner.

Wires the three fresh academic-literature strategies into the pick flow:
1. Faber 10-month tactical MA (ETF)
2. Magic Formula + Piotroski (EQUITY)
3. COT Commercial-Extremes + Seasonal (COMMODITY)

This runner performs a 'dry-run' check to ensure they would emit picks,
and then appends them to the active picks pool with 'shadow' status.
"""
from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from alpha_engine.faber_etf_strategy import generate_faber_picks
from alpha_engine.value_screener_runner import run as run_ueps
from alpha_engine.commodity_cot_contrarian import commodity_cot_contrarian_picks
from alpha_engine.commodity_seasonal import generate_picks as generate_commodity_seasonal_picks

logger = logging.getLogger(__name__)

ACTIVE_PICKS_PATH = Path("alpha_engine/data/active_picks.json")

def load_active_picks():
    if not ACTIVE_PICKS_PATH.exists():
        return []
    try:
        data = json.loads(ACTIVE_PICKS_PATH.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return data.get("picks", [])
        return data
    except Exception:
        return []

def save_active_picks(picks: list):
    payload = {
        "picks": picks,
        "last_updated": datetime.now(timezone.utc).isoformat(),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "top3_consensus_runner"
    }
    ACTIVE_PICKS_PATH.parent.mkdir(parents=True, exist_ok=True)
    ACTIVE_PICKS_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")

def run_all_top3():
    logging.basicConfig(level=logging.INFO)
    logger.info("Starting Top-3 Cross-AI-Consensus Strategy Runner")
    
    all_new_picks = []
    
    # 1. Faber 10mo MA (ETF)
    logger.info("Running Faber 10mo MA (ETF)...")
    try:
        faber_picks = generate_faber_picks()
        logger.info(f"Faber 10mo MA emitted {len(faber_picks)} picks.")
        all_new_picks.extend(faber_picks)
    except Exception as e:
        logger.error(f"Faber 10mo MA failed: {e}")

    # 2. Magic Formula + Piotroski (EQUITY)
    logger.info("Running Magic Formula + Piotroski (EQUITY)...")
    try:
        # We run it in dry-run mode to get the picks back without it managing the file itself
        # so we can consolidate here.
        ueps_summary, long_picks, short_picks = run_ueps(dry_run=True)
        logger.info(f"UEPS summary: {ueps_summary}")
        logger.info(f"UEPS emitted {len(long_picks)} LONG and {len(short_picks)} SHORT picks.")
        all_new_picks.extend(long_picks)
        all_new_picks.extend(short_picks)
    except Exception as e:
        logger.error(f"UEPS runner failed: {e}")

    # 3a. COT Commercial-Extremes (COMMODITY)
    logger.info("Running COT Commercial-Extremes (COMMODITY)...")
    try:
        os.environ["COMMODITY_COT_CONTRARIAN_DISABLED"] = "0"
        cot_picks = commodity_cot_contrarian_picks()
        logger.info(f"COT Contrarian emitted {len(cot_picks)} picks.")
        all_new_picks.extend(cot_picks)
    except Exception as e:
        logger.error(f"COT Contrarian failed: {e}")

    # 3b. Seasonal (COMMODITY)
    logger.info("Running Commodity Seasonal...")
    try:
        os.environ["COMMODITY_SEASONAL_ENABLED"] = "1"
        seasonal_picks = generate_commodity_seasonal_picks()
        logger.info(f"Commodity Seasonal emitted {len(seasonal_picks)} picks.")
        all_new_picks.extend(seasonal_picks)
    except Exception as e:
        logger.error(f"Commodity Seasonal failed: {e}")

    # Consolidate and Save
    if all_new_picks:
        logger.info(f"Consolidating {len(all_new_picks)} new consensus picks.")
        existing_picks = load_active_picks()
        # Filter out old versions of these strategies to avoid duplicates
        strategy_names = {p["strategy"] for p in all_new_picks}
        filtered_existing = [p for p in existing_picks if p.get("strategy") not in strategy_names]
        
        # Tag as 'shadow' per roadmap
        for p in all_new_picks:
            p["sizing_status"] = "shadow"
            p["paper_pilot"] = True
            p["pilot_start_date"] = "2026-06-01"
            
        save_active_picks(filtered_existing + all_new_picks)
        logger.info("Saved consolidated picks to active_picks.json")
    else:
        logger.info("No new picks generated by Top-3 Consensus.")

if __name__ == "__main__":
    run_all_top3()
