-- ============================================================
-- Migration: Add FUTURES, ETF, COMMODITY to asset_class ENUMs
-- Date: 2026-03-11 (updated 2026-03-26: added COMMODITY)
-- ============================================================
-- MySQL ALTER COLUMN to expand ENUM values.
-- Safe: only ADDS new values, never removes existing ones.

ALTER TABLE at_raw_picks
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE at_consensus_picks
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE at_audit_events
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE at_filter_log
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE at_strategy_stats
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE at_discord_sent
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE bt_backtest_runs
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE bt_backtest_trades
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';

ALTER TABLE at_sqlite_imports
  MODIFY COLUMN asset_class ENUM('CRYPTO','FOREX','EQUITY','PENNY_STOCK','MEMECOIN','SPORTS','FUTURES','ETF','COMMODITY','UNKNOWN') DEFAULT 'UNKNOWN';
