<?php
/**
 * Alpha Engine Picks API
 *
 * Serves picks generated by the Python Alpha Engine (uploaded via GitHub Actions).
 * Returns JSON compatible with the existing findstocks frontend.
 *
 * Endpoints:
 *   ?type=picks      - Latest picks with scores, sizing, stops
 *   ?type=regime     - Current market regime classification
 *   ?type=algorithms - List of alpha algorithms
 *   ?type=report     - Latest report summary
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Cache-Control: public, max-age=300');

$type = isset($_GET['type']) ? $_GET['type'] : 'picks';
$alpha_dir = dirname(__FILE__) . '/../alpha/';

// Helper: read JSON file safely
function read_alpha_json($path) {
    if (!file_exists($path)) {
        return null;
    }
    $content = file_get_contents($path);
    if ($content === false) {
        return null;
    }
    $data = json_decode($content, true);
    return $data;
}

switch ($type) {
    case 'picks':
        $picks = read_alpha_json($alpha_dir . 'latest_picks.json');
        if ($picks === null) {
            echo json_encode(array(
                'ok' => false,
                'error' => 'No picks available. Run Alpha Engine first.',
                'hint' => 'Trigger the alpha-engine-daily-picks GitHub Action'
            ));
        } else {
            $mtime = filemtime($alpha_dir . 'latest_picks.json');
            $age_hours = (time() - $mtime) / 3600;
            echo json_encode(array(
                'ok' => true,
                'picks' => $picks,
                'count' => count($picks),
                'generated_at' => date('Y-m-d H:i:s', $mtime),
                'age_hours' => round($age_hours, 1),
                'stale' => ($age_hours > 24)
            ));
        }
        break;

    case 'regime':
        $regime = read_alpha_json($alpha_dir . 'alpha_regime.json');
        if ($regime === null) {
            echo json_encode(array('ok' => false, 'error' => 'No regime data available'));
        } else {
            echo json_encode(array('ok' => true, 'regime' => $regime));
        }
        break;

    case 'algorithms':
        $algos = read_alpha_json($alpha_dir . 'alpha_algorithms.json');
        if ($algos === null) {
            // Return hardcoded list as fallback
            $algos = array(
                array('name' => 'alpha_momentum', 'display_name' => 'Alpha Momentum', 'family' => 'momentum'),
                array('name' => 'alpha_mean_reversion', 'display_name' => 'Alpha Mean Reversion', 'family' => 'mean_reversion'),
                array('name' => 'alpha_earnings_drift', 'display_name' => 'Alpha Earnings Drift', 'family' => 'earnings'),
                array('name' => 'alpha_quality', 'display_name' => 'Alpha Quality', 'family' => 'quality'),
                array('name' => 'alpha_value', 'display_name' => 'Alpha Value+Quality', 'family' => 'value'),
                array('name' => 'alpha_dividend', 'display_name' => 'Alpha Dividend Aristocrats', 'family' => 'dividend'),
                array('name' => 'alpha_safe_bet', 'display_name' => 'Alpha Safe Bet', 'family' => 'safe_bet'),
                array('name' => 'alpha_ml_ranker', 'display_name' => 'Alpha ML Ranker', 'family' => 'ml'),
                array('name' => 'alpha_meta_ensemble', 'display_name' => 'Alpha Meta Ensemble', 'family' => 'ensemble')
            );
        }
        echo json_encode(array('ok' => true, 'algorithms' => $algos));
        break;

    case 'report':
        // Find latest report markdown
        $reports = glob($alpha_dir . 'report_*.md');
        if (empty($reports)) {
            echo json_encode(array('ok' => false, 'error' => 'No reports available'));
        } else {
            rsort($reports);
            $latest = $reports[0];
            $content = file_get_contents($latest);
            $mtime = filemtime($latest);
            echo json_encode(array(
                'ok' => true,
                'report' => $content,
                'filename' => basename($latest),
                'generated_at' => date('Y-m-d H:i:s', $mtime)
            ));
        }
        break;

    default:
        echo json_encode(array(
            'ok' => false,
            'error' => 'Unknown type. Use: picks, regime, algorithms, report'
        ));
}
